export interface ApplicationFieldDef {
  key: string
  label: string
  section: 'registration' | 'basicDetails' | 'familyDetails' | 'visaDetails' | 'additionalQuestions' | 'photoUpload'
  subsection?: string
  inputType: 'text' | 'select' | 'date' | 'radio' | 'checkbox' | 'textarea'
  options?: { value: string; label: string }[]
  targetMappingField: string
  sourceApplicantPath?: string
  requiredInPortal?: boolean
  description?: string
  manualNotice?: string
  placeholder?: string
  visibleByDefault?: boolean
}

export interface ApplicationSectionDef {
  id: 'registration' | 'basicDetails' | 'familyDetails' | 'visaDetails' | 'additionalQuestions' | 'photoUpload'
  title: string
  subtitle: string
  iconName: string
  fields: ApplicationFieldDef[]
  manualNotices?: { title: string; message: string }[]
}

export interface WorkspaceSectionCardDef {
  id: string
  title: string
  subtitle: string
  iconName: string
  fieldKeys: string[]
  manualNotices?: { title: string; message: string }[]
}

export const WORKSPACE_DEFAULT_VISIBLE_FIELDS: string[] = [
  // 1. Personal Details (13)
  'appl.surname',
  'appl.applname',
  'appl.applsex',
  'appl.birthdate',
  'appl.placbrth',
  'appl.country_of_birth',
  'appl.nationality',
  'appl.nationality_by',
  'appl.nic_no',
  'appl.religion',
  'appl.visual_mark',
  'appl.edu_id',
  'marital_status',

  // 2. Passport Details (9)
  'appl.passport_number',
  'appl.passport_issue_place',
  'appl.passport_issue_date',
  'appl.passport_expiry_date',
  'appl.oth_ppt',
  'appl.oth_pptno',
  'appl.oth_ppt_issue_place',
  'appl.prev_passport_country_issue',
  'appl.other_ppt_nationality',

  // 3. Present Address (11)
  'pres_addr1',
  'pres_addr2',
  'village_town_city',
  'district',
  'state_province',
  'present_country',
  'pincode',
  'pres_phone',
  'isd_code',
  'mobile',
  'appl.email',

  // 4. Permanent Address (7)
  'perm_add1',
  'perm_add2',
  'permanent_village_town_city',
  'permanent_district',
  'permanent_state_province',
  'permanent_country',
  'permanent_postal_code',

  // 5. Family Details (16)
  'fthrname',
  'father_place_of_birth',
  'father_country_of_birth',
  'father_nationality',
  'father_prev_nationality',
  'mother_name',
  'mother_place_of_birth',
  'mother_country_of_birth',
  'mother_nationality',
  'mother_prev_nationality',
  'spouse_name',
  'spouse_place_of_birth',
  'spouse_country_of_birth',
  'spouse_nationality',
  'spouse_prev_nationality',
  'grandparent_flag',

  // 6. Profession / Employment (7)
  'occupation',
  'empname',
  'empdesignation',
  'empaddress',
  'empphone',
  'previous_occupation',
  'prev_org',

  // 7. Visa Details (15)
  'duration',
  'visa_entry_id',
  'journeydate',
  'entrypoint',
  'exitpoint',
  'country_visited',
  'saarc_flag',
  'nameofsponsor_ind',
  'add1ofsponsor_ind',
  'add2ofsponsor_ind',
  'phoneofsponsor_ind',
  'nameofsponsor_msn',
  'add1ofsponsor_msn',
  'add2ofsponsor_msn',
  'phoneofsponsor_msn',

  // 8. Previous Visit / Visa (8)
  'old_visa_flag',
  'prv_visit_add1',
  'prv_visit_add2',
  'prv_visit_add3',
  'old_visa_no',
  'old_visa_type_id',
  'oldvisaissueplace',
  'oldvisaissuedate',

  // 9. Additional Questions (6)
  'question_1_flag',
  'question_2_flag',
  'question_3_flag',
  'question_4_flag',
  'question_5_flag',
  'question_6_flag',
]

export const WORKSPACE_HIDDEN_FIELDS: string[] = [
  'appl.changedSurnameCheck', // Personal Details conditional
  'state_name',               // Present Address legacy/combined field
  'appl.email_re',            // Present Address technical duplicate
  'appl.missioncode',         // Present Address / Registration technical field
  'perm_add3',                // Permanent Address legacy/combined field
  'grandparent_details',      // Family Details conditional (if grandparent_flag == 'Yes')
  'previous_organization',    // Profession / Military conditional
  'previous_designation',     // Profession / Military conditional
  'previous_rank',            // Profession / Military conditional
  'previous_posting',         // Profession / Military conditional
  'appl.journeydate',         // Visa Details technical duplicate
  'answer_1',                 // Additional Question 1 explanation
  'answer_2',                 // Additional Question 2 explanation
  'answer_3',                 // Additional Question 3 explanation
  'answer_4',                 // Additional Question 4 explanation
  'answer_5',                 // Additional Question 5 explanation
  'answer_6',                 // Additional Question 6 explanation
]

export const WORKSPACE_SECTIONS: WorkspaceSectionCardDef[] = [
  {
    id: 'personalDetails',
    title: '1. Personal Details',
    subtitle: 'Primary applicant identity, birth details, religion, and education',
    iconName: 'User',
    fieldKeys: [
      'appl.surname',
      'appl.applname',
      'appl.changedSurnameCheck',
      'appl.applsex',
      'appl.birthdate',
      'appl.placbrth',
      'appl.country_of_birth',
      'appl.nationality',
      'appl.nationality_by',
      'appl.nic_no',
      'appl.religion',
      'appl.visual_mark',
      'appl.edu_id',
      'marital_status',
    ],
  },
  {
    id: 'passportDetails',
    title: '2. Passport Details',
    subtitle: 'Passport number, validity, issue details, and secondary passports',
    iconName: 'BookOpen',
    fieldKeys: [
      'appl.passport_number',
      'appl.passport_issue_place',
      'appl.passport_issue_date',
      'appl.passport_expiry_date',
      'appl.oth_ppt',
      'appl.oth_pptno',
      'appl.oth_ppt_issue_place',
      'appl.prev_passport_country_issue',
      'appl.other_ppt_nationality',
    ],
  },
  {
    id: 'presentAddress',
    title: '3. Present Address & Contact',
    subtitle: 'Current domicile address, phone numbers, email, and Indian Mission',
    iconName: 'Home',
    manualNotices: [
      {
        title: 'CAPTCHA Security Verification',
        message: 'CAPTCHA must be solved manually on the Indian Visa website. Extension does not collect or solve CAPTCHA.',
      },
    ],
    fieldKeys: [
      'pres_addr1',
      'pres_addr2',
      'village_town_city',
      'district',
      'state_province',
      'present_country',
      'pincode',
      'pres_phone',
      'isd_code',
      'mobile',
      'appl.email',
      'state_name',
      'appl.email_re',
      'appl.missioncode',
    ],
  },
  {
    id: 'permanentAddress',
    title: '4. Permanent Address',
    subtitle: 'Permanent address in home country (matches present address if same)',
    iconName: 'MapPin',
    manualNotices: [
      {
        title: 'Same Address Checkbox',
        message: 'The Same Address checkbox is a dynamic portal control and remains manual on the Indian Visa website.',
      },
    ],
    fieldKeys: [
      'perm_add1',
      'perm_add2',
      'permanent_village_town_city',
      'permanent_district',
      'permanent_state_province',
      'permanent_country',
      'permanent_postal_code',
      'perm_add3',
    ],
  },
  {
    id: 'familyDetails',
    title: '5. Family Details',
    subtitle: 'Father, mother, spouse details, and Pakistan ancestry disclosure',
    iconName: 'Users',
    fieldKeys: [
      'fthrname',
      'father_place_of_birth',
      'father_country_of_birth',
      'father_nationality',
      'father_prev_nationality',
      'mother_name',
      'mother_place_of_birth',
      'mother_country_of_birth',
      'mother_nationality',
      'mother_prev_nationality',
      'spouse_name',
      'spouse_place_of_birth',
      'spouse_country_of_birth',
      'spouse_nationality',
      'spouse_prev_nationality',
      'grandparent_flag',
      'grandparent_details',
    ],
  },
  {
    id: 'professionEmployment',
    title: '6. Profession / Employment',
    subtitle: 'Present occupation, employer information, and military/security service',
    iconName: 'Briefcase',
    fieldKeys: [
      'occupation',
      'empname',
      'empdesignation',
      'empaddress',
      'empphone',
      'previous_occupation',
      'prev_org',
      'previous_organization',
      'previous_designation',
      'previous_rank',
      'previous_posting',
    ],
  },
  {
    id: 'visaDetails',
    title: '7. Visa Details & References',
    subtitle: 'Visa duration, port of arrival/exit, and Indian & Bangladesh references',
    iconName: 'Compass',
    fieldKeys: [
      'duration',
      'visa_entry_id',
      'journeydate',
      'appl.journeydate',
      'entrypoint',
      'exitpoint',
      'country_visited',
      'saarc_flag',
      'nameofsponsor_ind',
      'add1ofsponsor_ind',
      'add2ofsponsor_ind',
      'phoneofsponsor_ind',
      'nameofsponsor_msn',
      'add1ofsponsor_msn',
      'add2ofsponsor_msn',
      'phoneofsponsor_msn',
    ],
  },
  {
    id: 'previousVisitVisa',
    title: '8. Previous Visit / Visa',
    subtitle: 'Prior Indian visas, stay addresses, and previously visited cities',
    iconName: 'History',
    manualNotices: [
      {
        title: 'Visa Refusal Disclosures',
        message: 'Visa refusal questions are sensitive legal disclosures and must be answered manually on the website.',
      },
    ],
    fieldKeys: [
      'old_visa_flag',
      'prv_visit_add1',
      'prv_visit_add2',
      'prv_visit_add3',
      'old_visa_no',
      'old_visa_type_id',
      'oldvisaissueplace',
      'oldvisaissuedate',
    ],
  },
  {
    id: 'additionalQuestions',
    title: '9. Additional Questions',
    subtitle: 'Legal and security questionnaire (Questions 1 to 6)',
    iconName: 'ShieldAlert',
    manualNotices: [
      {
        title: 'Applicant Declaration',
        message: 'The final declaration checkbox is a legal acknowledgement and must be confirmed manually by the applicant on the Indian Visa website.',
      },
    ],
    fieldKeys: [
      'question_1_flag',
      'answer_1',
      'question_2_flag',
      'answer_2',
      'question_3_flag',
      'answer_3',
      'question_4_flag',
      'answer_4',
      'question_5_flag',
      'answer_5',
      'question_6_flag',
      'answer_6',
    ],
  },
  {
    id: 'photoUpload',
    title: '10. Photo Section',
    subtitle: 'Applicant photograph management and preview',
    iconName: 'Camera',
    manualNotices: [
      {
        title: 'Portal Photo Chooser',
        message: 'On the Indian Visa website, photograph file selection remains manual. Extension manages the photo here in your workspace for verification and preview.',
      },
    ],
    fieldKeys: [],
  },
]

export const BANGLADESH_APPLICATION_SCHEMA: ApplicationSectionDef[] = [
  {
    id: 'registration',
    title: '1. Registration',
    subtitle: 'Initial application configuration and portal registration fields',
    iconName: 'FileText',
    manualNotices: [
      {
        title: 'CAPTCHA Security Verification',
        message: 'CAPTCHA must be solved manually on the Indian Visa website. Extension does not collect or solve CAPTCHA.',
      },
    ],
    fields: [
      {
        key: 'appl.countryname',
        label: 'Country / Region applying visa from',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.countryname',
        sourceApplicantPath: 'presentAddress.country',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.missioncode',
        label: 'Indian Mission / Office',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.missioncode',
        sourceApplicantPath: 'registration.indianMission',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH-DHAKA', label: 'BANGLADESH - DHAKA' },
          { value: 'BANGLADESH-CHITTAGONG', label: 'BANGLADESH - CHITTAGONG' },
          { value: 'BANGLADESH-RAJSHAHI', label: 'BANGLADESH - RAJSHAHI' },
          { value: 'BANGLADESH-SYLHET', label: 'BANGLADESH - SYLHET' },
          { value: 'BANGLADESH-KHULNA', label: 'BANGLADESH - KHULNA' },
        ],
        visibleByDefault: false,
      },
      {
        key: 'appl.nationality',
        label: 'Nationality / Region',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.nationality',
        sourceApplicantPath: 'personalInfo.nationality',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
          { value: 'NEPAL', label: 'NEPAL' },
          { value: 'SRI LANKA', label: 'SRI LANKA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.birthdate',
        label: 'Date of Birth (DD/MM/YYYY)',
        section: 'registration',
        inputType: 'date',
        targetMappingField: 'appl.birthdate',
        sourceApplicantPath: 'personalInfo.dateOfBirth',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: true,
      },
      {
        key: 'appl.email',
        label: 'Email ID',
        section: 'registration',
        inputType: 'text',
        targetMappingField: 'appl.email',
        sourceApplicantPath: 'contact.email',
        requiredInPortal: true,
        placeholder: 'applicant@example.com',
        visibleByDefault: true,
      },
      {
        key: 'appl.email_re',
        label: 'Re-enter Email ID',
        section: 'registration',
        inputType: 'text',
        targetMappingField: 'appl.email_re',
        sourceApplicantPath: 'contact.email',
        requiredInPortal: true,
        placeholder: 'applicant@example.com',
        visibleByDefault: false,
      },
      {
        key: 'appl.journeydate',
        label: 'Expected Date of Arrival (DD/MM/YYYY)',
        section: 'registration',
        inputType: 'date',
        targetMappingField: 'appl.journeydate',
        sourceApplicantPath: 'travel.intendedArrivalDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: false,
      },
    ],
  },
  {
    id: 'basicDetails',
    title: '2. Basic Details',
    subtitle: 'Personal identity and passport information',
    iconName: 'User',
    fields: [
      {
        key: 'appl.surname',
        label: 'Surname',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.surname',
        sourceApplicantPath: 'personalInfo.surname',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.applname',
        label: 'Given Name(s)',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.applname',
        sourceApplicantPath: 'personalInfo.givenNames',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.changedSurnameCheck',
        label: 'Have you ever changed your name?',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'checkbox',
        targetMappingField: 'appl.changedSurnameCheck',
        sourceApplicantPath: 'personalInfo.hasChangedName',
        visibleByDefault: false,
      },
      {
        key: 'appl.applsex',
        label: 'Gender',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.applsex',
        sourceApplicantPath: 'personalInfo.gender',
        requiredInPortal: true,
        options: [
          { value: 'MALE', label: 'MALE' },
          { value: 'FEMALE', label: 'FEMALE' },
          { value: 'TRANSGENDER', label: 'TRANSGENDER' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.placbrth',
        label: 'Town / City of Birth',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.placbrth',
        sourceApplicantPath: 'personalInfo.townCityOfBirth',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.country_of_birth',
        label: 'Country of Birth',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.country_of_birth',
        sourceApplicantPath: 'personalInfo.countryOfBirth',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.nic_no',
        label: 'National ID / NIC Number',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.nic_no',
        sourceApplicantPath: 'personalInfo.nationalIdNumber',
        visibleByDefault: true,
      },
      {
        key: 'appl.religion',
        label: 'Religion',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.religion',
        sourceApplicantPath: 'personalInfo.religion',
        requiredInPortal: true,
        options: [
          { value: 'ISLAM', label: 'ISLAM' },
          { value: 'HINDU', label: 'HINDU' },
          { value: 'BUDDHISM', label: 'BUDDHISM' },
          { value: 'CHRISTIAN', label: 'CHRISTIAN' },
          { value: 'SIKH', label: 'SIKH' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.visual_mark',
        label: 'Visible Identification Marks',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.visual_mark',
        sourceApplicantPath: 'personalInfo.visibleIdentificationMarks',
        visibleByDefault: true,
      },
      {
        key: 'appl.edu_id',
        label: 'Educational Qualification',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.edu_id',
        sourceApplicantPath: 'personalInfo.educationalQualification',
        requiredInPortal: true,
        options: [
          { value: 'GRADUATE', label: 'GRADUATE' },
          { value: 'POST GRADUATE', label: 'POST GRADUATE' },
          { value: 'HIGHER SECONDARY', label: 'HIGHER SECONDARY' },
          { value: 'MATRICULATION', label: 'MATRICULATION' },
          { value: 'BELOW MATRICULATION', label: 'BELOW MATRICULATION' },
          { value: 'PROFESSIONAL', label: 'PROFESSIONAL' },
          { value: 'ILLITERATE', label: 'ILLITERATE' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.nationality_by',
        label: 'Nationality Acquired By',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.nationality_by',
        sourceApplicantPath: 'personalInfo.nationalityAcquiredBy',
        requiredInPortal: true,
        options: [
          { value: 'Birth', label: 'By Birth' },
          { value: 'Naturalization', label: 'By Naturalization' },
        ],
        visibleByDefault: true,
      },

      // Passport Sub-section
      {
        key: 'appl.passport_number',
        label: 'Passport Number',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.passport_number',
        sourceApplicantPath: 'passport.passportNumber',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.passport_issue_place',
        label: 'Place of Issue',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.passport_issue_place',
        sourceApplicantPath: 'passport.placeOfIssue',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.passport_issue_date',
        label: 'Passport Issue Date (DD/MM/YYYY)',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'date',
        targetMappingField: 'appl.passport_issue_date',
        sourceApplicantPath: 'passport.issueDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: true,
      },
      {
        key: 'appl.passport_expiry_date',
        label: 'Passport Expiry Date (DD/MM/YYYY)',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'date',
        targetMappingField: 'appl.passport_expiry_date',
        sourceApplicantPath: 'passport.expiryDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: true,
      },
      {
        key: 'appl.oth_ppt',
        label: 'Do you hold any other valid passport/identity certificate?',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'radio',
        targetMappingField: 'appl.oth_ppt',
        sourceApplicantPath: 'passport.holdsOtherPassport',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.oth_pptno',
        label: 'Other Passport / IC Number',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.oth_pptno',
        sourceApplicantPath: 'passport.otherPassportDetails.passportNumber',
        visibleByDefault: true,
      },
      {
        key: 'appl.oth_ppt_issue_place',
        label: 'Other Passport Place of Issue',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.oth_ppt_issue_place',
        sourceApplicantPath: 'passport.otherPassportDetails.placeOfIssue',
        visibleByDefault: true,
      },
      {
        key: 'appl.prev_passport_country_issue',
        label: 'Other Passport Country of Issue',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'select',
        targetMappingField: 'appl.prev_passport_country_issue',
        sourceApplicantPath: 'passport.otherPassportDetails.countryOfIssue',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'appl.other_ppt_nationality',
        label: 'Other Passport Nationality',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'select',
        targetMappingField: 'appl.other_ppt_nationality',
        sourceApplicantPath: 'passport.otherPassportDetails.nationalityInPassport',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
        visibleByDefault: true,
      },
    ],
  },
  {
    id: 'familyDetails',
    title: '3. Family Details',
    subtitle: 'Applicant address, family members, and employment information',
    iconName: 'Users',
    manualNotices: [
      {
        title: 'Same Address Checkbox',
        message: 'The Same Address checkbox is a dynamic portal control and remains manual on the Indian Visa website.',
      },
    ],
    fields: [
      // Present Address
      {
        key: 'pres_addr1',
        label: 'Present Address Line 1 (House No / Street)',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_addr1',
        sourceApplicantPath: 'presentAddress.addressLine1',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'pres_addr2',
        label: 'Present Address Line 2',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_addr2',
        sourceApplicantPath: 'presentAddress.addressLine2',
        visibleByDefault: true,
      },
      {
        key: 'village_town_city',
        label: 'Village / Town / City',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'village_town_city',
        sourceApplicantPath: 'presentAddress.villageTownCity',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'district',
        label: 'District',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'district',
        sourceApplicantPath: 'presentAddress.district',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'state_province',
        label: 'State / Province / District',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'state_name',
        sourceApplicantPath: 'presentAddress.stateProvince',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'present_country',
        label: 'Country',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'select',
        targetMappingField: 'appl.countryname',
        sourceApplicantPath: 'presentAddress.country',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'pincode',
        label: 'Postal / Pincode',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pincode',
        sourceApplicantPath: 'presentAddress.postalCode',
        visibleByDefault: true,
      },
      {
        key: 'pres_phone',
        label: 'Phone Number',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_phone',
        sourceApplicantPath: 'presentAddress.phone',
        visibleByDefault: true,
      },
      {
        key: 'isd_code',
        label: 'ISD Code',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'isd_code',
        sourceApplicantPath: 'contact.isdCode',
        placeholder: 'e.g. 880',
        visibleByDefault: true,
      },
      {
        key: 'mobile',
        label: 'Mobile Number',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'mobile',
        sourceApplicantPath: 'contact.mobile',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'appl.email',
        label: 'Email ID',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'appl.email',
        sourceApplicantPath: 'contact.email',
        visibleByDefault: true,
      },
      {
        key: 'state_name',
        label: 'State / Province / District (Portal State Name)',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'state_name',
        sourceApplicantPath: 'presentAddress.stateProvince',
        visibleByDefault: false,
      },
      {
        key: 'appl.email_re',
        label: 'Retype Email ID',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'appl.email_re',
        sourceApplicantPath: 'contact.email',
        visibleByDefault: false,
      },
      {
        key: 'appl.missioncode',
        label: 'Indian Mission / Office',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'appl.missioncode',
        sourceApplicantPath: 'registration.indianMission',
        visibleByDefault: false,
      },

      // Permanent Address
      {
        key: 'perm_add1',
        label: 'Permanent Address Line 1',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add1',
        sourceApplicantPath: 'permanentAddress.addressLine1',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'perm_add2',
        label: 'Permanent Address Line 2',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add2',
        sourceApplicantPath: 'permanentAddress.addressLine2',
        visibleByDefault: true,
      },
      {
        key: 'permanent_village_town_city',
        label: 'Permanent Village / Town / City',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'permanent_village_town_city',
        sourceApplicantPath: 'permanentAddress.villageTownCity',
        visibleByDefault: true,
      },
      {
        key: 'permanent_district',
        label: 'Permanent District',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'permanent_district',
        sourceApplicantPath: 'permanentAddress.district',
        visibleByDefault: true,
      },
      {
        key: 'permanent_state_province',
        label: 'Permanent State / Province',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'permanent_state_province',
        sourceApplicantPath: 'permanentAddress.stateProvince',
        visibleByDefault: true,
      },
      {
        key: 'permanent_country',
        label: 'Permanent Country',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'select',
        targetMappingField: 'permanent_country',
        sourceApplicantPath: 'permanentAddress.country',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'permanent_postal_code',
        label: 'Permanent Postal / Pincode',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'permanent_postal_code',
        sourceApplicantPath: 'permanentAddress.postalCode',
        visibleByDefault: true,
      },
      {
        key: 'perm_add3',
        label: 'Permanent Village / Town / City / State (Combined)',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add3',
        sourceApplicantPath: 'permanentAddress.stateProvince',
        visibleByDefault: false,
      },

      // Father Details
      {
        key: 'fthrname',
        label: "Father's Full Name",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'text',
        targetMappingField: 'fthrname',
        sourceApplicantPath: 'family.father.name',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'father_place_of_birth',
        label: "Father's Place of Birth",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'text',
        targetMappingField: 'father_place_of_birth',
        sourceApplicantPath: 'family.father.placeOfBirth',
        visibleByDefault: true,
      },
      {
        key: 'father_country_of_birth',
        label: "Father's Country of Birth",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_country_of_birth',
        sourceApplicantPath: 'family.father.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'father_nationality',
        label: "Father's Nationality",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_nationality',
        sourceApplicantPath: 'family.father.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'father_prev_nationality',
        label: "Father's Previous Nationality",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_prev_nationality',
        sourceApplicantPath: 'family.father.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },

      // Mother Details
      {
        key: 'mother_name',
        label: "Mother's Full Name",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'text',
        targetMappingField: 'mother_name',
        sourceApplicantPath: 'family.mother.name',
        requiredInPortal: true,
        visibleByDefault: true,
      },
      {
        key: 'mother_place_of_birth',
        label: "Mother's Place of Birth",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'text',
        targetMappingField: 'mother_place_of_birth',
        sourceApplicantPath: 'family.mother.placeOfBirth',
        visibleByDefault: true,
      },
      {
        key: 'mother_country_of_birth',
        label: "Mother's Country of Birth",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_country_of_birth',
        sourceApplicantPath: 'family.mother.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'mother_nationality',
        label: "Mother's Nationality",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_nationality',
        sourceApplicantPath: 'family.mother.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'mother_prev_nationality',
        label: "Mother's Previous Nationality",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_prev_nationality',
        sourceApplicantPath: 'family.mother.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },

      // Marital & Spouse
      {
        key: 'marital_status',
        label: 'Marital Status',
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'marital_status',
        sourceApplicantPath: 'personalInfo.maritalStatus',
        options: [
          { value: 'Married', label: 'Married' },
          { value: 'Single', label: 'Single / Unmarried' },
          { value: 'Divorced', label: 'Divorced' },
          { value: 'Widow/Widower', label: 'Widow/Widower' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'spouse_name',
        label: "Spouse's Full Name",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'text',
        targetMappingField: 'spouse_name',
        sourceApplicantPath: 'family.spouse.name',
        visibleByDefault: true,
      },
      {
        key: 'spouse_place_of_birth',
        label: "Spouse's Place of Birth",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'text',
        targetMappingField: 'spouse_place_of_birth',
        sourceApplicantPath: 'family.spouse.placeOfBirth',
        visibleByDefault: true,
      },
      {
        key: 'spouse_country_of_birth',
        label: "Spouse's Country of Birth",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_country_of_birth',
        sourceApplicantPath: 'family.spouse.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'spouse_nationality',
        label: "Spouse's Nationality",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_nationality',
        sourceApplicantPath: 'family.spouse.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'spouse_prev_nationality',
        label: "Spouse's Previous Nationality",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_prev_nationality',
        sourceApplicantPath: 'family.spouse.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
        visibleByDefault: true,
      },

      // Grandparents / Pakistan Relation
      {
        key: 'grandparent_flag',
        label: 'Were your Grandfather/Grandmother Pakistan nationals or belong to Pakistan held area?',
        section: 'familyDetails',
        subsection: 'Origin Details',
        inputType: 'radio',
        targetMappingField: 'grandparent_flag',
        sourceApplicantPath: 'family.hasPakistanRelation',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'grandparent_details',
        label: 'If yes, give details',
        section: 'familyDetails',
        subsection: 'Origin Details',
        inputType: 'textarea',
        targetMappingField: 'grandparent_details',
        sourceApplicantPath: 'family.pakistanRelationDetails',
        visibleByDefault: false,
      },

      // Employment
      {
        key: 'occupation',
        label: 'Present Occupation',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'select',
        targetMappingField: 'occupation',
        sourceApplicantPath: 'employment.presentOccupation',
        requiredInPortal: true,
        options: [
          { value: 'BUSINESS PERSON', label: 'BUSINESS PERSON' },
          { value: 'PRIVATE SERVICE', label: 'PRIVATE SERVICE' },
          { value: 'GOVT SERVICE', label: 'GOVERNMENT SERVICE' },
          { value: 'HOUSEWIFE', label: 'HOUSEWIFE' },
          { value: 'STUDENT', label: 'STUDENT' },
          { value: 'RETIRED', label: 'RETIRED' },
          { value: 'TEACHER', label: 'TEACHER' },
          { value: 'DOCTOR', label: 'DOCTOR' },
          { value: 'ENGINEER', label: 'ENGINEER' },
          { value: 'ADVOCATE', label: 'ADVOCATE / LAWYER' },
          { value: 'JOURNALIST', label: 'JOURNALIST' },
          { value: 'FARMER', label: 'FARMER' },
          { value: 'AGRICULTURE', label: 'AGRICULTURE' },
          { value: 'UN-EMPLOYED', label: 'UN-EMPLOYED' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'empname',
        label: 'Employer / Business Name',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empname',
        sourceApplicantPath: 'employment.employerName',
        visibleByDefault: true,
      },
      {
        key: 'empdesignation',
        label: 'Designation / Rank',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empdesignation',
        sourceApplicantPath: 'employment.designationRank',
        visibleByDefault: true,
      },
      {
        key: 'empaddress',
        label: 'Employer Address',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empaddress',
        sourceApplicantPath: 'employment.employerAddress',
        visibleByDefault: true,
      },
      {
        key: 'empphone',
        label: 'Employer Phone Number',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empphone',
        sourceApplicantPath: 'employment.employerPhone',
        visibleByDefault: true,
      },
      {
        key: 'previous_occupation',
        label: 'Past / Previous Occupation (if any)',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'select',
        targetMappingField: 'previous_occupation',
        sourceApplicantPath: 'employment.pastOccupation',
        options: [
          { value: 'NONE', label: 'NONE' },
          { value: 'BUSINESS PERSON', label: 'BUSINESS PERSON' },
          { value: 'PRIVATE SERVICE', label: 'PRIVATE SERVICE' },
          { value: 'GOVT SERVICE', label: 'GOVERNMENT SERVICE' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'prev_org',
        label: 'Are you in/have you served in Military/Semi-Military/Police/Security Organization?',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'radio',
        targetMappingField: 'prev_org',
        sourceApplicantPath: 'employment.hasMilitaryService',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'previous_organization',
        label: 'Organization Name',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_organization',
        sourceApplicantPath: 'employment.militaryOrganization',
        visibleByDefault: false,
      },
      {
        key: 'previous_designation',
        label: 'Designation',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_designation',
        sourceApplicantPath: 'employment.militaryDesignation',
        visibleByDefault: false,
      },
      {
        key: 'previous_rank',
        label: 'Rank',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_rank',
        sourceApplicantPath: 'employment.militaryRank',
        visibleByDefault: false,
      },
      {
        key: 'previous_posting',
        label: 'Place of Posting',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_posting',
        sourceApplicantPath: 'employment.militaryPlaceOfPosting',
        visibleByDefault: false,
      },
    ],
  },
  {
    id: 'visaDetails',
    title: '4. Visa Details',
    subtitle: 'Visa duration, travel history, old visas, and reference information',
    iconName: 'Compass',
    manualNotices: [
      {
        title: 'Visa Refusal Disclosures',
        message: 'Visa refusal questions are sensitive legal disclosures and must be answered manually on the website.',
      },
    ],
    fields: [
      {
        key: 'duration',
        label: 'Duration of Visa (in Months)',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'text',
        targetMappingField: 'duration',
        sourceApplicantPath: 'travel.duration',
        placeholder: 'e.g. 12 or 6',
        visibleByDefault: true,
      },
      {
        key: 'visa_entry_id',
        label: 'Number of Entries',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'visa_entry_id',
        sourceApplicantPath: 'travel.visaEntryType',
        options: [
          { value: 'Multiple', label: 'Multiple Entry' },
          { value: 'Double', label: 'Double Entry' },
          { value: 'Triple', label: 'Triple Entry' },
          { value: 'Single', label: 'Single Entry' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'journeydate',
        label: 'Expected Date of Journey (DD/MM/YYYY)',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'date',
        targetMappingField: 'journeydate',
        sourceApplicantPath: 'travel.intendedArrivalDate',
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: true,
      },
      {
        key: 'entrypoint',
        label: 'Port of Arrival in India',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'entrypoint',
        sourceApplicantPath: 'travel.entryPoint',
        options: [
          { value: 'BY ROAD PHULBARI', label: 'BY ROAD PHULBARI' },
          { value: 'HARIDASPUR RAIL', label: 'HARIDASPUR RAIL' },
          { value: 'HARIDASPUR ROAD', label: 'HARIDASPUR ROAD (BENAPOLE)' },
          { value: 'CHANGRIBANDHA ROAD', label: 'CHANGRIBANDHA ROAD' },
          { value: 'DAWKI ROAD', label: 'DAWKI ROAD' },
          { value: 'GELEPHU ROAD', label: 'GELEPHU ROAD' },
          { value: 'HILI ROAD', label: 'HILI ROAD' },
          { value: 'KOLKATA AIRPORT', label: 'KOLKATA AIRPORT' },
          { value: 'DELHI AIRPORT', label: 'DELHI AIRPORT' },
          { value: 'CHENNAI AIRPORT', label: 'CHENNAI AIRPORT' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'exitpoint',
        label: 'Expected Port of Exit from India',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'exitpoint',
        sourceApplicantPath: 'travel.exitPoint',
        options: [
          { value: 'BY ROAD PHULBARI', label: 'BY ROAD PHULBARI' },
          { value: 'HARIDASPUR RAIL', label: 'HARIDASPUR RAIL' },
          { value: 'HARIDASPUR ROAD', label: 'HARIDASPUR ROAD (BENAPOLE)' },
          { value: 'CHANGRIBANDHA ROAD', label: 'CHANGRIBANDHA ROAD' },
          { value: 'DAWKI ROAD', label: 'DAWKI ROAD' },
          { value: 'KOLKATA AIRPORT', label: 'KOLKATA AIRPORT' },
          { value: 'DELHI AIRPORT', label: 'DELHI AIRPORT' },
        ],
        visibleByDefault: true,
      },

      // Previous Indian Visa
      {
        key: 'old_visa_flag',
        label: 'Have you visited India previously?',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'radio',
        targetMappingField: 'old_visa_flag',
        sourceApplicantPath: 'previousVisa.hasPreviousVisa',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'prv_visit_add1',
        label: 'Address stayed during previous visit (Line 1)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add1',
        sourceApplicantPath: 'previousVisa.visitedAddress1',
        visibleByDefault: true,
      },
      {
        key: 'prv_visit_add2',
        label: 'Address stayed during previous visit (Line 2)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add2',
        sourceApplicantPath: 'previousVisa.visitedAddress2',
        visibleByDefault: true,
      },
      {
        key: 'prv_visit_add3',
        label: 'Cities previously visited in India',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add3',
        sourceApplicantPath: 'previousVisa.visitedAddress3',
        visibleByDefault: true,
      },
      {
        key: 'old_visa_no',
        label: 'Previous Visa Number',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'old_visa_no',
        sourceApplicantPath: 'previousVisa.visaNumber',
        visibleByDefault: true,
      },
      {
        key: 'old_visa_type_id',
        label: 'Previous Visa Type',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'select',
        targetMappingField: 'old_visa_type_id',
        sourceApplicantPath: 'previousVisa.visaType',
        options: [
          { value: 'TOURIST VISA', label: 'TOURIST VISA' },
          { value: 'MEDICAL VISA', label: 'MEDICAL VISA' },
          { value: 'BUSINESS VISA', label: 'BUSINESS VISA' },
          { value: 'ENTRY VISA', label: 'ENTRY VISA' },
          { value: 'STUDENT VISA', label: 'STUDENT VISA' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'oldvisaissueplace',
        label: 'Previous Visa Place of Issue',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'oldvisaissueplace',
        sourceApplicantPath: 'previousVisa.placeOfIssue',
        visibleByDefault: true,
      },
      {
        key: 'oldvisaissuedate',
        label: 'Previous Visa Issue Date (DD/MM/YYYY)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'date',
        targetMappingField: 'oldvisaissuedate',
        sourceApplicantPath: 'previousVisa.dateOfIssue',
        placeholder: 'DD/MM/YYYY',
        visibleByDefault: true,
      },

      // Travel history
      {
        key: 'country_visited',
        label: 'Countries Visited in the Last 10 Years',
        section: 'visaDetails',
        subsection: 'Travel History',
        inputType: 'text',
        targetMappingField: 'country_visited',
        sourceApplicantPath: 'travel.countriesVisited',
        placeholder: 'e.g. INDIA, MALAYSIA, THAILAND',
        visibleByDefault: true,
      },
      {
        key: 'saarc_flag',
        label: 'Have you visited SAARC countries during the last 3 years?',
        section: 'visaDetails',
        subsection: 'Travel History',
        inputType: 'radio',
        targetMappingField: 'saarc_flag',
        sourceApplicantPath: 'travel.visitedSaarc',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },

      // References
      {
        key: 'nameofsponsor_ind',
        label: 'Reference Name in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'nameofsponsor_ind',
        sourceApplicantPath: 'reference.name',
        visibleByDefault: true,
      },
      {
        key: 'add1ofsponsor_ind',
        label: 'Address Line 1 in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'add1ofsponsor_ind',
        sourceApplicantPath: 'reference.addressLine1',
        visibleByDefault: true,
      },
      {
        key: 'add2ofsponsor_ind',
        label: 'Address Line 2 in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'add2ofsponsor_ind',
        sourceApplicantPath: 'reference.addressLine2',
        visibleByDefault: true,
      },
      {
        key: 'phoneofsponsor_ind',
        label: 'Phone Number in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'phoneofsponsor_ind',
        sourceApplicantPath: 'reference.phone',
        visibleByDefault: true,
      },
      {
        key: 'nameofsponsor_msn',
        label: 'Reference Name in Bangladesh / Home Country',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'nameofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.name',
        visibleByDefault: true,
      },
      {
        key: 'add1ofsponsor_msn',
        label: 'Address Line 1 in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'add1ofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.addressLine1',
        visibleByDefault: true,
      },
      {
        key: 'add2ofsponsor_msn',
        label: 'Address Line 2 in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'add2ofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.addressLine2',
        visibleByDefault: true,
      },
      {
        key: 'phoneofsponsor_msn',
        label: 'Phone Number in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'phoneofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.phone',
        visibleByDefault: true,
      },
    ],
  },
  {
    id: 'additionalQuestions',
    title: '5. Additional Questions',
    subtitle: '6 legal/security question groups and applicant declaration',
    iconName: 'ShieldAlert',
    manualNotices: [
      {
        title: 'Applicant Declaration',
        message: 'The final declaration checkbox is a legal acknowledgement and must be confirmed manually by the applicant on the Indian Visa website.',
      },
    ],
    fields: [
      {
        key: 'question_1_flag',
        label: '1. Have you ever been arrested/prosecuted/convicted by Court of Law?',
        section: 'additionalQuestions',
        subsection: 'Question 1',
        inputType: 'radio',
        targetMappingField: 'question_1_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_1',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 1',
        inputType: 'textarea',
        targetMappingField: 'answer_1',
        visibleByDefault: false,
      },
      {
        key: 'question_2_flag',
        label: '2. Have you ever been refused entry / deported by any country including India?',
        section: 'additionalQuestions',
        subsection: 'Question 2',
        inputType: 'radio',
        targetMappingField: 'question_2_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_2',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 2',
        inputType: 'textarea',
        targetMappingField: 'answer_2',
        visibleByDefault: false,
      },
      {
        key: 'question_3_flag',
        label: '3. Have you ever been engaged in human trafficking / drug trafficking / financial fraud / crimes against humanity?',
        section: 'additionalQuestions',
        subsection: 'Question 3',
        inputType: 'radio',
        targetMappingField: 'question_3_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_3',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 3',
        inputType: 'textarea',
        targetMappingField: 'answer_3',
        visibleByDefault: false,
      },
      {
        key: 'question_4_flag',
        label: '4. Have you ever been involved in cyber crime / terrorist activities / sabotage / espionage?',
        section: 'additionalQuestions',
        subsection: 'Question 4',
        inputType: 'radio',
        targetMappingField: 'question_4_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_4',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 4',
        inputType: 'textarea',
        targetMappingField: 'answer_4',
        visibleByDefault: false,
      },
      {
        key: 'question_5_flag',
        label: '5. Have you ever by any means expressed views that justify or glorify terrorist violence?',
        section: 'additionalQuestions',
        subsection: 'Question 5',
        inputType: 'radio',
        targetMappingField: 'question_5_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_5',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 5',
        inputType: 'textarea',
        targetMappingField: 'answer_5',
        visibleByDefault: false,
      },
      {
        key: 'question_6_flag',
        label: '6. Have you sought asylum or refuge in any country?',
        section: 'additionalQuestions',
        subsection: 'Question 6',
        inputType: 'radio',
        targetMappingField: 'question_6_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
        visibleByDefault: true,
      },
      {
        key: 'answer_6',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 6',
        inputType: 'textarea',
        targetMappingField: 'answer_6',
        visibleByDefault: false,
      },
    ],
  },
  {
    id: 'photoUpload',
    title: '6. Photo Section',
    subtitle: 'Applicant photograph management',
    iconName: 'Camera',
    manualNotices: [
      {
        title: 'Portal Photo Chooser',
        message: 'On the Indian Visa website, photograph file selection remains manual. Extension manages the photo here in your workspace for verification and preview.',
      },
    ],
    fields: [],
  },
]

export function getAllSchemaFields(): ApplicationFieldDef[] {
  return BANGLADESH_APPLICATION_SCHEMA.flatMap((s) => s.fields)
}

export function getDefaultVisibleSchemaFields(): ApplicationFieldDef[] {
  return getAllSchemaFields().filter((f) => f.visibleByDefault !== false)
}

export function getDefaultHiddenSchemaFields(): ApplicationFieldDef[] {
  return getAllSchemaFields().filter((f) => f.visibleByDefault === false)
}

export function getWorkspaceSections(): WorkspaceSectionCardDef[] {
  return WORKSPACE_SECTIONS
}
