export interface ApplicationFieldDef {
  key: string
  label: string
  section: 'registration' | 'basicDetails' | 'familyDetails' | 'visaDetails' | 'additionalQuestions' | 'photoUpload'
  subsection?: string
  inputType: 'text' | 'select' | 'date' | 'radio' | 'checkbox' | 'textarea'
  options?: { value: string; label: string }[]
  targetMappingField: string
  sourceApplicantPath?: string
  requiredInPortal?: boolean
  description?: string
  manualNotice?: string
  placeholder?: string
}

export interface ApplicationSectionDef {
  id: 'registration' | 'basicDetails' | 'familyDetails' | 'visaDetails' | 'additionalQuestions' | 'photoUpload'
  title: string
  subtitle: string
  iconName: string
  fields: ApplicationFieldDef[]
  manualNotices?: { title: string; message: string }[]
}

export const BANGLADESH_APPLICATION_SCHEMA: ApplicationSectionDef[] = [
  {
    id: 'registration',
    title: '1. Registration',
    subtitle: 'Initial application configuration and portal registration fields',
    iconName: 'FileText',
    manualNotices: [
      {
        title: 'CAPTCHA Security Verification',
        message: 'CAPTCHA must be solved manually on the Indian Visa website. Extension does not collect or solve CAPTCHA.',
      },
    ],
    fields: [
      {
        key: 'appl.countryname',
        label: 'Country / Region applying visa from',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.countryname',
        sourceApplicantPath: 'presentAddress.country',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
      },
      {
        key: 'appl.missioncode',
        label: 'Indian Mission / Office',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.missioncode',
        sourceApplicantPath: 'registration.indianMission',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH-DHAKA', label: 'BANGLADESH - DHAKA' },
          { value: 'BANGLADESH-CHITTAGONG', label: 'BANGLADESH - CHITTAGONG' },
          { value: 'BANGLADESH-RAJSHAHI', label: 'BANGLADESH - RAJSHAHI' },
          { value: 'BANGLADESH-SYLHET', label: 'BANGLADESH - SYLHET' },
          { value: 'BANGLADESH-KHULNA', label: 'BANGLADESH - KHULNA' },
        ],
      },
      {
        key: 'appl.nationality',
        label: 'Nationality / Region',
        section: 'registration',
        inputType: 'select',
        targetMappingField: 'appl.nationality',
        sourceApplicantPath: 'personalInfo.nationality',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
          { value: 'NEPAL', label: 'NEPAL' },
          { value: 'SRI LANKA', label: 'SRI LANKA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
        ],
      },
      {
        key: 'appl.birthdate',
        label: 'Date of Birth (DD/MM/YYYY)',
        section: 'registration',
        inputType: 'date',
        targetMappingField: 'appl.birthdate',
        sourceApplicantPath: 'personalInfo.dateOfBirth',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
      },
      {
        key: 'appl.email',
        label: 'Email ID',
        section: 'registration',
        inputType: 'text',
        targetMappingField: 'appl.email',
        sourceApplicantPath: 'contact.email',
        requiredInPortal: true,
        placeholder: 'applicant@example.com',
      },
      {
        key: 'appl.email_re',
        label: 'Re-enter Email ID',
        section: 'registration',
        inputType: 'text',
        targetMappingField: 'appl.email_re',
        sourceApplicantPath: 'contact.email',
        requiredInPortal: true,
        placeholder: 'applicant@example.com',
      },
      {
        key: 'appl.journeydate',
        label: 'Expected Date of Arrival (DD/MM/YYYY)',
        section: 'registration',
        inputType: 'date',
        targetMappingField: 'appl.journeydate',
        sourceApplicantPath: 'travel.intendedArrivalDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
      },
    ],
  },
  {
    id: 'basicDetails',
    title: '2. Basic Details',
    subtitle: 'Personal identity and passport information',
    iconName: 'User',
    fields: [
      {
        key: 'appl.surname',
        label: 'Surname',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.surname',
        sourceApplicantPath: 'personalInfo.surname',
        requiredInPortal: true,
      },
      {
        key: 'appl.applname',
        label: 'Given Name(s)',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.applname',
        sourceApplicantPath: 'personalInfo.givenNames',
        requiredInPortal: true,
      },
      {
        key: 'appl.changedSurnameCheck',
        label: 'Have you ever changed your name?',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'checkbox',
        targetMappingField: 'appl.changedSurnameCheck',
        sourceApplicantPath: 'personalInfo.hasChangedName',
      },
      {
        key: 'appl.applsex',
        label: 'Gender',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.applsex',
        sourceApplicantPath: 'personalInfo.gender',
        requiredInPortal: true,
        options: [
          { value: 'MALE', label: 'MALE' },
          { value: 'FEMALE', label: 'FEMALE' },
          { value: 'TRANSGENDER', label: 'TRANSGENDER' },
        ],
      },
      {
        key: 'appl.placbrth',
        label: 'Town / City of Birth',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.placbrth',
        sourceApplicantPath: 'personalInfo.townCityOfBirth',
        requiredInPortal: true,
      },
      {
        key: 'appl.country_of_birth',
        label: 'Country of Birth',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.country_of_birth',
        sourceApplicantPath: 'personalInfo.countryOfBirth',
        requiredInPortal: true,
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'appl.nic_no',
        label: 'National ID / NIC Number',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.nic_no',
        sourceApplicantPath: 'personalInfo.nationalIdNumber',
      },
      {
        key: 'appl.religion',
        label: 'Religion',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.religion',
        sourceApplicantPath: 'personalInfo.religion',
        requiredInPortal: true,
        options: [
          { value: 'ISLAM', label: 'ISLAM' },
          { value: 'HINDU', label: 'HINDU' },
          { value: 'BUDDHISM', label: 'BUDDHISM' },
          { value: 'CHRISTIAN', label: 'CHRISTIAN' },
          { value: 'SIKH', label: 'SIKH' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
      },
      {
        key: 'appl.visual_mark',
        label: 'Visible Identification Marks',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'text',
        targetMappingField: 'appl.visual_mark',
        sourceApplicantPath: 'personalInfo.visibleIdentificationMarks',
      },
      {
        key: 'appl.edu_id',
        label: 'Educational Qualification',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.edu_id',
        sourceApplicantPath: 'personalInfo.educationalQualification',
        requiredInPortal: true,
        options: [
          { value: 'GRADUATE', label: 'GRADUATE' },
          { value: 'POST GRADUATE', label: 'POST GRADUATE' },
          { value: 'HIGHER SECONDARY', label: 'HIGHER SECONDARY' },
          { value: 'MATRICULATION', label: 'MATRICULATION' },
          { value: 'BELOW MATRICULATION', label: 'BELOW MATRICULATION' },
          { value: 'PROFESSIONAL', label: 'PROFESSIONAL' },
          { value: 'ILLITERATE', label: 'ILLITERATE' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
      },
      {
        key: 'appl.nationality_by',
        label: 'Nationality Acquired By',
        section: 'basicDetails',
        subsection: 'Personal Details',
        inputType: 'select',
        targetMappingField: 'appl.nationality_by',
        sourceApplicantPath: 'personalInfo.nationalityAcquiredBy',
        requiredInPortal: true,
        options: [
          { value: 'Birth', label: 'By Birth' },
          { value: 'Naturalization', label: 'By Naturalization' },
        ],
      },

      // Passport Sub-section
      {
        key: 'appl.passport_number',
        label: 'Passport Number',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.passport_number',
        sourceApplicantPath: 'passport.passportNumber',
        requiredInPortal: true,
      },
      {
        key: 'appl.passport_issue_place',
        label: 'Place of Issue',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.passport_issue_place',
        sourceApplicantPath: 'passport.placeOfIssue',
        requiredInPortal: true,
      },
      {
        key: 'appl.passport_issue_date',
        label: 'Passport Issue Date (DD/MM/YYYY)',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'date',
        targetMappingField: 'appl.passport_issue_date',
        sourceApplicantPath: 'passport.issueDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
      },
      {
        key: 'appl.passport_expiry_date',
        label: 'Passport Expiry Date (DD/MM/YYYY)',
        section: 'basicDetails',
        subsection: 'Passport Details',
        inputType: 'date',
        targetMappingField: 'appl.passport_expiry_date',
        sourceApplicantPath: 'passport.expiryDate',
        requiredInPortal: true,
        placeholder: 'DD/MM/YYYY',
      },
      {
        key: 'appl.oth_ppt',
        label: 'Do you hold any other valid passport/identity certificate?',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'radio',
        targetMappingField: 'appl.oth_ppt',
        sourceApplicantPath: 'passport.holdsOtherPassport',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'appl.oth_pptno',
        label: 'Other Passport / IC Number',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.oth_pptno',
        sourceApplicantPath: 'passport.otherPassportDetails.passportNumber',
      },
      {
        key: 'appl.oth_ppt_issue_place',
        label: 'Other Passport Place of Issue',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'text',
        targetMappingField: 'appl.oth_ppt_issue_place',
        sourceApplicantPath: 'passport.otherPassportDetails.placeOfIssue',
      },
      {
        key: 'appl.prev_passport_country_issue',
        label: 'Other Passport Country of Issue',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'select',
        targetMappingField: 'appl.prev_passport_country_issue',
        sourceApplicantPath: 'passport.otherPassportDetails.countryOfIssue',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
      },
      {
        key: 'appl.other_ppt_nationality',
        label: 'Other Passport Nationality',
        section: 'basicDetails',
        subsection: 'Other Passport Details',
        inputType: 'select',
        targetMappingField: 'appl.other_ppt_nationality',
        sourceApplicantPath: 'passport.otherPassportDetails.nationalityInPassport',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'USA', label: 'UNITED STATES OF AMERICA' },
          { value: 'UK', label: 'UNITED KINGDOM' },
        ],
      },
    ],
  },
  {
    id: 'familyDetails',
    title: '3. Family Details',
    subtitle: 'Applicant address, family members, and employment information',
    iconName: 'Users',
    manualNotices: [
      {
        title: 'Same Address Checkbox',
        message: 'The Same Address checkbox is a dynamic portal control and remains manual on the Indian Visa website.',
      },
    ],
    fields: [
      // Present Address
      {
        key: 'pres_addr1',
        label: 'Present Address Line 1 (House No / Street)',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_addr1',
        sourceApplicantPath: 'presentAddress.addressLine1',
        requiredInPortal: true,
      },
      {
        key: 'pres_addr2',
        label: 'Present Address Line 2',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_addr2',
        sourceApplicantPath: 'presentAddress.addressLine2',
      },
      {
        key: 'state_name',
        label: 'Village / Town / City / District',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'state_name',
        sourceApplicantPath: 'presentAddress.villageTownCity',
        requiredInPortal: true,
      },
      {
        key: 'pincode',
        label: 'Postal / Pincode',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pincode',
        sourceApplicantPath: 'presentAddress.postalCode',
      },
      {
        key: 'pres_phone',
        label: 'Phone Number',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'pres_phone',
        sourceApplicantPath: 'contact.phone',
      },
      {
        key: 'mobile',
        label: 'Mobile Number',
        section: 'familyDetails',
        subsection: 'Present Address',
        inputType: 'text',
        targetMappingField: 'mobile',
        sourceApplicantPath: 'contact.mobile',
      },

      // Permanent Address
      {
        key: 'perm_add1',
        label: 'Permanent Address Line 1',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add1',
        sourceApplicantPath: 'permanentAddress.addressLine1',
        requiredInPortal: true,
      },
      {
        key: 'perm_add2',
        label: 'Permanent Address Line 2',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add2',
        sourceApplicantPath: 'permanentAddress.addressLine2',
      },
      {
        key: 'perm_add3',
        label: 'Permanent Village / Town / City / State',
        section: 'familyDetails',
        subsection: 'Permanent Address',
        inputType: 'text',
        targetMappingField: 'perm_add3',
        sourceApplicantPath: 'permanentAddress.villageTownCity',
        requiredInPortal: true,
      },

      // Father Details
      {
        key: 'fthrname',
        label: "Father's Full Name",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'text',
        targetMappingField: 'fthrname',
        sourceApplicantPath: 'family.father.name',
        requiredInPortal: true,
      },
      {
        key: 'father_place_of_birth',
        label: "Father's Place of Birth",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'text',
        targetMappingField: 'father_place_of_birth',
        sourceApplicantPath: 'family.father.placeOfBirth',
      },
      {
        key: 'father_country_of_birth',
        label: "Father's Country of Birth",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_country_of_birth',
        sourceApplicantPath: 'family.father.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'father_nationality',
        label: "Father's Nationality",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_nationality',
        sourceApplicantPath: 'family.father.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'father_prev_nationality',
        label: "Father's Previous Nationality",
        section: 'familyDetails',
        subsection: "Father's Details",
        inputType: 'select',
        targetMappingField: 'father_prev_nationality',
        sourceApplicantPath: 'family.father.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },

      // Mother Details
      {
        key: 'mother_name',
        label: "Mother's Full Name",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'text',
        targetMappingField: 'mother_name',
        sourceApplicantPath: 'family.mother.name',
        requiredInPortal: true,
      },
      {
        key: 'mother_place_of_birth',
        label: "Mother's Place of Birth",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'text',
        targetMappingField: 'mother_place_of_birth',
        sourceApplicantPath: 'family.mother.placeOfBirth',
      },
      {
        key: 'mother_country_of_birth',
        label: "Mother's Country of Birth",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_country_of_birth',
        sourceApplicantPath: 'family.mother.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'mother_nationality',
        label: "Mother's Nationality",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_nationality',
        sourceApplicantPath: 'family.mother.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'mother_prev_nationality',
        label: "Mother's Previous Nationality",
        section: 'familyDetails',
        subsection: "Mother's Details",
        inputType: 'select',
        targetMappingField: 'mother_prev_nationality',
        sourceApplicantPath: 'family.mother.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },

      // Marital & Spouse
      {
        key: 'marital_status',
        label: 'Marital Status',
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'marital_status',
        sourceApplicantPath: 'personalInfo.maritalStatus',
        options: [
          { value: 'Married', label: 'Married' },
          { value: 'Single', label: 'Single / Unmarried' },
          { value: 'Divorced', label: 'Divorced' },
          { value: 'Widow/Widower', label: 'Widow/Widower' },
        ],
      },
      {
        key: 'spouse_name',
        label: "Spouse's Full Name",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'text',
        targetMappingField: 'spouse_name',
        sourceApplicantPath: 'family.spouse.name',
      },
      {
        key: 'spouse_place_of_birth',
        label: "Spouse's Place of Birth",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'text',
        targetMappingField: 'spouse_place_of_birth',
        sourceApplicantPath: 'family.spouse.placeOfBirth',
      },
      {
        key: 'spouse_country_of_birth',
        label: "Spouse's Country of Birth",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_country_of_birth',
        sourceApplicantPath: 'family.spouse.countryOfBirth',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'spouse_nationality',
        label: "Spouse's Nationality",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_nationality',
        sourceApplicantPath: 'family.spouse.nationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },
      {
        key: 'spouse_prev_nationality',
        label: "Spouse's Previous Nationality",
        section: 'familyDetails',
        subsection: 'Marital & Spouse Details',
        inputType: 'select',
        targetMappingField: 'spouse_prev_nationality',
        sourceApplicantPath: 'family.spouse.previousNationality',
        options: [
          { value: 'BANGLADESH', label: 'BANGLADESH' },
          { value: 'INDIA', label: 'INDIA' },
          { value: 'PAKISTAN', label: 'PAKISTAN' },
        ],
      },

      // Grandparents / Pakistan Relation
      {
        key: 'grandparent_flag',
        label: 'Were your Grandfather/Grandmother Pakistan nationals or belong to Pakistan held area?',
        section: 'familyDetails',
        subsection: 'Origin Details',
        inputType: 'radio',
        targetMappingField: 'grandparent_flag',
        sourceApplicantPath: 'family.hasPakistanRelation',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'grandparent_details',
        label: 'If yes, give details',
        section: 'familyDetails',
        subsection: 'Origin Details',
        inputType: 'textarea',
        targetMappingField: 'grandparent_details',
        sourceApplicantPath: 'family.pakistanRelationDetails',
      },

      // Employment
      {
        key: 'occupation',
        label: 'Present Occupation',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'select',
        targetMappingField: 'occupation',
        sourceApplicantPath: 'employment.presentOccupation',
        requiredInPortal: true,
        options: [
          { value: 'BUSINESS PERSON', label: 'BUSINESS PERSON' },
          { value: 'PRIVATE SERVICE', label: 'PRIVATE SERVICE' },
          { value: 'GOVT SERVICE', label: 'GOVERNMENT SERVICE' },
          { value: 'HOUSEWIFE', label: 'HOUSEWIFE' },
          { value: 'STUDENT', label: 'STUDENT' },
          { value: 'RETIRED', label: 'RETIRED' },
          { value: 'TEACHER', label: 'TEACHER' },
          { value: 'DOCTOR', label: 'DOCTOR' },
          { value: 'ENGINEER', label: 'ENGINEER' },
          { value: 'ADVOCATE', label: 'ADVOCATE / LAWYER' },
          { value: 'JOURNALIST', label: 'JOURNALIST' },
          { value: 'UN-EMPLOYED', label: 'UN-EMPLOYED' },
          { value: 'OTHERS', label: 'OTHERS' },
        ],
      },
      {
        key: 'empname',
        label: 'Employer / Business Name',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empname',
        sourceApplicantPath: 'employment.employerName',
      },
      {
        key: 'empdesignation',
        label: 'Designation / Rank',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empdesignation',
        sourceApplicantPath: 'employment.designationRank',
      },
      {
        key: 'empaddress',
        label: 'Employer Address',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empaddress',
        sourceApplicantPath: 'employment.employerAddress',
      },
      {
        key: 'empphone',
        label: 'Employer Phone Number',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'text',
        targetMappingField: 'empphone',
        sourceApplicantPath: 'employment.employerPhone',
      },
      {
        key: 'previous_occupation',
        label: 'Past / Previous Occupation (if any)',
        section: 'familyDetails',
        subsection: 'Occupation Details',
        inputType: 'select',
        targetMappingField: 'previous_occupation',
        sourceApplicantPath: 'employment.pastOccupation',
        options: [
          { value: 'NONE', label: 'NONE' },
          { value: 'BUSINESS PERSON', label: 'BUSINESS PERSON' },
          { value: 'PRIVATE SERVICE', label: 'PRIVATE SERVICE' },
          { value: 'GOVT SERVICE', label: 'GOVERNMENT SERVICE' },
        ],
      },
      {
        key: 'prev_org',
        label: 'Are you in/have you served in Military/Semi-Military/Police/Security Organization?',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'radio',
        targetMappingField: 'prev_org',
        sourceApplicantPath: 'employment.hasMilitaryService',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'previous_organization',
        label: 'Organization Name',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_organization',
        sourceApplicantPath: 'employment.militaryOrganization',
      },
      {
        key: 'previous_designation',
        label: 'Designation',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_designation',
        sourceApplicantPath: 'employment.militaryDesignation',
      },
      {
        key: 'previous_rank',
        label: 'Rank',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_rank',
        sourceApplicantPath: 'employment.militaryRank',
      },
      {
        key: 'previous_posting',
        label: 'Place of Posting',
        section: 'familyDetails',
        subsection: 'Military / Security Details',
        inputType: 'text',
        targetMappingField: 'previous_posting',
        sourceApplicantPath: 'employment.militaryPlaceOfPosting',
      },
    ],
  },
  {
    id: 'visaDetails',
    title: '4. Visa Details',
    subtitle: 'Visa duration, travel history, old visas, and reference information',
    iconName: 'Compass',
    manualNotices: [
      {
        title: 'Visa Refusal Disclosures',
        message: 'Visa refusal questions are sensitive legal disclosures and must be answered manually on the website.',
      },
    ],
    fields: [
      {
        key: 'duration',
        label: 'Duration of Visa (in Months)',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'text',
        targetMappingField: 'duration',
        sourceApplicantPath: 'travel.duration',
        placeholder: 'e.g. 12 or 6',
      },
      {
        key: 'visa_entry_id',
        label: 'Number of Entries',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'visa_entry_id',
        sourceApplicantPath: 'travel.visaEntryType',
        options: [
          { value: 'Multiple', label: 'Multiple Entry' },
          { value: 'Double', label: 'Double Entry' },
          { value: 'Triple', label: 'Triple Entry' },
          { value: 'Single', label: 'Single Entry' },
        ],
      },
      {
        key: 'journeydate',
        label: 'Expected Date of Journey (DD/MM/YYYY)',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'date',
        targetMappingField: 'journeydate',
        sourceApplicantPath: 'travel.intendedArrivalDate',
        placeholder: 'DD/MM/YYYY',
      },
      {
        key: 'entrypoint',
        label: 'Port of Arrival in India',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'entrypoint',
        sourceApplicantPath: 'travel.entryPoint',
        options: [
          { value: 'HARIDASPUR RAIL', label: 'HARIDASPUR RAIL' },
          { value: 'HARIDASPUR ROAD', label: 'HARIDASPUR ROAD (BENAPOLE)' },
          { value: 'CHANGRIBANDHA ROAD', label: 'CHANGRIBANDHA ROAD' },
          { value: 'DAWKI ROAD', label: 'DAWKI ROAD' },
          { value: 'GELEPHU ROAD', label: 'GELEPHU ROAD' },
          { value: 'HILI ROAD', label: 'HILI ROAD' },
          { value: 'KOLKATA AIRPORT', label: 'KOLKATA AIRPORT' },
          { value: 'DELHI AIRPORT', label: 'DELHI AIRPORT' },
          { value: 'CHENNAI AIRPORT', label: 'CHENNAI AIRPORT' },
        ],
      },
      {
        key: 'exitpoint',
        label: 'Expected Port of Exit from India',
        section: 'visaDetails',
        subsection: 'Visa Information',
        inputType: 'select',
        targetMappingField: 'exitpoint',
        sourceApplicantPath: 'travel.exitPoint',
        options: [
          { value: 'HARIDASPUR RAIL', label: 'HARIDASPUR RAIL' },
          { value: 'HARIDASPUR ROAD', label: 'HARIDASPUR ROAD (BENAPOLE)' },
          { value: 'CHANGRIBANDHA ROAD', label: 'CHANGRIBANDHA ROAD' },
          { value: 'DAWKI ROAD', label: 'DAWKI ROAD' },
          { value: 'KOLKATA AIRPORT', label: 'KOLKATA AIRPORT' },
          { value: 'DELHI AIRPORT', label: 'DELHI AIRPORT' },
        ],
      },

      // Previous Indian Visa
      {
        key: 'old_visa_flag',
        label: 'Have you visited India previously?',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'radio',
        targetMappingField: 'old_visa_flag',
        sourceApplicantPath: 'previousVisa.hasPreviousVisa',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'prv_visit_add1',
        label: 'Address stayed during previous visit (Line 1)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add1',
        sourceApplicantPath: 'previousVisa.visitedAddress1',
      },
      {
        key: 'prv_visit_add2',
        label: 'Address stayed during previous visit (Line 2)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add2',
        sourceApplicantPath: 'previousVisa.visitedAddress2',
      },
      {
        key: 'prv_visit_add3',
        label: 'Cities previously visited in India',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'prv_visit_add3',
        sourceApplicantPath: 'previousVisa.visitedAddress3',
      },
      {
        key: 'old_visa_no',
        label: 'Previous Visa Number',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'old_visa_no',
        sourceApplicantPath: 'previousVisa.visaNumber',
      },
      {
        key: 'old_visa_type_id',
        label: 'Previous Visa Type',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'select',
        targetMappingField: 'old_visa_type_id',
        sourceApplicantPath: 'previousVisa.visaType',
        options: [
          { value: 'TOURIST VISA', label: 'TOURIST VISA' },
          { value: 'MEDICAL VISA', label: 'MEDICAL VISA' },
          { value: 'BUSINESS VISA', label: 'BUSINESS VISA' },
          { value: 'ENTRY VISA', label: 'ENTRY VISA' },
          { value: 'STUDENT VISA', label: 'STUDENT VISA' },
        ],
      },
      {
        key: 'oldvisaissueplace',
        label: 'Previous Visa Place of Issue',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'text',
        targetMappingField: 'oldvisaissueplace',
        sourceApplicantPath: 'previousVisa.placeOfIssue',
      },
      {
        key: 'oldvisaissuedate',
        label: 'Previous Visa Issue Date (DD/MM/YYYY)',
        section: 'visaDetails',
        subsection: 'Previous Visa / Visit Details',
        inputType: 'date',
        targetMappingField: 'oldvisaissuedate',
        sourceApplicantPath: 'previousVisa.dateOfIssue',
        placeholder: 'DD/MM/YYYY',
      },

      // Travel history
      {
        key: 'country_visited',
        label: 'Countries Visited in the Last 10 Years',
        section: 'visaDetails',
        subsection: 'Travel History',
        inputType: 'text',
        targetMappingField: 'country_visited',
        sourceApplicantPath: 'travel.countriesVisited',
        placeholder: 'e.g. INDIA, MALAYSIA, THAILAND',
      },
      {
        key: 'saarc_flag',
        label: 'Have you visited SAARC countries during the last 3 years?',
        section: 'visaDetails',
        subsection: 'Travel History',
        inputType: 'radio',
        targetMappingField: 'saarc_flag',
        sourceApplicantPath: 'travel.visitedSaarc',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },

      // References
      {
        key: 'nameofsponsor_ind',
        label: 'Reference Name in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'nameofsponsor_ind',
        sourceApplicantPath: 'reference.name',
      },
      {
        key: 'add1ofsponsor_ind',
        label: 'Address Line 1 in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'add1ofsponsor_ind',
        sourceApplicantPath: 'reference.addressLine1',
      },
      {
        key: 'add2ofsponsor_ind',
        label: 'Address Line 2 in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'add2ofsponsor_ind',
        sourceApplicantPath: 'reference.addressLine2',
      },
      {
        key: 'phoneofsponsor_ind',
        label: 'Phone Number in India',
        section: 'visaDetails',
        subsection: 'Reference in India',
        inputType: 'text',
        targetMappingField: 'phoneofsponsor_ind',
        sourceApplicantPath: 'reference.phone',
      },
      {
        key: 'nameofsponsor_msn',
        label: 'Reference Name in Bangladesh / Home Country',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'nameofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.name',
      },
      {
        key: 'add1ofsponsor_msn',
        label: 'Address Line 1 in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'add1ofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.addressLine1',
      },
      {
        key: 'add2ofsponsor_msn',
        label: 'Address Line 2 in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'add2ofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.addressLine2',
      },
      {
        key: 'phoneofsponsor_msn',
        label: 'Phone Number in Bangladesh',
        section: 'visaDetails',
        subsection: 'Reference in Bangladesh',
        inputType: 'text',
        targetMappingField: 'phoneofsponsor_msn',
        sourceApplicantPath: 'sponsorMission.phone',
      },
    ],
  },
  {
    id: 'additionalQuestions',
    title: '5. Additional Questions',
    subtitle: '6 legal/security question groups and applicant declaration',
    iconName: 'ShieldAlert',
    manualNotices: [
      {
        title: 'Applicant Declaration',
        message: 'The final declaration checkbox is a legal acknowledgement and must be confirmed manually by the applicant on the Indian Visa website.',
      },
    ],
    fields: [
      {
        key: 'question_1_flag',
        label: '1. Have you ever been arrested/prosecuted/convicted by Court of Law?',
        section: 'additionalQuestions',
        subsection: 'Question 1',
        inputType: 'radio',
        targetMappingField: 'question_1_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_1',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 1',
        inputType: 'textarea',
        targetMappingField: 'answer_1',
      },
      {
        key: 'question_2_flag',
        label: '2. Have you ever been refused entry / deported by any country including India?',
        section: 'additionalQuestions',
        subsection: 'Question 2',
        inputType: 'radio',
        targetMappingField: 'question_2_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_2',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 2',
        inputType: 'textarea',
        targetMappingField: 'answer_2',
      },
      {
        key: 'question_3_flag',
        label: '3. Have you ever been engaged in human trafficking / drug trafficking / financial fraud / crimes against humanity?',
        section: 'additionalQuestions',
        subsection: 'Question 3',
        inputType: 'radio',
        targetMappingField: 'question_3_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_3',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 3',
        inputType: 'textarea',
        targetMappingField: 'answer_3',
      },
      {
        key: 'question_4_flag',
        label: '4. Have you ever been involved in cyber crime / terrorist activities / sabotage / espionage?',
        section: 'additionalQuestions',
        subsection: 'Question 4',
        inputType: 'radio',
        targetMappingField: 'question_4_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_4',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 4',
        inputType: 'textarea',
        targetMappingField: 'answer_4',
      },
      {
        key: 'question_5_flag',
        label: '5. Have you ever by any means expressed views that justify or glorify terrorist violence?',
        section: 'additionalQuestions',
        subsection: 'Question 5',
        inputType: 'radio',
        targetMappingField: 'question_5_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_5',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 5',
        inputType: 'textarea',
        targetMappingField: 'answer_5',
      },
      {
        key: 'question_6_flag',
        label: '6. Have you sought asylum or refuge in any country?',
        section: 'additionalQuestions',
        subsection: 'Question 6',
        inputType: 'radio',
        targetMappingField: 'question_6_flag',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
      {
        key: 'answer_6',
        label: 'If yes, give details',
        section: 'additionalQuestions',
        subsection: 'Question 6',
        inputType: 'textarea',
        targetMappingField: 'answer_6',
      },
    ],
  },
  {
    id: 'photoUpload',
    title: '6. Photo Section',
    subtitle: 'Applicant photograph management',
    iconName: 'Camera',
    manualNotices: [
      {
        title: 'Portal Photo Chooser',
        message: 'On the Indian Visa website, photograph file selection remains manual. Extension manages the photo here in your workspace for verification and preview.',
      },
    ],
    fields: [],
  },
]

export function getAllSchemaFields(): ApplicationFieldDef[] {
  return BANGLADESH_APPLICATION_SCHEMA.flatMap((s) => s.fields)
}
