import type { IndiaFieldCoverageItem } from './types'

export const INDIA_FIELD_COVERAGE_REGISTRY: IndiaFieldCoverageItem[] = [
  // --- Personal Information (Regular Visa) ---
  {
    fieldId: 'reg_surname',
    fieldLabel: 'Surname / Family Name',
    profileSourcePath: 'personalInfo.surname',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#surname',
    fallbackSelector: 'input[name="surname"]',
    status: 'fixture-tested',
    notes: 'Tested against synthetic form DOM.',
  },
  {
    fieldId: 'reg_given_name',
    fieldLabel: 'Given Name(s)',
    profileSourcePath: 'personalInfo.givenNames',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#given_name',
    fallbackSelector: 'input[name="given_name"]',
    status: 'fixture-tested',
    notes: 'Tested against synthetic form DOM.',
  },
  {
    fieldId: 'reg_dob',
    fieldLabel: 'Date of Birth',
    profileSourcePath: 'personalInfo.dateOfBirth',
    flow: 'regular',
    page: 'application-form',
    controlType: 'date',
    primarySelector: '#dob',
    fallbackSelector: 'input[name="dob"]',
    status: 'fixture-tested',
    notes: 'Requires DD/MM/YYYY format conversion.',
  },
  {
    fieldId: 'reg_nationality',
    fieldLabel: 'Nationality',
    profileSourcePath: 'personalInfo.nationality',
    flow: 'regular',
    page: 'application-form',
    controlType: 'select',
    primarySelector: '#nationality',
    fallbackSelector: 'select[name="nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_gender',
    fieldLabel: 'Gender',
    profileSourcePath: 'personalInfo.gender',
    flow: 'regular',
    page: 'application-form',
    controlType: 'radio',
    primarySelector: '#gender_male',
    fallbackSelector: 'input[name="gender"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_town_of_birth',
    fieldLabel: 'Town/City of Birth',
    profileSourcePath: 'personalInfo.townCityOfBirth',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#place_of_birth',
    fallbackSelector: 'input[name="place_of_birth"]',
    status: 'needs-verification',
  },
  {
    fieldId: 'reg_country_of_birth',
    fieldLabel: 'Country of Birth',
    profileSourcePath: 'personalInfo.countryOfBirth',
    flow: 'regular',
    page: 'application-form',
    controlType: 'select',
    primarySelector: '#country_of_birth',
    fallbackSelector: 'select[name="country_of_birth"]',
    status: 'needs-verification',
  },

  // --- Passport Information (Regular Visa) ---
  {
    fieldId: 'reg_passport_no',
    fieldLabel: 'Passport Number',
    profileSourcePath: 'passport.passportNumber',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#passport_no',
    fallbackSelector: 'input[name="passport_no"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_passport_issue_place',
    fieldLabel: 'Place of Issue',
    profileSourcePath: 'passport.placeOfIssue',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#passport_issue_place',
    fallbackSelector: 'input[name="passport_issue_place"]',
    status: 'needs-verification',
  },
  {
    fieldId: 'reg_passport_issue_date',
    fieldLabel: 'Passport Issue Date',
    profileSourcePath: 'passport.issueDate',
    flow: 'regular',
    page: 'application-form',
    controlType: 'date',
    primarySelector: '#passport_issue_date',
    fallbackSelector: 'input[name="passport_issue_date"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_passport_expiry_date',
    fieldLabel: 'Passport Expiry Date',
    profileSourcePath: 'passport.expiryDate',
    flow: 'regular',
    page: 'application-form',
    controlType: 'date',
    primarySelector: '#passport_expiry_date',
    fallbackSelector: 'input[name="passport_expiry_date"]',
    status: 'fixture-tested',
  },

  // --- Manual-Only Security Boundaries ---
  {
    fieldId: 'captcha_field',
    fieldLabel: 'CAPTCHA Security Image',
    profileSourcePath: 'n/a',
    flow: 'regular',
    page: 'application-start',
    controlType: 'text',
    primarySelector: '#captcha_input',
    status: 'manual-only',
    notes: 'CAPTCHA solving is strictly manual.',
  },
  {
    fieldId: 'payment_gateway',
    fieldLabel: 'Payment Confirmation Gateway',
    profileSourcePath: 'n/a',
    flow: 'regular',
    page: 'application-form',
    controlType: 'text',
    primarySelector: '#payment_submit',
    status: 'manual-only',
    notes: 'Payment processing is strictly manual.',
  },
]
