import type { IndiaFieldCoverageItem } from './types'

export const INDIA_FIELD_COVERAGE_REGISTRY: IndiaFieldCoverageItem[] = [
  // --- Personal & Passport Information (Regular Visa) ---
  {
    fieldId: 'reg_surname',
    fieldLabel: 'Surname / Family Name',
    profileSourcePath: 'personalInfo.surname',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'text',
    primarySelector: '#surname',
    fallbackSelector: 'input[name="surname"]',
    status: 'fixture-tested',
    notes: 'Tested against synthetic form DOM.',
  },
  {
    fieldId: 'reg_given_name',
    fieldLabel: 'Given Name(s)',
    profileSourcePath: 'personalInfo.givenNames',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'text',
    primarySelector: '#given_name',
    fallbackSelector: 'input[name="given_name"]',
    status: 'fixture-tested',
    notes: 'Tested against synthetic form DOM.',
  },
  {
    fieldId: 'reg_dob',
    fieldLabel: 'Date of Birth',
    profileSourcePath: 'personalInfo.dateOfBirth',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'date',
    primarySelector: '#dob',
    fallbackSelector: 'input[name="dob"]',
    status: 'fixture-tested',
    notes: 'Requires DD/MM/YYYY format conversion.',
  },
  {
    fieldId: 'reg_nationality',
    fieldLabel: 'Nationality',
    profileSourcePath: 'personalInfo.nationality',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'select',
    primarySelector: '#nationality',
    fallbackSelector: 'select[name="nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_gender',
    fieldLabel: 'Gender',
    profileSourcePath: 'personalInfo.gender',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'radio',
    primarySelector: '#gender_male',
    fallbackSelector: 'input[name="gender"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_town_of_birth',
    fieldLabel: 'Town/City of Birth',
    profileSourcePath: 'personalInfo.townCityOfBirth',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'text',
    primarySelector: '#place_of_birth',
    fallbackSelector: 'input[name="place_of_birth"]',
    status: 'needs-verification',
  },
  {
    fieldId: 'reg_country_of_birth',
    fieldLabel: 'Country of Birth',
    profileSourcePath: 'personalInfo.countryOfBirth',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'select',
    primarySelector: '#country_of_birth',
    fallbackSelector: 'select[name="country_of_birth"]',
    status: 'needs-verification',
  },
  {
    fieldId: 'reg_passport_no',
    fieldLabel: 'Passport Number',
    profileSourcePath: 'passport.passportNumber',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'text',
    primarySelector: '#passport_no',
    fallbackSelector: 'input[name="passport_no"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_passport_issue_place',
    fieldLabel: 'Place of Issue',
    profileSourcePath: 'passport.placeOfIssue',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'text',
    primarySelector: '#passport_issue_place',
    fallbackSelector: 'input[name="passport_issue_place"]',
    status: 'needs-verification',
  },
  {
    fieldId: 'reg_passport_issue_date',
    fieldLabel: 'Passport Issue Date',
    profileSourcePath: 'passport.issueDate',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'date',
    primarySelector: '#passport_issue_date',
    fallbackSelector: 'input[name="passport_issue_date"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_passport_expiry_date',
    fieldLabel: 'Passport Expiry Date',
    profileSourcePath: 'passport.expiryDate',
    flow: 'regular',
    page: 'personal-details',
    controlType: 'date',
    primarySelector: '#passport_expiry_date',
    fallbackSelector: 'input[name="passport_expiry_date"]',
    status: 'fixture-tested',
  },

  // --- Address & Contact (Page 3) ---
  {
    fieldId: 'reg_present_addr1',
    fieldLabel: 'Present Address Line 1',
    profileSourcePath: 'presentAddress.addressLine1',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="pres_addr1"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_present_addr2',
    fieldLabel: 'Present Address Line 2',
    profileSourcePath: 'presentAddress.addressLine2',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="pres_addr2"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_present_city',
    fieldLabel: 'Present Village/Town/City',
    profileSourcePath: 'presentAddress.villageTownCity',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="pres_city"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_present_state',
    fieldLabel: 'Present State/Province',
    profileSourcePath: 'presentAddress.stateProvince',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="pres_state"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_present_country',
    fieldLabel: 'Present Country',
    profileSourcePath: 'presentAddress.country',
    flow: 'regular',
    page: 'address-details',
    controlType: 'select',
    primarySelector: '[name="pres_country"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_present_zip',
    fieldLabel: 'Present Postal/ZIP Code',
    profileSourcePath: 'presentAddress.postalCode',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="pres_postal_code"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mobile',
    fieldLabel: 'Present Mobile Number',
    profileSourcePath: 'contact.mobile',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="mobile_no"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_phone',
    fieldLabel: 'Present Phone Number',
    profileSourcePath: 'contact.phone',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="phone_no"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_addr1',
    fieldLabel: 'Permanent Address Line 1',
    profileSourcePath: 'permanentAddress.addressLine1',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="perm_addr1"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_addr2',
    fieldLabel: 'Permanent Address Line 2',
    profileSourcePath: 'permanentAddress.addressLine2',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="perm_addr2"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_city',
    fieldLabel: 'Permanent Village/Town/City',
    profileSourcePath: 'permanentAddress.villageTownCity',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="perm_city"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_state',
    fieldLabel: 'Permanent State/Province',
    profileSourcePath: 'permanentAddress.stateProvince',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="perm_state"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_country',
    fieldLabel: 'Permanent Country',
    profileSourcePath: 'permanentAddress.country',
    flow: 'regular',
    page: 'address-details',
    controlType: 'select',
    primarySelector: '[name="perm_country"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_permanent_zip',
    fieldLabel: 'Permanent Postal/ZIP Code',
    profileSourcePath: 'permanentAddress.postalCode',
    flow: 'regular',
    page: 'address-details',
    controlType: 'text',
    primarySelector: '[name="perm_postal_code"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_same_addr',
    fieldLabel: 'Same as Present Address Flag',
    profileSourcePath: 'permanentAddress.sameAsPresentAddress',
    flow: 'regular',
    page: 'address-details',
    controlType: 'checkbox',
    primarySelector: '[name="same_address"]',
    status: 'fixture-tested',
  },

  // --- Family Details (Page 4) ---
  {
    fieldId: 'reg_father_name',
    fieldLabel: "Father's Name",
    profileSourcePath: 'family.father.name',
    flow: 'regular',
    page: 'family-details',
    controlType: 'text',
    primarySelector: '[name="father_name"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_father_nationality',
    fieldLabel: "Father's Nationality",
    profileSourcePath: 'family.father.nationality',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="father_nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_father_prev_nationality',
    fieldLabel: "Father's Previous Nationality",
    profileSourcePath: 'family.father.previousNationality',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="father_prev_nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_father_place_birth',
    fieldLabel: "Father's Place of Birth",
    profileSourcePath: 'family.father.placeOfBirth',
    flow: 'regular',
    page: 'family-details',
    controlType: 'text',
    primarySelector: '[name="father_place_birth"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_father_country_birth',
    fieldLabel: "Father's Country of Birth",
    profileSourcePath: 'family.father.countryOfBirth',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="father_country_birth"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mother_name',
    fieldLabel: "Mother's Name",
    profileSourcePath: 'family.mother.name',
    flow: 'regular',
    page: 'family-details',
    controlType: 'text',
    primarySelector: '[name="mother_name"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mother_nationality',
    fieldLabel: "Mother's Nationality",
    profileSourcePath: 'family.mother.nationality',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="mother_nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mother_prev_nationality',
    fieldLabel: "Mother's Previous Nationality",
    profileSourcePath: 'family.mother.previousNationality',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="mother_prev_nationality"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mother_place_birth',
    fieldLabel: "Mother's Place of Birth",
    profileSourcePath: 'family.mother.placeOfBirth',
    flow: 'regular',
    page: 'family-details',
    controlType: 'text',
    primarySelector: '[name="mother_place_birth"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_mother_country_birth',
    fieldLabel: "Mother's Country of Birth",
    profileSourcePath: 'family.mother.countryOfBirth',
    flow: 'regular',
    page: 'family-details',
    controlType: 'select',
    primarySelector: '[name="mother_country_birth"]',
    status: 'fixture-tested',
  },

  // --- Employment / Occupation (Page 5) ---
  {
    fieldId: 'reg_present_occupation',
    fieldLabel: 'Present Occupation',
    profileSourcePath: 'employment.presentOccupation',
    flow: 'regular',
    page: 'occupation-details',
    controlType: 'select',
    primarySelector: '[name="present_occupation"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_designation',
    fieldLabel: 'Designation / Rank',
    profileSourcePath: 'employment.designationRank',
    flow: 'regular',
    page: 'occupation-details',
    controlType: 'text',
    primarySelector: '[name="designation"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_employer_name',
    fieldLabel: 'Employer Name / Business',
    profileSourcePath: 'employment.employerName',
    flow: 'regular',
    page: 'occupation-details',
    controlType: 'text',
    primarySelector: '[name="employer_name"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_employer_address',
    fieldLabel: 'Employer Address',
    profileSourcePath: 'employment.employerAddress',
    flow: 'regular',
    page: 'occupation-details',
    controlType: 'text',
    primarySelector: '[name="employer_address"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_employer_phone',
    fieldLabel: 'Employer Phone Number',
    profileSourcePath: 'employment.employerPhone',
    flow: 'regular',
    page: 'occupation-details',
    controlType: 'text',
    primarySelector: '[name="employer_phone"]',
    status: 'fixture-tested',
  },

  // --- Travel details (Page 6) ---
  {
    fieldId: 'reg_purpose',
    fieldLabel: 'Purpose of Visit',
    profileSourcePath: 'travel.purposeOfVisit',
    flow: 'regular',
    page: 'travel-details',
    controlType: 'select',
    primarySelector: '[name="purpose"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_arrival_date',
    fieldLabel: 'Expected Arrival Date',
    profileSourcePath: 'travel.intendedArrivalDate',
    flow: 'regular',
    page: 'travel-details',
    controlType: 'date',
    primarySelector: '[name="arrival_date"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_departure_date',
    fieldLabel: 'Expected Departure Date',
    profileSourcePath: 'travel.intendedDepartureDate',
    flow: 'regular',
    page: 'travel-details',
    controlType: 'date',
    primarySelector: '[name="departure_date"]',
    status: 'fixture-tested',
  },

  // --- Accommodation & References (Page 7) ---
  {
    fieldId: 'reg_hotel_name',
    fieldLabel: 'Place / Hotel Name',
    profileSourcePath: 'accommodation.placeHotelName',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="hotel_name"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_hotel_address',
    fieldLabel: 'Hotel Address',
    profileSourcePath: 'accommodation.address',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="hotel_address"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_hotel_state',
    fieldLabel: 'Hotel State',
    profileSourcePath: 'accommodation.state',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'select',
    primarySelector: '[name="hotel_state"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_hotel_phone',
    fieldLabel: 'Hotel Phone Number',
    profileSourcePath: 'accommodation.phone',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="hotel_phone"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_booking_ref',
    fieldLabel: 'Booking Reference',
    profileSourcePath: 'accommodation.bookingReference',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="booking_ref"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_ref_india_name',
    fieldLabel: 'Reference in India Name',
    profileSourcePath: 'reference.name',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="ref_india_name"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_ref_india_address',
    fieldLabel: 'Reference in India Address',
    profileSourcePath: 'reference.address',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="ref_india_address"]',
    status: 'fixture-tested',
  },
  {
    fieldId: 'reg_ref_india_phone',
    fieldLabel: 'Reference in India Phone',
    profileSourcePath: 'reference.phone',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '[name="ref_india_phone"]',
    status: 'fixture-tested',
  },

  // --- Manual-Only Security Boundaries ---
  {
    fieldId: 'captcha_field',
    fieldLabel: 'CAPTCHA Security Image',
    profileSourcePath: 'n/a',
    flow: 'regular',
    page: 'application-start',
    controlType: 'text',
    primarySelector: '#captcha_input',
    status: 'manual-only',
    notes: 'CAPTCHA solving is strictly manual.',
  },
  {
    fieldId: 'payment_gateway',
    fieldLabel: 'Payment Confirmation Gateway',
    profileSourcePath: 'n/a',
    flow: 'regular',
    page: 'reference-details',
    controlType: 'text',
    primarySelector: '#payment_submit',
    status: 'manual-only',
    notes: 'Payment processing is strictly manual.',
  },
]
