import type { IndiaVisaPage } from './pages'
import type { IndiaVisaFieldId } from './types'

export type FieldDataSource =
  | 'applicant_profile'
  | 'india_visa_application'
  | 'derived'
  | 'user_input'
  | 'manual_captcha'

export type FieldRequirementStatus = 'required' | 'optional' | 'conditional'

export type FieldType =
  | 'text'
  | 'select'
  | 'radio'
  | 'checkbox'
  | 'date'
  | 'number'
  | 'textarea'
  | 'manual'

export interface IndiaVisaFieldMapping {
  page: IndiaVisaPage
  fieldId: IndiaVisaFieldId
  label: string
  sourcePath: string
  dataSource: FieldDataSource
  fieldType: FieldType
  requirement: FieldRequirementStatus
  conditionallyDisplayed?: boolean
  conditionDescription?: string
  notes?: string
}

export const INDIA_VISA_FIELD_MAPPINGS: IndiaVisaFieldMapping[] = [
  // 1. REGISTRATION PAGE
  {
    page: 'registration',
    fieldId: 'reg_applying_from_country',
    label: 'Country/Region applying visa from',
    sourcePath: 'application.registration.applyingFromCountry',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'registration',
    fieldId: 'reg_indian_mission',
    label: 'Indian Mission/Office',
    sourcePath: 'application.registration.indianMission',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'registration',
    fieldId: 'reg_nationality',
    label: 'Nationality/Region',
    sourcePath: 'applicant.personalInfo.nationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'registration',
    fieldId: 'reg_date_of_birth',
    label: 'Date of Birth',
    sourcePath: 'applicant.personalInfo.dateOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'date',
    requirement: 'required',
    notes: 'Stored as YYYY-MM-DD',
  },
  {
    page: 'registration',
    fieldId: 'reg_email',
    label: 'Email ID',
    sourcePath: 'applicant.contact.email',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'registration',
    fieldId: 'reg_reenter_email',
    label: 'Re-enter Email ID',
    sourcePath: 'applicant.contact.email',
    dataSource: 'derived',
    fieldType: 'text',
    requirement: 'required',
    notes: 'Derived from reg_email for validation confirmation',
  },
  {
    page: 'registration',
    fieldId: 'reg_expected_arrival_date',
    label: 'Expected Date of Arrival',
    sourcePath: 'application.registration.expectedArrivalDate',
    dataSource: 'india_visa_application',
    fieldType: 'date',
    requirement: 'required',
  },
  {
    page: 'registration',
    fieldId: 'reg_captcha',
    label: 'CAPTCHA',
    sourcePath: 'application.registration.captchaCompletedManually',
    dataSource: 'manual_captcha',
    fieldType: 'manual',
    requirement: 'required',
    notes: 'MUST be entered manually by the user. Captcha cannot be automated.',
  },

  // 2. BASIC DETAILS PAGE
  {
    page: 'basic-details',
    fieldId: 'surname',
    label: 'Surname / Family Name',
    sourcePath: 'applicant.personalInfo.surname',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'given_names',
    label: 'Given Name(s)',
    sourcePath: 'applicant.personalInfo.givenNames',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'has_changed_name',
    label: 'Have you ever changed your name?',
    sourcePath: 'applicant.personalInfo.hasChangedName',
    dataSource: 'applicant_profile',
    fieldType: 'checkbox',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'previous_name',
    label: 'Previous / Other Name',
    sourcePath: 'applicant.personalInfo.previousName',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_changed_name is true',
  },
  {
    page: 'basic-details',
    fieldId: 'gender',
    label: 'Gender',
    sourcePath: 'applicant.personalInfo.gender',
    dataSource: 'applicant_profile',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'date_of_birth',
    label: 'Date of Birth',
    sourcePath: 'applicant.personalInfo.dateOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'date',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'town_city_of_birth',
    label: 'Town/City of Birth',
    sourcePath: 'applicant.personalInfo.townCityOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'country_of_birth',
    label: 'Country/Region of Birth',
    sourcePath: 'applicant.personalInfo.countryOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'national_id_number',
    label: 'Citizenship / National ID Number',
    sourcePath: 'applicant.personalInfo.nationalIdNumber',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'religion',
    label: 'Religion',
    sourcePath: 'applicant.personalInfo.religion',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'visible_identification_marks',
    label: 'Visible Identification Marks',
    sourcePath: 'applicant.personalInfo.visibleIdentificationMarks',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'educational_qualification',
    label: 'Educational Qualification',
    sourcePath: 'applicant.personalInfo.educationalQualification',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'nationality',
    label: 'Nationality',
    sourcePath: 'applicant.personalInfo.nationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'nationality_acquired_by',
    label: 'Did you acquire nationality by birth or naturalization?',
    sourcePath: 'applicant.personalInfo.nationalityAcquiredBy',
    dataSource: 'applicant_profile',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'previous_nationality',
    label: 'Previous Nationality',
    sourcePath: 'applicant.personalInfo.previousNationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if nationality acquired by naturalization',
  },
  {
    page: 'basic-details',
    fieldId: 'passport_number',
    label: 'Passport Number',
    sourcePath: 'applicant.passport.passportNumber',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'passport_place_of_issue',
    label: 'Place of Issue',
    sourcePath: 'applicant.passport.placeOfIssue',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'passport_issue_date',
    label: 'Date of Issue',
    sourcePath: 'applicant.passport.issueDate',
    dataSource: 'applicant_profile',
    fieldType: 'date',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'passport_expiry_date',
    label: 'Date of Expiry',
    sourcePath: 'applicant.passport.expiryDate',
    dataSource: 'applicant_profile',
    fieldType: 'date',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'holds_other_passport',
    label: 'Do you hold another valid Passport/Identity Certificate?',
    sourcePath: 'applicant.passport.holdsOtherPassport',
    dataSource: 'applicant_profile',
    fieldType: 'checkbox',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'other_passport_number',
    label: 'Other Passport Number',
    sourcePath: 'applicant.passport.otherPassportDetails.passportNumber',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if holds_other_passport is true',
  },
  {
    page: 'basic-details',
    fieldId: 'other_passport_country_of_issue',
    label: 'Other Passport Country of Issue',
    sourcePath: 'applicant.passport.otherPassportDetails.countryOfIssue',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if holds_other_passport is true',
  },
  {
    page: 'basic-details',
    fieldId: 'other_passport_issue_date',
    label: 'Other Passport Date of Issue',
    sourcePath: 'applicant.passport.otherPassportDetails.issueDate',
    dataSource: 'applicant_profile',
    fieldType: 'date',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if holds_other_passport is true',
  },
  {
    page: 'basic-details',
    fieldId: 'other_passport_place_of_issue',
    label: 'Other Passport Place of Issue',
    sourcePath: 'applicant.passport.otherPassportDetails.placeOfIssue',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if holds_other_passport is true',
  },
  {
    page: 'basic-details',
    fieldId: 'other_passport_nationality',
    label: 'Other Passport Nationality',
    sourcePath: 'applicant.passport.otherPassportDetails.nationalityInPassport',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if holds_other_passport is true',
  },
  // Address Fields in Basic Details
  {
    page: 'basic-details',
    fieldId: 'present_address_line1',
    label: 'Present Address Line 1',
    sourcePath: 'applicant.presentAddress.addressLine1',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_address_line2',
    label: 'Present Address Line 2',
    sourcePath: 'applicant.presentAddress.addressLine2',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'present_village_town_city',
    label: 'Present Village/Town/City',
    sourcePath: 'applicant.presentAddress.villageTownCity',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_district',
    label: 'Present District',
    sourcePath: 'applicant.presentAddress.district',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'present_state_province',
    label: 'Present State/Province',
    sourcePath: 'applicant.presentAddress.stateProvince',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_country',
    label: 'Present Country',
    sourcePath: 'applicant.presentAddress.country',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_postal_code',
    label: 'Present Postal/ZIP Code',
    sourcePath: 'applicant.presentAddress.postalCode',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_phone',
    label: 'Present Phone',
    sourcePath: 'applicant.contact.phone',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'present_mobile',
    label: 'Present Mobile',
    sourcePath: 'applicant.contact.mobile',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'present_email',
    label: 'Present Email',
    sourcePath: 'applicant.contact.email',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'same_as_present_address',
    label: 'Permanent Address same as Present Address?',
    sourcePath: 'applicant.permanentAddress.sameAsPresentAddress',
    dataSource: 'applicant_profile',
    fieldType: 'checkbox',
    requirement: 'required',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_address_line1',
    label: 'Permanent Address Line 1',
    sourcePath: 'applicant.permanentAddress.addressLine1',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if same_as_present_address is false',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_address_line2',
    label: 'Permanent Address Line 2',
    sourcePath: 'applicant.permanentAddress.addressLine2',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_village_town_city',
    label: 'Permanent Village/Town/City',
    sourcePath: 'applicant.permanentAddress.villageTownCity',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if same_as_present_address is false',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_district',
    label: 'Permanent District',
    sourcePath: 'applicant.permanentAddress.district',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_state_province',
    label: 'Permanent State/Province',
    sourcePath: 'applicant.permanentAddress.stateProvince',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if same_as_present_address is false',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_country',
    label: 'Permanent Country',
    sourcePath: 'applicant.permanentAddress.country',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if same_as_present_address is false',
  },
  {
    page: 'basic-details',
    fieldId: 'permanent_postal_code',
    label: 'Permanent Postal/ZIP Code',
    sourcePath: 'applicant.permanentAddress.postalCode',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if same_as_present_address is false',
  },

  // 3. FAMILY DETAILS PAGE
  {
    page: 'family-details',
    fieldId: 'father_name',
    label: "Father's Name",
    sourcePath: 'applicant.family.father.name',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'father_nationality',
    label: "Father's Nationality",
    sourcePath: 'applicant.family.father.nationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'father_previous_nationality',
    label: "Father's Previous Nationality",
    sourcePath: 'applicant.family.father.previousNationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'father_place_of_birth',
    label: "Father's Place of Birth",
    sourcePath: 'applicant.family.father.placeOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'father_country_of_birth',
    label: "Father's Country of Birth",
    sourcePath: 'applicant.family.father.countryOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'mother_name',
    label: "Mother's Name",
    sourcePath: 'applicant.family.mother.name',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'mother_nationality',
    label: "Mother's Nationality",
    sourcePath: 'applicant.family.mother.nationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'mother_previous_nationality',
    label: "Mother's Previous Nationality",
    sourcePath: 'applicant.family.mother.previousNationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'mother_place_of_birth',
    label: "Mother's Place of Birth",
    sourcePath: 'applicant.family.mother.placeOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'mother_country_of_birth',
    label: "Mother's Country of Birth",
    sourcePath: 'applicant.family.mother.countryOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'spouse_name',
    label: "Spouse's Name",
    sourcePath: 'applicant.family.spouse.name',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'spouse_nationality',
    label: "Spouse's Nationality",
    sourcePath: 'applicant.family.spouse.nationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'spouse_previous_nationality',
    label: "Spouse's Previous Nationality",
    sourcePath: 'applicant.family.spouse.previousNationality',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'spouse_place_of_birth',
    label: "Spouse's Place of Birth",
    sourcePath: 'applicant.family.spouse.placeOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'spouse_country_of_birth',
    label: "Spouse's Country of Birth",
    sourcePath: 'applicant.family.spouse.countryOfBirth',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'family-details',
    fieldId: 'has_pakistan_relation',
    label: 'Were your Parents/Grandparents Pakistan Nationals or belong to Pakistan held area?',
    sourcePath: 'applicant.family.hasPakistanRelation',
    dataSource: 'applicant_profile',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'family-details',
    fieldId: 'pakistan_relation_details',
    label: 'Details of Pakistan Relation',
    sourcePath: 'applicant.family.pakistanRelationDetails',
    dataSource: 'applicant_profile',
    fieldType: 'textarea',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_pakistan_relation is true',
  },

  // 4. VISA DETAILS PAGE
  {
    page: 'visa-details',
    fieldId: 'visa_type',
    label: 'Type of Visa Required',
    sourcePath: 'application.visaDetails.visaType',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'number_of_entries',
    label: 'Number of Entries',
    sourcePath: 'application.visaDetails.numberOfEntries',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'period_of_visa',
    label: 'Period of Visa (in months)',
    sourcePath: 'application.visaDetails.periodOfVisaMonths',
    dataSource: 'india_visa_application',
    fieldType: 'number',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'expected_date_of_journey',
    label: 'Expected Date of Journey',
    sourcePath: 'application.visaDetails.expectedDateOfJourney',
    dataSource: 'india_visa_application',
    fieldType: 'date',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'port_of_arrival',
    label: 'Port of Arrival',
    sourcePath: 'application.visaDetails.portOfArrival',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'port_of_exit',
    label: 'Port of Exit',
    sourcePath: 'application.visaDetails.portOfExit',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'visa-details',
    fieldId: 'places_to_be_visited',
    label: 'Places to be Visited',
    sourcePath: 'application.visaDetails.placesToBeVisited',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'visa-details',
    fieldId: 'purpose_of_visit',
    label: 'Purpose of Visit',
    sourcePath: 'application.visaDetails.purposeOfVisit',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },

  // 5. PREVIOUS VISIT DETAILS PAGE
  {
    page: 'previous-visit',
    fieldId: 'has_visited_india',
    label: 'Have you ever visited India before?',
    sourcePath: 'application.previousVisitDetails.hasVisitedIndia',
    dataSource: 'india_visa_application',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'previous-visit',
    fieldId: 'stay_address_in_india',
    label: 'Address where stayed in India',
    sourcePath: 'application.previousVisitDetails.stayAddressInIndia',
    dataSource: 'india_visa_application',
    fieldType: 'textarea',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'cities_visited_in_india',
    label: 'Cities in India Visited',
    sourcePath: 'application.previousVisitDetails.citiesVisitedInIndia',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'previous_visa_type',
    label: 'Previous Indian Visa Type',
    sourcePath: 'application.previousVisitDetails.previousVisaType',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'previous_visa_number',
    label: 'Previous Visa Number',
    sourcePath: 'application.previousVisitDetails.previousVisaNumber',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'previous_visa_issued_place',
    label: 'Previous Visa Issued Place',
    sourcePath: 'application.previousVisitDetails.previousVisaIssuedPlace',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'previous_visa_date_of_issue',
    label: 'Previous Visa Date of Issue',
    sourcePath: 'application.previousVisitDetails.previousVisaIssueDate',
    dataSource: 'india_visa_application',
    fieldType: 'date',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_visited_india is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'countries_visited_last_10_years',
    label: 'Countries Visited during Last 10 Years',
    sourcePath: 'application.previousVisitDetails.countriesVisitedLast10Years',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'optional',
  },
  {
    page: 'previous-visit',
    fieldId: 'has_been_refused_visa',
    label: 'Has Indian Visa ever been refused/rejected?',
    sourcePath: 'application.previousVisitDetails.hasBeenRefusedIndianVisa',
    dataSource: 'india_visa_application',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'previous-visit',
    fieldId: 'visa_refusal_details',
    label: 'Visa Refusal Details',
    sourcePath: 'application.previousVisitDetails.refusalDetails',
    dataSource: 'india_visa_application',
    fieldType: 'textarea',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_been_refused_visa is true',
  },
  {
    page: 'previous-visit',
    fieldId: 'has_been_deported',
    label: 'Have you ever been deported from India?',
    sourcePath: 'application.previousVisitDetails.hasBeenDeportedFromIndia',
    dataSource: 'india_visa_application',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'previous-visit',
    fieldId: 'deportation_details',
    label: 'Deportation Details',
    sourcePath: 'application.previousVisitDetails.deportationDetails',
    dataSource: 'india_visa_application',
    fieldType: 'textarea',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_been_deported is true',
  },

  // 6. PROFESSION / OCCUPATION PAGE
  {
    page: 'profession',
    fieldId: 'present_occupation',
    label: 'Present Occupation',
    sourcePath: 'applicant.employment.presentOccupation',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'designation_rank',
    label: 'Designation / Rank',
    sourcePath: 'applicant.employment.designationRank',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'employer_name',
    label: 'Employer Name / Business',
    sourcePath: 'applicant.employment.employerName',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'employer_address',
    label: 'Employer Address',
    sourcePath: 'applicant.employment.employerAddress',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'employer_phone',
    label: 'Employer Phone Number',
    sourcePath: 'applicant.employment.employerPhone',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'past_occupation',
    label: 'Past Occupation',
    sourcePath: 'applicant.employment.pastOccupation',
    dataSource: 'applicant_profile',
    fieldType: 'select',
    requirement: 'optional',
  },
  {
    page: 'profession',
    fieldId: 'has_military_service',
    label: 'Have you worked with Armed Forces / Police / Para-Military?',
    sourcePath: 'applicant.employment.hasMilitaryService',
    dataSource: 'applicant_profile',
    fieldType: 'radio',
    requirement: 'required',
  },
  {
    page: 'profession',
    fieldId: 'military_organization',
    label: 'Military/Police Organization Name',
    sourcePath: 'applicant.employment.militaryOrganization',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_military_service is true',
  },
  {
    page: 'profession',
    fieldId: 'military_designation',
    label: 'Military/Police Designation',
    sourcePath: 'applicant.employment.militaryDesignation',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_military_service is true',
  },
  {
    page: 'profession',
    fieldId: 'military_place_of_posting',
    label: 'Military/Police Place of Posting',
    sourcePath: 'applicant.employment.militaryPlaceOfPosting',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_military_service is true',
  },
  {
    page: 'profession',
    fieldId: 'military_rank',
    label: 'Military/Police Rank',
    sourcePath: 'applicant.employment.militaryRank',
    dataSource: 'applicant_profile',
    fieldType: 'text',
    requirement: 'conditional',
    conditionallyDisplayed: true,
    conditionDescription: 'Required if has_military_service is true',
  },

  // 7. ACCOMMODATION / PLACE OF STAY PAGE
  {
    page: 'accommodation',
    fieldId: 'acc_hotel_name',
    label: 'Place / Hotel Name',
    sourcePath: 'application.accommodations[0].placeHotelName',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
    notes: 'Supports array of AccommodationDetails entries',
  },
  {
    page: 'accommodation',
    fieldId: 'acc_address',
    label: 'Accommodation Address',
    sourcePath: 'application.accommodations[0].address',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'accommodation',
    fieldId: 'acc_state',
    label: 'Accommodation State',
    sourcePath: 'application.accommodations[0].state',
    dataSource: 'india_visa_application',
    fieldType: 'select',
    requirement: 'required',
  },
  {
    page: 'accommodation',
    fieldId: 'acc_phone',
    label: 'Accommodation Phone Number',
    sourcePath: 'application.accommodations[0].phone',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },

  // 8. REFERENCES PAGE
  {
    page: 'references',
    fieldId: 'ref_india_name',
    label: 'India Reference Name',
    sourcePath: 'application.references.india.name',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'references',
    fieldId: 'ref_india_address',
    label: 'India Reference Address',
    sourcePath: 'application.references.india.address',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'references',
    fieldId: 'ref_india_phone',
    label: 'India Reference Phone',
    sourcePath: 'application.references.india.phone',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'references',
    fieldId: 'ref_bangladesh_name',
    label: 'Home Country / Bangladesh Reference Name',
    sourcePath: 'application.references.bangladesh.name',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'references',
    fieldId: 'ref_bangladesh_address',
    label: 'Home Country / Bangladesh Reference Address',
    sourcePath: 'application.references.bangladesh.address',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'references',
    fieldId: 'ref_bangladesh_phone',
    label: 'Home Country / Bangladesh Reference Phone',
    sourcePath: 'application.references.bangladesh.phone',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },

  // 9. DOCUMENTS PAGE
  {
    page: 'documents',
    fieldId: 'doc_passport',
    label: 'Passport Copy Document Upload',
    sourcePath: 'application.documents[0]',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
    notes: 'Document metadata entry (Id, Type, Name, UploadedAt)',
  },
  {
    page: 'documents',
    fieldId: 'doc_photo',
    label: 'Applicant Photo Upload',
    sourcePath: 'application.documents[1]',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'required',
  },
  {
    page: 'documents',
    fieldId: 'doc_supporting',
    label: 'Supporting Documents Upload',
    sourcePath: 'application.documents[2]',
    dataSource: 'india_visa_application',
    fieldType: 'text',
    requirement: 'optional',
  },

  // 10. DECLARATION PAGE
  {
    page: 'declaration',
    fieldId: 'dec_agreed',
    label: 'Application Declaration Agreement',
    sourcePath: 'application.declaration.isDeclared',
    dataSource: 'india_visa_application',
    fieldType: 'checkbox',
    requirement: 'required',
  },
  {
    page: 'declaration',
    fieldId: 'dec_date',
    label: 'Declaration Date',
    sourcePath: 'application.declaration.declarationDate',
    dataSource: 'india_visa_application',
    fieldType: 'date',
    requirement: 'required',
  },
]
