import type { CanonicalIndiaVisaPage } from '../../types'
import type { IndiaFieldSelector } from '../../mapping.types'
import { BANGLADESH_REGISTRATION_SELECTORS } from './registration'
import { BANGLADESH_BASIC_DETAILS_SELECTORS } from './basicDetails'
import { BANGLADESH_FAMILY_DETAILS_SELECTORS } from './familyDetails'
import { BANGLADESH_VISA_DETAILS_SELECTORS } from './visaDetails'
import { BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS } from './additionalQuestions'
import { BANGLADESH_PHOTO_UPLOAD_SELECTORS } from './photoUpload'

export type BangladeshControlCategory =
  | 'verified-selector'
  | 'unverified-selector'
  | 'technical-control'
  | 'security-control'

export type BangladeshAutofillEligibility =
  | 'autofillable'
  | 'manual-only'
  | 'technical-ignored'

export interface BangladeshRegisteredControl {
  controlId: string
  page: CanonicalIndiaVisaPage
  category: BangladeshControlCategory
  eligibility: BangladeshAutofillEligibility
  selectors: IndiaFieldSelector[]
  description: string
}

export const BANGLADESH_FIELD_REGISTRY: BangladeshRegisteredControl[] = [
  // --- Page 1: REGISTRATION ---
  {
    controlId: 'reg_countryname',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.applyingFromCountry,
    description: 'Country applying visa from (#countryname_id)',
  },
  {
    controlId: 'reg_missioncode',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.indianMission,
    description: 'Indian Mission in Bangladesh (#missioncode_id)',
  },
  {
    controlId: 'reg_nationality',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.nationality,
    description: 'Applicant Nationality (#nationality_id)',
  },
  {
    controlId: 'reg_dob',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.dateOfBirth,
    description: 'Date of Birth (#dob_id)',
  },
  {
    controlId: 'reg_email',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.email,
    description: 'Email address (#email_id)',
  },
  {
    controlId: 'reg_email_re',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.emailConfirm,
    description: 'Email address confirmation (#email_re_id)',
  },
  {
    controlId: 'reg_journeydate',
    page: 'REGISTRATION',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.expectedArrivalDate,
    description: 'Expected Date of Arrival (#jouryney_id)',
  },
  {
    controlId: 'reg_captcha',
    page: 'REGISTRATION',
    category: 'security-control',
    eligibility: 'manual-only',
    selectors: BANGLADESH_REGISTRATION_SELECTORS.captcha,
    description: 'CAPTCHA Security Verification (#captcha) - strictly manual',
  },

  // --- Page 2: BASIC_DETAILS ---
  {
    controlId: 'basic_surname',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.surname,
    description: 'Surname (#surname)',
  },
  {
    controlId: 'basic_given_name',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.givenName,
    description: 'Given Name (#givenName)',
  },
  {
    controlId: 'basic_changed_surname_check',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.changedSurnameCheck,
    description: 'Changed Surname checkbox (#changedSurnameCheck)',
  },
  {
    controlId: 'basic_gender',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.gender,
    description: 'Gender (#gender)',
  },
  {
    controlId: 'basic_birth_place',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.townCityOfBirth,
    description: 'Town/City of Birth (#birth_place)',
  },
  {
    controlId: 'basic_country_birth',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.countryOfBirth,
    description: 'Country of Birth (#country_birth)',
  },
  {
    controlId: 'basic_nic_number',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalIdNumber,
    description: 'National ID / NIC Number (#nic_number)',
  },
  {
    controlId: 'basic_religion',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.religion,
    description: 'Religion (#religion)',
  },
  {
    controlId: 'basic_identity_marks',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.visibleIdentificationMarks,
    description: 'Visible Identification Marks (#identity_marks)',
  },
  {
    controlId: 'basic_education',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.educationalQualification,
    description: 'Educational Qualification (#education)',
  },
  {
    controlId: 'basic_nationality_by',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalityBy,
    description: 'Nationality by Birth/Naturalization (#nationality_by)',
  },
  {
    controlId: 'basic_nationality',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.nationality,
    description: 'Nationality (#nationality)',
  },
  {
    controlId: 'basic_dob',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.dateOfBirth,
    description: 'Date of Birth (#dob)',
  },
  {
    controlId: 'basic_passport_no',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.passportNumber,
    description: 'Passport Number (#passport_no)',
  },
  {
    controlId: 'basic_passport_issue_place',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.placeOfIssue,
    description: 'Passport Place of Issue (#passport_issue_place)',
  },
  {
    controlId: 'basic_passport_issue_date',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.issueDate,
    description: 'Passport Issue Date (#passport_issue_date)',
  },
  {
    controlId: 'basic_passport_expiry_date',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.expiryDate,
    description: 'Passport Expiry Date (#passport_expiry_date)',
  },
  {
    controlId: 'basic_other_ppt_flag',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportFlag,
    description: 'Holds other passport flag (#other_ppt_1, #other_ppt_2)',
  },
  {
    controlId: 'basic_other_ppt_no',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNumber,
    description: 'Other Passport Number (#other_ppt_no)',
  },
  {
    controlId: 'basic_other_ppt_issue_place',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportPlaceOfIssue,
    description: 'Other Passport Place of Issue (#other_ppt_issue_place)',
  },
  {
    controlId: 'basic_other_ppt_country_issue',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportCountryOfIssue,
    description: 'Other Passport Country of Issue (#other_ppt_country_issue)',
  },
  {
    controlId: 'basic_other_ppt_nat',
    page: 'BASIC_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNationality,
    description: 'Other Passport Nationality (#other_ppt_nat)',
  },

  // --- Page 3: FAMILY_DETAILS ---
  {
    controlId: 'family_pres_add1',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress1,
    description: 'Present Address Line 1 (#pres_add1)',
  },
  {
    controlId: 'family_pres_add2',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress2,
    description: 'Present Address Line 2 (#pres_add2)',
  },
  {
    controlId: 'family_pres_add3',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentStateCity,
    description: 'Present City/State (#pres_add3)',
  },
  {
    controlId: 'family_pincode',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPostalCode,
    description: 'Postal/Pincode (#pincode)',
  },
  {
    controlId: 'family_pres_phone',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPhone,
    description: 'Present Phone Number (#pres_phone)',
  },
  {
    controlId: 'family_mobile',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.mobile,
    description: 'Mobile Number (#mobile)',
  },
  {
    controlId: 'family_same_address',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.sameAddress,
    description: 'Same Address Flag (#sameAddress_id)',
  },
  {
    controlId: 'family_perm_add1',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress1,
    description: 'Permanent Address Line 1 (#perm_address1)',
  },
  {
    controlId: 'family_perm_add2',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress2,
    description: 'Permanent Address Line 2 (#perm_address2)',
  },
  {
    controlId: 'family_perm_add3',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentStateCity,
    description: 'Permanent City/State (#perm_address3)',
  },
  {
    controlId: 'family_fthrname',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherName,
    description: "Father's Full Name (#fthrname)",
  },
  {
    controlId: 'family_father_birth_place',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherPlaceOfBirth,
    description: "Father's Place of Birth (#father_place_of_birth)",
  },
  {
    controlId: 'family_father_country_birth',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherCountryOfBirth,
    description: "Father's Country of Birth (#father_country_of_birth)",
  },
  {
    controlId: 'family_father_nat',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherNationality,
    description: "Father's Nationality (#father_nationality)",
  },
  {
    controlId: 'family_mother_name',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherName,
    description: "Mother's Full Name (#mother_name)",
  },
  {
    controlId: 'family_mother_birth_place',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherPlaceOfBirth,
    description: "Mother's Place of Birth (#mother_place_of_birth)",
  },
  {
    controlId: 'family_mother_country_birth',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherCountryOfBirth,
    description: "Mother's Country of Birth (#mother_country_of_birth)",
  },
  {
    controlId: 'family_mother_nat',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherNationality,
    description: "Mother's Nationality (#mother_nationality)",
  },
  {
    controlId: 'family_marital_status',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.maritalStatus,
    description: 'Marital Status (#marital_status)',
  },
  {
    controlId: 'family_grandparent_flag',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.grandparentFlag,
    description: 'Grandparent Pakistan/Origin Flag (#grandparent_flag1, #grandparent_flag2)',
  },
  {
    controlId: 'family_grandparent_details',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.grandparentDetails,
    description: 'Grandparent Details (#grandparent_details)',
  },
  {
    controlId: 'family_occupation',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.occupation,
    description: 'Present Occupation (#occupation)',
  },
  {
    controlId: 'family_empname',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerName,
    description: 'Employer/Business Name (#empname)',
  },
  {
    controlId: 'family_empdesignation',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerDesignation,
    description: 'Employer Designation (#empdesignation)',
  },
  {
    controlId: 'family_empaddress',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerAddress,
    description: 'Employer Address (#empaddress)',
  },
  {
    controlId: 'family_empphone',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerPhone,
    description: 'Employer Phone (#empphone)',
  },
  {
    controlId: 'family_prev_occupation',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOccupation,
    description: 'Previous Occupation (#previous_occupation)',
  },
  {
    controlId: 'family_prev_org_flag',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOrgFlag,
    description: 'Previous Military/Security Flag (#prev_org1, #prev_org2)',
  },
  {
    controlId: 'family_prev_org_name',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOrganization,
    description: 'Previous Organization (#previous_organization)',
  },
  {
    controlId: 'family_prev_desig',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousDesignation,
    description: 'Previous Designation (#previous_designation)',
  },
  {
    controlId: 'family_prev_rank',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousRank,
    description: 'Previous Rank (#previous_rank)',
  },
  {
    controlId: 'family_prev_posting',
    page: 'FAMILY_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousPosting,
    description: 'Previous Posting (#previous_posting)',
  },

  // --- Page 4: TRAVEL_DETAILS (Visa Details) ---
  {
    controlId: 'visa_duration',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.duration,
    description: 'Visa Duration (#duration)',
  },
  {
    controlId: 'visa_entry_id',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.visaEntryType,
    description: 'Visa Entry Type (#visa_entry_id)',
  },
  {
    controlId: 'visa_journeydate',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.expectedArrivalDate,
    description: 'Expected Arrival Date (#jouryney_id)',
  },
  {
    controlId: 'visa_entrypoint',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.entryPoint,
    description: 'Port of Arrival (#entrypoint)',
  },
  {
    controlId: 'visa_exitpoint',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.exitPoint,
    description: 'Port of Exit (#exitpointprc)',
  },
  {
    controlId: 'visa_old_visa_flag',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaFlag,
    description: 'Previous Indian Visa Flag (#old_visa_flag1, #old_visa_flag2)',
  },
  {
    controlId: 'visa_prv_visit_add1',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress1,
    description: 'Previous Visit Address 1 (#prv_visit_add1)',
  },
  {
    controlId: 'visa_prv_visit_add2',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress2,
    description: 'Previous Visit Address 2 (#prv_visit_add2)',
  },
  {
    controlId: 'visa_prv_visit_add3',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress3,
    description: 'Previous Visit Address 3 (#prv_visit_add3)',
  },
  {
    controlId: 'visa_old_visa_no',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaNumber,
    description: 'Old Visa Number (#old_visa_no)',
  },
  {
    controlId: 'visa_old_visa_type',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaType,
    description: 'Old Visa Type (#old_visa_type_id)',
  },
  {
    controlId: 'visa_old_visa_place',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaIssuePlace,
    description: 'Old Visa Issue Place (#oldvisaissueplace)',
  },
  {
    controlId: 'visa_old_visa_date',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaIssueDate,
    description: 'Old Visa Issue Date (#oldvisaissuedate)',
  },
  {
    controlId: 'visa_refuse_flag',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.refuseFlag,
    description: 'Visa Refusal Flag (#refuse_flag1, #refuse_flag2)',
  },
  {
    controlId: 'visa_refuse_details',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.refuseDetails,
    description: 'Visa Refusal Details (#refuse_details)',
  },
  {
    controlId: 'visa_country_visited',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.countryVisited,
    description: 'Countries Visited (#country_visited)',
  },
  {
    controlId: 'visa_saarc_flag',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.saarcFlag,
    description: 'SAARC Countries Visited Flag (#saarc_flag1, #saarc_flag2)',
  },
  {
    controlId: 'visa_sponsor_ind_name',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaName,
    description: 'Sponsor in India Name (#nameofsponsor_ind)',
  },
  {
    controlId: 'visa_sponsor_ind_add1',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaAddress1,
    description: 'Sponsor in India Address Line 1 (#add1ofsponsor_ind)',
  },
  {
    controlId: 'visa_sponsor_ind_add2',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaAddress2,
    description: 'Sponsor in India Address Line 2 (#add2ofsponsor_ind)',
  },
  {
    controlId: 'visa_sponsor_ind_phone',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaPhone,
    description: 'Sponsor in India Phone (#phoneofsponsor_ind)',
  },
  {
    controlId: 'visa_sponsor_msn_name',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionName,
    description: 'Reference in Home/Mission Country Name (#nameofsponsor_msn)',
  },
  {
    controlId: 'visa_sponsor_msn_add1',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionAddress1,
    description: 'Reference in Home/Mission Country Address Line 1 (#add1ofsponsor_msn)',
  },
  {
    controlId: 'visa_sponsor_msn_add2',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionAddress2,
    description: 'Reference in Home/Mission Country Address Line 2 (#add2ofsponsor_msn)',
  },
  {
    controlId: 'visa_sponsor_msn_phone',
    page: 'TRAVEL_DETAILS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionPhone,
    description: 'Reference in Home/Mission Country Phone (#phoneofsponsor_msn)',
  },
  {
    controlId: 'visa_btn_continue',
    page: 'TRAVEL_DETAILS',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.submitContinue,
    description: 'Submit/Continue Button (#continue) - never auto-clicked',
  },
  {
    controlId: 'visa_btn_exit',
    page: 'TRAVEL_DETAILS',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_VISA_DETAILS_SELECTORS.submitExit,
    description: 'Exit Button (#exit) - never auto-clicked',
  },

  // --- Page 5: ADDITIONAL_QUESTIONS ---
  {
    controlId: 'q_1_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question1Yes,
    description: 'Question 1 Yes (#question_yes_1)',
  },
  {
    controlId: 'q_1_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question1No,
    description: 'Question 1 No (#question_no_1)',
  },
  {
    controlId: 'q_1_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer1,
    description: 'Question 1 Details (#answer_1)',
  },
  {
    controlId: 'q_2_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question2Yes,
    description: 'Question 2 Yes (#question_yes_2)',
  },
  {
    controlId: 'q_2_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question2No,
    description: 'Question 2 No (#question_no_2)',
  },
  {
    controlId: 'q_2_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer2,
    description: 'Question 2 Details (#answer_2)',
  },
  {
    controlId: 'q_3_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question3Yes,
    description: 'Question 3 Yes (#question_yes_3)',
  },
  {
    controlId: 'q_3_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question3No,
    description: 'Question 3 No (#question_no_3)',
  },
  {
    controlId: 'q_3_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer3,
    description: 'Question 3 Details (#answer_3)',
  },
  {
    controlId: 'q_4_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question4Yes,
    description: 'Question 4 Yes (#question_yes_4)',
  },
  {
    controlId: 'q_4_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question4No,
    description: 'Question 4 No (#question_no_4)',
  },
  {
    controlId: 'q_4_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer4,
    description: 'Question 4 Details (#answer_4)',
  },
  {
    controlId: 'q_5_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question5Yes,
    description: 'Question 5 Yes (#question_yes_5)',
  },
  {
    controlId: 'q_5_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question5No,
    description: 'Question 5 No (#question_no_5)',
  },
  {
    controlId: 'q_5_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer5,
    description: 'Question 5 Details (#answer_5)',
  },
  {
    controlId: 'q_6_yes',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question6Yes,
    description: 'Question 6 Yes (#question_yes_6)',
  },
  {
    controlId: 'q_6_no',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.question6No,
    description: 'Question 6 No (#question_no_6)',
  },
  {
    controlId: 'q_6_ans',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'verified-selector',
    eligibility: 'autofillable',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.answer6,
    description: 'Question 6 Details (#answer_6)',
  },
  {
    controlId: 'q_declaration',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'security-control',
    eligibility: 'manual-only',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.declarationCheckbox,
    description: 'Declaration Checkbox (#verifyQuestions) - manual user confirmation',
  },
  {
    controlId: 'q_btn_continue',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.submitContinue,
    description: 'Submit/Continue Button (#continue)',
  },
  {
    controlId: 'q_btn_exit',
    page: 'ADDITIONAL_QUESTIONS',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_ADDITIONAL_QUESTIONS_SELECTORS.submitExit,
    description: 'Exit Button (#exit)',
  },

  // --- Page 6: DOCUMENT_UPLOAD (Photo Upload) ---
  {
    controlId: 'photo_file_upload',
    page: 'DOCUMENT_UPLOAD',
    category: 'verified-selector',
    eligibility: 'manual-only',
    selectors: BANGLADESH_PHOTO_UPLOAD_SELECTORS.photoFile,
    description: 'Photo File Upload (#photo) - manual upload only',
  },
  {
    controlId: 'photo_upload_btn',
    page: 'DOCUMENT_UPLOAD',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_PHOTO_UPLOAD_SELECTORS.uploadButton,
    description: 'Upload Button (#upload)',
  },
  {
    controlId: 'photo_btn_continue',
    page: 'DOCUMENT_UPLOAD',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_PHOTO_UPLOAD_SELECTORS.submitContinue,
    description: 'Submit/Continue Button (#continue)',
  },
  {
    controlId: 'photo_btn_exit',
    page: 'DOCUMENT_UPLOAD',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    selectors: BANGLADESH_PHOTO_UPLOAD_SELECTORS.submitExit,
    description: 'Exit Button (#exit)',
  },
]

/**
 * Returns registered controls for a canonical page.
 */
export function getBangladeshPageControls(page: CanonicalIndiaVisaPage): BangladeshRegisteredControl[] {
  return BANGLADESH_FIELD_REGISTRY.filter((c) => c.page === page)
}

/**
 * Returns total count of verified Bangladesh selectors.
 */
export function getBangladeshVerifiedFieldsCount(): number {
  return BANGLADESH_FIELD_REGISTRY.filter((c) => c.category === 'verified-selector').length
}

/**
 * Returns total count of autofillable controls.
 */
export function getBangladeshAutofillableFieldsCount(): number {
  return BANGLADESH_FIELD_REGISTRY.filter((c) => c.eligibility === 'autofillable').length
}

/**
 * Returns total count of manual/security controls.
 */
export function getBangladeshManualControlsCount(): number {
  return BANGLADESH_FIELD_REGISTRY.filter((c) => c.eligibility === 'manual-only').length
}

/**
 * Returns total count of technical controls.
 */
export function getBangladeshTechnicalControlsCount(): number {
  return BANGLADESH_FIELD_REGISTRY.filter((c) => c.eligibility === 'technical-ignored').length
}
