import type { CanonicalIndiaVisaPage } from './types'
import type { BangladeshAutofillEligibility, BangladeshControlCategory } from './selectors/bangladesh/registry'
import type { ApplicantProfileFieldPath } from './mapping.types'

export type ExtractionCoverageCategory =
  | 'A_SUPPORTED'                   // Currently extracted from standard Passport MRZ / text
  | 'B_DOCUMENT_TYPE_DEPENDENT'     // Extracted from visual zone / specific document types
  | 'C_NOT_EXTRACTABLE'             // Not part of passport or standard identity document
  | 'D_LEAVE_EMPTY_SOURCE_ABSENT'   // Normal field: skip without mutation when document lacks data
  | 'E_FUTURE_DOCUMENT_SOURCE'      // Requires future travel itinerary / invitation / visa document extractor
  | 'SECURITY_MANUAL'               // Security gates (e.g., CAPTCHA)
  | 'TECHNICAL_IGNORED'             // Buttons / technical action elements

export interface FieldCoverageEntry {
  controlId: string
  page: CanonicalIndiaVisaPage
  portalFieldName: string
  domSelector: string
  category: BangladeshControlCategory
  eligibility: BangladeshAutofillEligibility
  isExtractedByCurrentPdf: boolean
  extractedSource: string | null
  applicantFieldPath: ApplicantProfileFieldPath | null
  coverageCategory: ExtractionCoverageCategory
  transform: string | null
  notes: string
}

export const BANGLADESH_PORTAL_COVERAGE_MATRIX: FieldCoverageEntry[] = [
  // ==========================================
  // PAGE 1: REGISTRATION (/visa/Registration)
  // ==========================================
  {
    controlId: 'reg_countryname',
    page: 'REGISTRATION',
    portalFieldName: 'appl.countryname',
    domSelector: '#countryname_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'presentAddress.country',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Country applying from. Not encoded in passport MRZ. Safely skipped if missing.',
  },
  {
    controlId: 'reg_missioncode',
    page: 'REGISTRATION',
    portalFieldName: 'appl.missioncode',
    domSelector: '#missioncode_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'registration.indianMission',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Indian Mission in Bangladesh. Derived if present in notes or applicant present address city.',
  },
  {
    controlId: 'reg_nationality',
    page: 'REGISTRATION',
    portalFieldName: 'appl.nationality',
    domSelector: '#nationality_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) nationality (e.g. BGD)',
    applicantFieldPath: 'personalInfo.nationality',
    coverageCategory: 'A_SUPPORTED',
    transform: 'selectOptionMatch',
    notes: 'Applicant nationality. Directly provided by passport MRZ with high confidence (95).',
  },
  {
    controlId: 'reg_dob',
    page: 'REGISTRATION',
    portalFieldName: 'appl.birthdate',
    domSelector: '#dob_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) dateOfBirth / PDF text regex',
    applicantFieldPath: 'personalInfo.dateOfBirth',
    coverageCategory: 'A_SUPPORTED',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Applicant date of birth. Normalized to DD/MM/YYYY for portal input.',
  },
  {
    controlId: 'reg_email',
    page: 'REGISTRATION',
    portalFieldName: 'appl.email',
    domSelector: '#email_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text regex / OCR text pattern',
    applicantFieldPath: 'contact.email',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'lowercase',
    notes: 'Applicant email address. Extracted when present on visa application / biodata sheet.',
  },
  {
    controlId: 'reg_email_re',
    page: 'REGISTRATION',
    portalFieldName: 'appl.email_re',
    domSelector: '#email_re_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text regex / OCR text pattern',
    applicantFieldPath: 'contact.email',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'lowercase',
    notes: 'Applicant email address confirmation. Mirrors primary email.',
  },
  {
    controlId: 'reg_journeydate',
    page: 'REGISTRATION',
    portalFieldName: 'appl.journeydate',
    domSelector: '#jouryney_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'travel.intendedArrivalDate',
    coverageCategory: 'E_FUTURE_DOCUMENT_SOURCE',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Expected date of arrival. Requires travel ticket / itinerary document.',
  },
  {
    controlId: 'reg_captcha',
    page: 'REGISTRATION',
    portalFieldName: 'captcha',
    domSelector: '#captcha',
    category: 'security-control',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'CAPTCHA security verification. Strictly manual-required. Never automated.',
  },

  // ==========================================
  // PAGE 2: BASIC DETAILS (/visa/BasicDetails)
  // ==========================================
  {
    controlId: 'basic_surname',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.surname',
    domSelector: '#surname',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) surname',
    applicantFieldPath: 'personalInfo.surname',
    coverageCategory: 'A_SUPPORTED',
    transform: 'uppercase',
    notes: 'Surname from passport MRZ.',
  },
  {
    controlId: 'basic_given_name',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.applname',
    domSelector: '#givenName',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) givenNames',
    applicantFieldPath: 'personalInfo.givenNames',
    coverageCategory: 'A_SUPPORTED',
    transform: 'uppercase',
    notes: 'Given name(s) from passport MRZ.',
  },
  {
    controlId: 'basic_changed_surname_check',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.changedSurnameCheck',
    domSelector: '#changedSurnameCheck',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Previous name check. Left untouched when source data absent.',
  },
  {
    controlId: 'basic_gender',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.applsex',
    domSelector: '#gender',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) sex (M/F/<)',
    applicantFieldPath: 'personalInfo.gender',
    coverageCategory: 'A_SUPPORTED',
    transform: 'selectOptionMatch',
    notes: 'Gender mapped to MALE / FEMALE options in DOM select.',
  },
  {
    controlId: 'basic_birth_place',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.placbrth',
    domSelector: '#birth_place',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: 'Visual zone / OCR text',
    applicantFieldPath: 'personalInfo.townCityOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Town/City of Birth. Extracted when visual zone OCR is available.',
  },
  {
    controlId: 'basic_country_birth',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.country_of_birth',
    domSelector: '#country_birth',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: 'Visual zone / OCR text',
    applicantFieldPath: 'personalInfo.countryOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Country of Birth.',
  },
  {
    controlId: 'basic_nic_number',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.nic_no',
    domSelector: '#nic_number',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: 'MRZ optional data / National ID PDF',
    applicantFieldPath: 'personalInfo.nationalIdNumber',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'National ID / NIC Number.',
  },
  {
    controlId: 'basic_religion',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.religion',
    domSelector: '#religion',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'personalInfo.religion',
    coverageCategory: 'C_NOT_EXTRACTABLE',
    transform: 'selectOptionMatch',
    notes: 'Religion is not printed on standard passports. Left untouched.',
  },
  {
    controlId: 'basic_identity_marks',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.visual_mark',
    domSelector: '#identity_marks',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'personalInfo.visibleIdentificationMarks',
    coverageCategory: 'C_NOT_EXTRACTABLE',
    transform: null,
    notes: 'Visible identification marks. Left untouched when source absent.',
  },
  {
    controlId: 'basic_education',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.edu_id',
    domSelector: '#education',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'personalInfo.educationalQualification',
    coverageCategory: 'C_NOT_EXTRACTABLE',
    transform: 'selectOptionMatch',
    notes: 'Educational qualification. Left untouched when source absent.',
  },
  {
    controlId: 'basic_nationality_by',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.nationality_by',
    domSelector: '#nationality_by',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'personalInfo.nationalityAcquiredBy',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Nationality acquired by Birth / Naturalization.',
  },
  {
    controlId: 'basic_passport_no',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.passport_number',
    domSelector: '#passport_no',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) passportNumber / PDF text regex',
    applicantFieldPath: 'passport.passportNumber',
    coverageCategory: 'A_SUPPORTED',
    transform: 'uppercase',
    notes: 'Passport number verified with checksum.',
  },
  {
    controlId: 'basic_passport_issue_place',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.passport_issue_place',
    domSelector: '#passport_issue_place',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: 'Visual zone / OCR text',
    applicantFieldPath: 'passport.placeOfIssue',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Passport place of issue.',
  },
  {
    controlId: 'basic_passport_issue_date',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.passport_issue_date',
    domSelector: '#passport_issue_date',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: 'Visual zone / OCR text',
    applicantFieldPath: 'passport.issueDate',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Passport issue date.',
  },
  {
    controlId: 'basic_passport_expiry_date',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.passport_expiry_date',
    domSelector: '#passport_expiry_date',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'MRZ (TD3) passportExpiryDate',
    applicantFieldPath: 'passport.expiryDate',
    coverageCategory: 'A_SUPPORTED',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Passport expiry date.',
  },
  {
    controlId: 'basic_other_ppt_flag',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.oth_ppt',
    domSelector: '#other_ppt_1, #other_ppt_2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'passport.holdsOtherPassport',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Other passport holding radio buttons.',
  },
  {
    controlId: 'basic_other_ppt_no',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.oth_pptno',
    domSelector: '#other_ppt_no',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'passport.otherPassportDetails.passportNumber',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'uppercase',
    notes: 'Other passport number.',
  },
  {
    controlId: 'basic_other_ppt_issue_place',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.other_ppt_issue_place',
    domSelector: '#other_ppt_issue_place',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'passport.otherPassportDetails.placeOfIssue',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'uppercase',
    notes: 'Other passport place of issue.',
  },
  {
    controlId: 'basic_other_ppt_country_issue',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.prev_passport_country_issue',
    domSelector: '#other_ppt_country_issue',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'passport.otherPassportDetails.countryOfIssue',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Other passport country of issue.',
  },
  {
    controlId: 'basic_other_ppt_nat',
    page: 'BASIC_DETAILS',
    portalFieldName: 'appl.other_ppt_nationality',
    domSelector: '#other_ppt_nat',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'passport.otherPassportDetails.nationalityInPassport',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Other passport nationality.',
  },

  // ==========================================
  // PAGE 3: FAMILY DETAILS (/visa/FamilyDetails)
  // ==========================================
  {
    controlId: 'family_pres_add1',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.pres_add1',
    domSelector: '#pres_add1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'presentAddress.addressLine1',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Present Address Line 1.',
  },
  {
    controlId: 'family_pres_add2',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.pres_add2',
    domSelector: '#pres_add2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'presentAddress.addressLine2',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Present Address Line 2.',
  },
  {
    controlId: 'family_pres_add3',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.state_name',
    domSelector: '#pres_add3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'presentAddress.villageTownCity',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Present City/State.',
  },
  {
    controlId: 'family_pincode',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.pincode',
    domSelector: '#pincode',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'presentAddress.postalCode',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Postal/Pincode.',
  },
  {
    controlId: 'family_pres_phone',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.pres_phone',
    domSelector: '#pres_phone',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'contact.phone',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Present Phone Number.',
  },
  {
    controlId: 'family_mobile',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mobile',
    domSelector: '#mobile',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text regex',
    applicantFieldPath: 'contact.mobile',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Mobile Number.',
  },
  {
    controlId: 'family_same_address',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'sameAddress',
    domSelector: '#sameAddress_id',
    category: 'security-control',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'Same Address Flag (#sameAddress_id) - strictly manual user choice, never automated.',
  },
  {
    controlId: 'family_perm_add1',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.perm_add1',
    domSelector: '#perm_address1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'permanentAddress.addressLine1',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Permanent Address Line 1.',
  },
  {
    controlId: 'family_perm_add2',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.perm_add2',
    domSelector: '#perm_address2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'permanentAddress.addressLine2',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Permanent Address Line 2.',
  },
  {
    controlId: 'family_perm_add3',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.perm_add3',
    domSelector: '#perm_address3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'permanentAddress.villageTownCity',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Permanent City/State.',
  },
  {
    controlId: 'family_fthrname',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.fthrname',
    domSelector: '#fthrname',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.father.name',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Father's Full Name.",
  },
  {
    controlId: 'family_father_birth_place',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.father_place_of_birth',
    domSelector: '#father_place_of_birth',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.father.placeOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Father's Place of Birth.",
  },
  {
    controlId: 'family_father_country_birth',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.father_country_of_birth',
    domSelector: '#father_country_of_birth',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.father.countryOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Father's Country of Birth.",
  },
  {
    controlId: 'family_father_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.father_nationality',
    domSelector: '#father_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.father.nationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Father's Nationality.",
  },
  {
    controlId: 'family_father_prev_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.father_prev_nationality',
    domSelector: '#father_prev_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.father.previousNationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Father's Previous Nationality.",
  },
  {
    controlId: 'family_mother_name',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mother_name',
    domSelector: '#mother_name',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.mother.name',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Mother's Full Name.",
  },
  {
    controlId: 'family_mother_birth_place',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mother_place_of_birth',
    domSelector: '#mother_place_of_birth',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.mother.placeOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Mother's Place of Birth.",
  },
  {
    controlId: 'family_mother_country_birth',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mother_country_of_birth',
    domSelector: '#mother_country_of_birth',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.mother.countryOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Mother's Country of Birth.",
  },
  {
    controlId: 'family_mother_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mother_nationality',
    domSelector: '#mother_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.mother.nationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Mother's Nationality.",
  },
  {
    controlId: 'family_mother_prev_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.mother_prev_nationality',
    domSelector: '#mother_prev_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.mother.previousNationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Mother's Previous Nationality.",
  },
  {
    controlId: 'family_marital_status',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.marital_status',
    domSelector: '#marital_status',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'personalInfo.maritalStatus',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Marital Status.',
  },
  {
    controlId: 'family_spouse_name',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.spouse_name',
    domSelector: '#spouse_name',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.spouse.name',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Spouse's Full Name.",
  },
  {
    controlId: 'family_spouse_birth_place',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.spouse_place_of_birth',
    domSelector: '#spouse_birth_place',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.spouse.placeOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: "Spouse's Place of Birth.",
  },
  {
    controlId: 'family_spouse_country_birth',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.spouse_country_of_birth',
    domSelector: '#spouse_birth_country',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.spouse.countryOfBirth',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Spouse's Country of Birth.",
  },
  {
    controlId: 'family_spouse_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.spouse_nationality',
    domSelector: '#spouse_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.spouse.nationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Spouse's Nationality.",
  },
  {
    controlId: 'family_spouse_prev_nat',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.spouse_prev_nationality',
    domSelector: '#spouse_prev_nationality',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'family.spouse.previousNationality',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: "Spouse's Previous Nationality.",
  },
  {
    controlId: 'family_grandparent_flag',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.grandparent_flag',
    domSelector: '#grandparent_flag1, #grandparent_flag2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'family.hasPakistanRelation',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Grandparent Pakistan/Origin Flag.',
  },
  {
    controlId: 'family_grandparent_details',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.grandparent_details',
    domSelector: '#grandparent_details',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'family.pakistanRelationDetails',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Grandparent Details.',
  },
  {
    controlId: 'family_occupation',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.occupation',
    domSelector: '#occupation',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.presentOccupation',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Present Occupation.',
  },
  {
    controlId: 'family_empname',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.empname',
    domSelector: '#empname',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.employerName',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Employer/Business Name.',
  },
  {
    controlId: 'family_empdesignation',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.empdesignation',
    domSelector: '#empdesignation',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.designationRank',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Employer Designation.',
  },
  {
    controlId: 'family_empaddress',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.empaddress',
    domSelector: '#empaddress',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.employerAddress',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Employer Address.',
  },
  {
    controlId: 'family_empphone',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.empphone',
    domSelector: '#empphone',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.employerPhone',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Employer Phone.',
  },
  {
    controlId: 'family_prev_occupation',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.previous_occupation',
    domSelector: '#previous_occupation',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'employment.pastOccupation',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: 'selectOptionMatch',
    notes: 'Previous Occupation.',
  },
  {
    controlId: 'family_prev_org_flag',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.prev_org',
    domSelector: '#prev_org1, #prev_org2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: 'employment.hasMilitaryService',
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Previous Military/Security Flag.',
  },
  {
    controlId: 'family_prev_org_name',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.previous_organization',
    domSelector: '#previous_organization',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.militaryOrganization',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Previous Organization.',
  },
  {
    controlId: 'family_prev_desig',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.previous_designation',
    domSelector: '#previous_designation',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.militaryDesignation',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Previous Designation.',
  },
  {
    controlId: 'family_prev_rank',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.previous_rank',
    domSelector: '#previous_rank',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.militaryRank',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Previous Rank.',
  },
  {
    controlId: 'family_prev_posting',
    page: 'FAMILY_DETAILS',
    portalFieldName: 'appl.previous_posting',
    domSelector: '#previous_posting',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'PDF text / Document regex',
    applicantFieldPath: 'employment.militaryPlaceOfPosting',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Previous Place of Posting.',
  },

  // ==========================================
  // PAGE 4: TRAVEL DETAILS (/visa/VisaDetails)
  // ==========================================
  {
    controlId: 'visa_duration',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.duration',
    domSelector: '#duration',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Visa application document / explicit itinerary regex',
    applicantFieldPath: 'travel.duration',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Visa Duration.',
  },
  {
    controlId: 'visa_entry_id',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.visa_entry_id',
    domSelector: '#visa_entry_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Visa application document / explicit itinerary regex',
    applicantFieldPath: 'travel.visaEntryType',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Visa Entry Type.',
  },
  {
    controlId: 'visa_journeydate',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.journeydate',
    domSelector: '#jouryney_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Flight ticket / travel itinerary regex',
    applicantFieldPath: 'travel.intendedArrivalDate',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Expected Arrival Date on Travel Details page.',
  },
  {
    controlId: 'visa_entrypoint',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.entrypoint',
    domSelector: '#entrypoint',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Flight ticket / travel itinerary / booking regex',
    applicantFieldPath: 'travel.entryPoint',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Port of Arrival in India.',
  },
  {
    controlId: 'visa_exitpoint',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.exitpoint',
    domSelector: '#exitpointprc',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Flight ticket / travel itinerary / booking regex',
    applicantFieldPath: 'travel.exitPoint',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Port of Exit.',
  },
  {
    controlId: 'visa_old_visa_flag',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.old_visa_flag',
    domSelector: '#old_visa_flag1, #old_visa_flag2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa document',
    applicantFieldPath: 'previousVisa.hasPreviousVisa',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Previous Indian Visa Flag.',
  },
  {
    controlId: 'visa_prv_visit_add1',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.prv_visit_add1',
    domSelector: '#prv_visit_add1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa / trip record',
    applicantFieldPath: 'previousVisa.visitedAddress1',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Previous Visit Address 1.',
  },
  {
    controlId: 'visa_prv_visit_add2',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.prv_visit_add2',
    domSelector: '#prv_visit_add2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa / trip record',
    applicantFieldPath: 'previousVisa.visitedAddress2',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Previous Visit Address 2.',
  },
  {
    controlId: 'visa_prv_visit_add3',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.prv_visit_add3',
    domSelector: '#prv_visit_add3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa / trip record',
    applicantFieldPath: 'previousVisa.visitedAddress3',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Previous Visit Address 3.',
  },
  {
    controlId: 'visa_old_visa_no',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.old_visa_no',
    domSelector: '#old_visa_no',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa sticker / document regex',
    applicantFieldPath: 'previousVisa.visaNumber',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Old Visa Number.',
  },
  {
    controlId: 'visa_old_visa_type',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.old_visa_type_id',
    domSelector: '#old_visa_type_id',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa sticker / document regex',
    applicantFieldPath: 'previousVisa.visaType',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'selectOptionMatch',
    notes: 'Old Visa Type.',
  },
  {
    controlId: 'visa_old_visa_place',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.oldvisaissueplace',
    domSelector: '#oldvisaissueplace',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa sticker / document regex',
    applicantFieldPath: 'previousVisa.placeOfIssue',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Old Visa Issue Place.',
  },
  {
    controlId: 'visa_old_visa_date',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.oldvisaissuedate',
    domSelector: '#oldvisaissuedate',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Previous visa sticker / document regex',
    applicantFieldPath: 'previousVisa.dateOfIssue',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'isoDateToDdMmYyyy',
    notes: 'Old Visa Issue Date.',
  },
  {
    controlId: 'visa_refuse_flag',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.refuse_flag',
    domSelector: '#refuse_flag1, #refuse_flag2',
    category: 'security-control',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'Visa Refusal Flag - strictly manual user response, never automated.',
  },
  {
    controlId: 'visa_refuse_details',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.refuse_details',
    domSelector: '#refuse_details',
    category: 'security-control',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'Visa Refusal Details - strictly manual user response, never automated.',
  },
  {
    controlId: 'visa_country_visited',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.country_visited',
    domSelector: '#country_visited',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Passport stamps / travel history',
    applicantFieldPath: 'travel.countriesVisited',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Countries Visited.',
  },
  {
    controlId: 'visa_saarc_flag',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.saarc_flag',
    domSelector: '#saarc_flag1, #saarc_flag2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Passport stamps / travel history',
    applicantFieldPath: 'travel.visitedSaarc',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'SAARC Countries Visited Flag.',
  },
  {
    controlId: 'visa_sponsor_ind_name',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.nameofsponsor_ind',
    domSelector: '#nameofsponsor_ind',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Hotel booking / invitation letter',
    applicantFieldPath: 'reference.name',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Sponsor in India Name.',
  },
  {
    controlId: 'visa_sponsor_ind_add1',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.add1ofsponsor_ind',
    domSelector: '#add1ofsponsor_ind',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Hotel booking / invitation letter',
    applicantFieldPath: 'reference.addressLine1',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Sponsor in India Address Line 1.',
  },
  {
    controlId: 'visa_sponsor_ind_add2',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.add2ofsponsor_ind',
    domSelector: '#add2ofsponsor_ind',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Hotel booking / invitation letter',
    applicantFieldPath: 'reference.addressLine2',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Sponsor in India Address Line 2.',
  },
  {
    controlId: 'visa_sponsor_ind_phone',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.phoneofsponsor_ind',
    domSelector: '#phoneofsponsor_ind',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Hotel booking / invitation letter',
    applicantFieldPath: 'reference.phone',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Sponsor in India Phone.',
  },
  {
    controlId: 'visa_sponsor_msn_name',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.nameofsponsor_msn',
    domSelector: '#nameofsponsor_msn',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Home country reference document',
    applicantFieldPath: 'sponsorMission.name',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: 'uppercase',
    notes: 'Reference in Home/Mission Country Name.',
  },
  {
    controlId: 'visa_sponsor_msn_add1',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.add1ofsponsor_msn',
    domSelector: '#add1ofsponsor_msn',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Home country reference document',
    applicantFieldPath: 'sponsorMission.addressLine1',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Reference in Home/Mission Country Address Line 1.',
  },
  {
    controlId: 'visa_sponsor_msn_add2',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.add2ofsponsor_msn',
    domSelector: '#add2ofsponsor_msn',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Home country reference document',
    applicantFieldPath: 'sponsorMission.addressLine2',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Reference in Home/Mission Country Address Line 2.',
  },
  {
    controlId: 'visa_sponsor_msn_phone',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'appl.phoneofsponsor_msn',
    domSelector: '#phoneofsponsor_msn',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: true,
    extractedSource: 'Home country reference document',
    applicantFieldPath: 'sponsorMission.phone',
    coverageCategory: 'B_DOCUMENT_TYPE_DEPENDENT',
    transform: null,
    notes: 'Reference in Home/Mission Country Phone.',
  },
  {
    controlId: 'visa_btn_continue',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'continue',
    domSelector: '#continue',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Form submission button. Never auto-clicked.',
  },
  {
    controlId: 'visa_btn_exit',
    page: 'TRAVEL_DETAILS',
    portalFieldName: 'exit',
    domSelector: '#exit',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Form exit button. Never auto-clicked.',
  },

  // ==========================================
  // PAGE 5: ADDITIONAL QUESTIONS (/visa/AdditionalQuestions)
  // ==========================================
  {
    controlId: 'q_1_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_1',
    domSelector: '#question_yes_1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 1 Yes radio. Left untouched when source absent.',
  },
  {
    controlId: 'q_1_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_1',
    domSelector: '#question_no_1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 1 No radio. Left untouched when source absent.',
  },
  {
    controlId: 'q_1_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_1',
    domSelector: '#answer_1',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 1 affirmative explanation details.',
  },
  {
    controlId: 'q_2_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_2',
    domSelector: '#question_yes_2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 2 Yes radio.',
  },
  {
    controlId: 'q_2_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_2',
    domSelector: '#question_no_2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 2 No radio.',
  },
  {
    controlId: 'q_2_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_2',
    domSelector: '#answer_2',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 2 affirmative explanation details.',
  },
  {
    controlId: 'q_3_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_3',
    domSelector: '#question_yes_3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 3 Yes radio.',
  },
  {
    controlId: 'q_3_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_3',
    domSelector: '#question_no_3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 3 No radio.',
  },
  {
    controlId: 'q_3_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_3',
    domSelector: '#answer_3',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 3 affirmative explanation details.',
  },
  {
    controlId: 'q_4_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_4',
    domSelector: '#question_yes_4',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 4 Yes radio.',
  },
  {
    controlId: 'q_4_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_4',
    domSelector: '#question_no_4',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 4 No radio.',
  },
  {
    controlId: 'q_4_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_4',
    domSelector: '#answer_4',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 4 affirmative explanation details.',
  },
  {
    controlId: 'q_5_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_5',
    domSelector: '#question_yes_5',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 5 Yes radio.',
  },
  {
    controlId: 'q_5_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_5',
    domSelector: '#question_no_5',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 5 No radio.',
  },
  {
    controlId: 'q_5_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_5',
    domSelector: '#answer_5',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 5 affirmative explanation details.',
  },
  {
    controlId: 'q_6_yes',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_yes_6',
    domSelector: '#question_yes_6',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 6 Yes radio.',
  },
  {
    controlId: 'q_6_no',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'question_no_6',
    domSelector: '#question_no_6',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 6 No radio.',
  },
  {
    controlId: 'q_6_ans',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'answer_6',
    domSelector: '#answer_6',
    category: 'verified-selector',
    eligibility: 'autofillable',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'D_LEAVE_EMPTY_SOURCE_ABSENT',
    transform: null,
    notes: 'Question 6 affirmative explanation details.',
  },
  {
    controlId: 'q_declaration',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'verifyQuestions',
    domSelector: '#verifyQuestions',
    category: 'security-control',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'Declaration checkbox. Manual user confirmation required.',
  },
  {
    controlId: 'q_btn_continue',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'continue',
    domSelector: '#continue',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Submit/Continue button.',
  },
  {
    controlId: 'q_btn_exit',
    page: 'ADDITIONAL_QUESTIONS',
    portalFieldName: 'exit',
    domSelector: '#exit',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Exit button.',
  },

  // ==========================================
  // PAGE 6: DOCUMENT UPLOAD (/visa/PhotoUpload)
  // ==========================================
  {
    controlId: 'photo_file_upload',
    page: 'DOCUMENT_UPLOAD',
    portalFieldName: 'photo',
    domSelector: '#photo',
    category: 'verified-selector',
    eligibility: 'manual-only',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'SECURITY_MANUAL',
    transform: null,
    notes: 'Photograph file upload. Manual user file selection in this phase.',
  },
  {
    controlId: 'photo_upload_btn',
    page: 'DOCUMENT_UPLOAD',
    portalFieldName: 'upload',
    domSelector: '#upload',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Upload photo action button.',
  },
  {
    controlId: 'photo_btn_continue',
    page: 'DOCUMENT_UPLOAD',
    portalFieldName: 'continue',
    domSelector: '#continue',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Submit/Continue button.',
  },
  {
    controlId: 'photo_btn_exit',
    page: 'DOCUMENT_UPLOAD',
    portalFieldName: 'exit',
    domSelector: '#exit',
    category: 'technical-control',
    eligibility: 'technical-ignored',
    isExtractedByCurrentPdf: false,
    extractedSource: null,
    applicantFieldPath: null,
    coverageCategory: 'TECHNICAL_IGNORED',
    transform: null,
    notes: 'Exit button.',
  },
]

/**
 * Returns summary statistics for the Bangladesh Portal coverage matrix.
 */
export function getCoverageMatrixStats() {
  const total = BANGLADESH_PORTAL_COVERAGE_MATRIX.length
  const verifiedAutofillable = BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.eligibility === 'autofillable').length
  const securityManual = BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.eligibility === 'manual-only').length
  const technicalIgnored = BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.eligibility === 'technical-ignored').length
  const directlyExtracted = BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.isExtractedByCurrentPdf).length

  return {
    total,
    verifiedAutofillable,
    securityManual,
    technicalIgnored,
    directlyExtracted,
    byPage: {
      REGISTRATION: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'REGISTRATION').length,
      BASIC_DETAILS: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'BASIC_DETAILS').length,
      FAMILY_DETAILS: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'FAMILY_DETAILS').length,
      TRAVEL_DETAILS: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'TRAVEL_DETAILS').length,
      ADDITIONAL_QUESTIONS: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'ADDITIONAL_QUESTIONS').length,
      DOCUMENT_UPLOAD: BANGLADESH_PORTAL_COVERAGE_MATRIX.filter((e) => e.page === 'DOCUMENT_UPLOAD').length,
    },
  }
}
