import type { FieldInputType, FieldMapping, FieldSelector, MappingStatus, SelectorStrategy } from '../../core/autofill/types'

export type IndiaFieldInputType = FieldInputType
export type SelectorStrategyType = SelectorStrategy
export type IndiaFieldSelector = FieldSelector
export type IndiaMappingStatus = MappingStatus

export type ApplicantProfileFieldPath =
  | 'personalInfo.surname'
  | 'personalInfo.givenNames'
  | 'personalInfo.previousName'
  | 'personalInfo.dateOfBirth'
  | 'personalInfo.townCityOfBirth'
  | 'personalInfo.countryOfBirth'
  | 'personalInfo.nationalIdNumber'
  | 'personalInfo.religion'
  | 'personalInfo.visibleIdentificationMarks'
  | 'personalInfo.educationalQualification'
  | 'personalInfo.nationality'
  | 'personalInfo.previousNationality'
  | 'personalInfo.gender'
  | 'passport.passportNumber'
  | 'passport.passportType'
  | 'passport.issuingCountry'
  | 'passport.issueDate'
  | 'passport.expiryDate'
  | 'passport.placeOfIssue'
  | 'presentAddress.addressLine1'
  | 'presentAddress.addressLine2'
  | 'presentAddress.villageTownCity'
  | 'presentAddress.district'
  | 'presentAddress.stateProvince'
  | 'presentAddress.country'
  | 'presentAddress.postalCode'
  | 'permanentAddress.addressLine1'
  | 'permanentAddress.addressLine2'
  | 'permanentAddress.villageTownCity'
  | 'permanentAddress.district'
  | 'permanentAddress.stateProvince'
  | 'permanentAddress.country'
  | 'permanentAddress.postalCode'
  | 'permanentAddress.sameAsPresentAddress'
  | 'contact.email'
  | 'contact.mobile'
  | 'contact.phone'
  | 'family.father.name'
  | 'family.father.nationality'
  | 'family.father.previousNationality'
  | 'family.father.placeOfBirth'
  | 'family.father.countryOfBirth'
  | 'family.mother.name'
  | 'family.mother.nationality'
  | 'family.mother.previousNationality'
  | 'family.mother.placeOfBirth'
  | 'family.mother.countryOfBirth'
  | 'family.spouse.name'
  | 'family.spouse.nationality'
  | 'family.spouse.previousNationality'
  | 'family.spouse.placeOfBirth'
  | 'family.spouse.countryOfBirth'
  | 'employment.presentOccupation'
  | 'employment.designationRank'
  | 'employment.employerName'
  | 'employment.employerPhone'
  | 'employment.employerAddress'
  | 'employment.employerAddress.addressLine1'
  | 'employment.employerAddress.addressLine2'
  | 'employment.employerAddress.villageTownCity'
  | 'employment.employerAddress.district'
  | 'employment.employerAddress.stateProvince'
  | 'employment.employerAddress.country'
  | 'employment.employerAddress.postalCode'
  | 'travel.purposeOfVisit'
  | 'travel.intendedArrivalDate'
  | 'travel.intendedDepartureDate'
  | 'travel.countriesToVisit'
  | 'travel.previousVisitToCountry'
  | 'travel.travelCompanions'
  | 'accommodation.placeHotelName'
  | 'accommodation.state'
  | 'accommodation.phone'
  | 'accommodation.address'
  | 'accommodation.address.addressLine1'
  | 'accommodation.address.addressLine2'
  | 'accommodation.address.villageTownCity'
  | 'accommodation.address.district'
  | 'accommodation.address.stateProvince'
  | 'accommodation.address.country'
  | 'accommodation.address.postalCode'
  | 'accommodation.bookingReference'
  | 'reference.name'
  | 'reference.phone'
  | 'reference.email'
  | 'reference.address'
  | 'reference.address.addressLine1'
  | 'reference.address.addressLine2'
  | 'reference.address.villageTownCity'
  | 'reference.address.district'
  | 'reference.address.stateProvince'
  | 'reference.address.country'
  | 'reference.address.postalCode'
  | 'notes'

import type { IndiaVisaPage } from './types'

export interface IndiaVisaFieldMapping extends FieldMapping {
  sourceField?: ApplicantProfileFieldPath
  page?: IndiaVisaPage
}
