import type { IndiaVisaFieldMapping } from '../mapping.types'
import { BANGLADESH_VISA_SELECTORS } from '../selectors/bangladeshVisa'

/**
 * Bangladesh Indian Visa Portal (indianvisa-bangladesh.nic.in) Field Mappings.
 * 
 * Target Portal Pages:
 * - /visa/Registration (Canonical Page Identity: 'registration')
 * - /visa/BasicDetails (Canonical Page Identity: 'basic-details')
 * 
 * All automated field mappings are explicitly marked `unverified` because live DOM evidence
 * is intentionally not assumed. CAPTCHA is strictly marked manual-only.
 */
export const BANGLADESH_VISA_MAPPINGS: IndiaVisaFieldMapping[] = [
  // ==========================================
  // /visa/Registration Page Fields
  // ==========================================
  {
    id: 'bd_reg_country',
    section: 'application-information',
    targetField: 'country_applying_from',
    sourceField: 'presentAddress.country',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.applyingFromCountry,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'registration',
    notes: 'Country/Region applying visa from (Bangladesh portal)',
  },
  {
    id: 'bd_reg_indian_mission',
    section: 'application-information',
    targetField: 'indian_mission',
    sourceField: 'registration.indianMission',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.indianMission,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'registration',
    notes: 'Indian Mission/Office in Bangladesh (e.g. IVAC Dhaka, Chittagong, etc.)',
  },
  {
    id: 'bd_reg_nationality',
    section: 'application-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.nationality,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'registration',
  },
  {
    id: 'bd_reg_dob',
    section: 'application-information',
    targetField: 'dob',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'unverified',
    required: true,
    page: 'registration',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_reg_email',
    section: 'application-information',
    targetField: 'email',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.email,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'registration',
    transform: 'lowercase',
  },
  {
    id: 'bd_reg_email_confirm',
    section: 'application-information',
    targetField: 'email_re',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.emailConfirm,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'registration',
    transform: 'lowercase',
  },
  {
    id: 'bd_reg_expected_arrival',
    section: 'application-information',
    targetField: 'arr_date',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.expectedArrivalDate,
    inputType: 'date',
    status: 'unverified',
    required: true,
    page: 'registration',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_reg_captcha',
    section: 'application-information',
    targetField: 'captcha',
    sourceType: 'manual',
    selector: BANGLADESH_VISA_SELECTORS.captcha,
    inputType: 'text',
    status: 'verified',
    page: 'registration',
    notes: 'CAPTCHA MUST be solved manually by the user. Automation is prohibited.',
  },

  // ==========================================
  // /visa/BasicDetails Page Fields
  // ==========================================
  {
    id: 'bd_basic_surname',
    section: 'personal-information',
    targetField: 'applicant_surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.surname,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_given_name',
    section: 'personal-information',
    targetField: 'applicant_given_name',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.givenName,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_gender',
    section: 'personal-information',
    targetField: 'gender',
    sourceField: 'personalInfo.gender',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.gender,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_dob',
    section: 'personal-information',
    targetField: 'date_of_birth',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_town_city_of_birth',
    section: 'personal-information',
    targetField: 'city_of_birth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_country_of_birth',
    section: 'personal-information',
    targetField: 'country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_national_id',
    section: 'personal-information',
    targetField: 'national_id',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'unverified',
    required: false,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_religion',
    section: 'personal-information',
    targetField: 'religion',
    sourceField: 'personalInfo.religion',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.religion,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_educational_qualification',
    section: 'personal-information',
    targetField: 'educational_qualification',
    sourceField: 'personalInfo.educationalQualification',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.educationalQualification,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_nationality',
    section: 'personal-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.nationality,
    inputType: 'select',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_passport_number',
    section: 'passport-information',
    targetField: 'passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_place_of_issue',
    section: 'passport-information',
    targetField: 'place_of_issue',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'unverified',
    required: true,
    page: 'basic-details',
  },
  {
    id: 'bd_basic_passport_issue_date',
    section: 'passport-information',
    targetField: 'issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.issueDate,
    inputType: 'date',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_passport_expiry_date',
    section: 'passport-information',
    targetField: 'expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'unverified',
    required: true,
    page: 'basic-details',
    transform: 'isoDateToDdMmYyyy',
  },
]

