import type { IndiaVisaFieldMapping } from '../mapping.types'
import { EVISA_SELECTORS } from '../selectors/eVisa'

/**
 * Verified field mappings for official Indian e-Visa Online forms.
 */
export const EVISA_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'evisa_passport_type',
    section: 'application-information',
    targetField: 'passportType',
    sourceField: 'passport.passportType',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.passportType,
    inputType: 'select',
    status: 'verified',
    required: true,
  },
  {
    id: 'evisa_nationality',
    section: 'application-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.nationality,
    inputType: 'select',
    status: 'verified',
    required: true,
  },
  {
    id: 'evisa_dob',
    section: 'application-information',
    targetField: 'dob',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'evisa_email',
    section: 'application-information',
    targetField: 'emailId',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.email,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'lowercase',
  },
  {
    id: 'evisa_surname',
    section: 'personal-information',
    targetField: 'surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'evisa_given_name',
    section: 'personal-information',
    targetField: 'givenName',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'evisa_passport_no',
    section: 'passport-information',
    targetField: 'passportNo',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'evisa_passport_issue_date',
    section: 'passport-information',
    targetField: 'passportIssueDate',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'evisa_passport_expiry_date',
    section: 'passport-information',
    targetField: 'passportExpiryDate',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },
]
