import type { IndiaVisaFieldMapping } from '../mapping.types'
import { EVISA_SELECTORS } from '../selectors/eVisa'

/**
 * Verified field mappings for official Indian e-Visa Online forms.
 */
export const EVISA_MAPPINGS: IndiaVisaFieldMapping[] = [
  // Form 1: Personal & Passport Details
  {
    id: 'evisa_passport_type',
    section: 'application-information',
    targetField: 'passportType',
    sourceField: 'passport.passportType',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.passportType,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'evisa_nationality',
    section: 'application-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.nationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'evisa_dob',
    section: 'application-information',
    targetField: 'dob',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'evisa_email',
    section: 'application-information',
    targetField: 'emailId',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.email,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'lowercase',
  },
  {
    id: 'evisa_surname',
    section: 'personal-information',
    targetField: 'surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'evisa_given_name',
    section: 'personal-information',
    targetField: 'givenName',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'evisa_passport_no',
    section: 'passport-information',
    targetField: 'passportNo',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'evisa_passport_issue_date',
    section: 'passport-information',
    targetField: 'passportIssueDate',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'evisa_passport_expiry_date',
    section: 'passport-information',
    targetField: 'passportExpiryDate',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },

  // Form 2: Present Address, Permanent Address & Family Information
  {
    id: 'evisa_pres_addr1',
    section: 'address-information',
    targetField: 'presAddress1',
    sourceField: 'presentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentAddressLine1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_pres_addr2',
    section: 'address-information',
    targetField: 'presAddress2',
    sourceField: 'presentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentAddressLine2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'evisa_pres_city',
    section: 'address-information',
    targetField: 'presCity',
    sourceField: 'presentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_pres_state',
    section: 'address-information',
    targetField: 'presState',
    sourceField: 'presentAddress.stateProvince',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentState,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_pres_country',
    section: 'address-information',
    targetField: 'presCountry',
    sourceField: 'presentAddress.country',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentCountry,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_pres_zip',
    section: 'address-information',
    targetField: 'presZip',
    sourceField: 'presentAddress.postalCode',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_mobile',
    section: 'contact-information',
    targetField: 'mobile',
    sourceField: 'contact.mobile',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.mobile,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_phone',
    section: 'contact-information',
    targetField: 'phone',
    sourceField: 'contact.phone',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.phone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_addr1',
    section: 'address-information',
    targetField: 'permAddress1',
    sourceField: 'permanentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentAddressLine1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_addr2',
    section: 'address-information',
    targetField: 'permAddress2',
    sourceField: 'permanentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentAddressLine2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_city',
    section: 'address-information',
    targetField: 'permCity',
    sourceField: 'permanentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_state',
    section: 'address-information',
    targetField: 'permState',
    sourceField: 'permanentAddress.stateProvince',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentState,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_country',
    section: 'address-information',
    targetField: 'permCountry',
    sourceField: 'permanentAddress.country',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentCountry,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_perm_zip',
    section: 'address-information',
    targetField: 'permZip',
    sourceField: 'permanentAddress.postalCode',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.permanentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_same_addr',
    section: 'address-information',
    targetField: 'sameAddressCheckbox',
    sourceField: 'permanentAddress.sameAsPresentAddress',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.sameAsPresentAddress,
    inputType: 'checkbox',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'evisa_father_name',
    section: 'family-information',
    targetField: 'fatherName',
    sourceField: 'family.father.name',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.fatherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_father_nationality',
    section: 'family-information',
    targetField: 'fatherNationality',
    sourceField: 'family.father.nationality',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.fatherNationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_father_place_birth',
    section: 'family-information',
    targetField: 'fatherPlaceOfBirth',
    sourceField: 'family.father.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.fatherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_father_country_birth',
    section: 'family-information',
    targetField: 'fatherCountryOfBirth',
    sourceField: 'family.father.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.fatherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_mother_name',
    section: 'family-information',
    targetField: 'motherName',
    sourceField: 'family.mother.name',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.motherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_mother_nationality',
    section: 'family-information',
    targetField: 'motherNationality',
    sourceField: 'family.mother.nationality',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.motherNationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_mother_place_birth',
    section: 'family-information',
    targetField: 'motherPlaceOfBirth',
    sourceField: 'family.mother.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.motherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'evisa_mother_country_birth',
    section: 'family-information',
    targetField: 'motherCountryOfBirth',
    sourceField: 'family.mother.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.motherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },

  // Form 3: Visa details / Travel details
  {
    id: 'evisa_purpose_visit',
    section: 'travel-information',
    targetField: 'purposeOfVisit',
    sourceField: 'travel.purposeOfVisit',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.purposeOfVisit,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'travel-details',
  },
  {
    id: 'evisa_arrival_date',
    section: 'travel-information',
    targetField: 'intendedArrivalDate',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.intendedArrivalDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'travel-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'evisa_departure_date',
    section: 'travel-information',
    targetField: 'intendedDepartureDate',
    sourceField: 'travel.intendedDepartureDate',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.intendedDepartureDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'travel-details',
    transform: 'isoDateToDdMmYyyy',
  },

  // Form 4: Employment / Occupation
  {
    id: 'evisa_present_occupation',
    section: 'employment-information',
    targetField: 'presentOccupation',
    sourceField: 'employment.presentOccupation',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.presentOccupation,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'evisa_designation',
    section: 'employment-information',
    targetField: 'designation',
    sourceField: 'employment.designationRank',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.designationRank,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'evisa_employer_name',
    section: 'employment-information',
    targetField: 'employerName',
    sourceField: 'employment.employerName',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.employerName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'evisa_employer_address',
    section: 'employment-information',
    targetField: 'employerAddress',
    sourceField: 'employment.employerAddress',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.employerAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'evisa_employer_phone',
    section: 'employment-information',
    targetField: 'employerPhone',
    sourceField: 'employment.employerPhone',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.employerPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },

  // Form 5: Reference details & Accommodation details
  {
    id: 'evisa_hotel_name',
    section: 'accommodation-information',
    targetField: 'hotelName',
    sourceField: 'accommodation.placeHotelName',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.hotelName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_hotel_address',
    section: 'accommodation-information',
    targetField: 'hotelAddress',
    sourceField: 'accommodation.address',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.hotelAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_hotel_state',
    section: 'accommodation-information',
    targetField: 'hotelState',
    sourceField: 'accommodation.state',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.hotelState,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_hotel_phone',
    section: 'accommodation-information',
    targetField: 'hotelPhone',
    sourceField: 'accommodation.phone',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.hotelPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_booking_ref',
    section: 'accommodation-information',
    targetField: 'bookingReference',
    sourceField: 'accommodation.bookingReference',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.bookingReference,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'reference-details',
  },
  {
    id: 'evisa_ref_india_name',
    section: 'reference-information',
    targetField: 'refIndiaName',
    sourceField: 'reference.name',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.referenceIndiaName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_ref_india_address',
    section: 'reference-information',
    targetField: 'refIndiaAddress',
    sourceField: 'reference.address',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.referenceIndiaAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'evisa_ref_india_phone',
    section: 'reference-information',
    targetField: 'refIndiaPhone',
    sourceField: 'reference.phone',
    sourceType: 'applicant-profile',
    selector: EVISA_SELECTORS.referenceIndiaPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
]
