import type { IndiaVisaFieldMapping } from '../mapping.types'
import { REGULAR_VISA_SELECTORS } from '../selectors/regularVisa'

/**
 * Verified field mappings for official Indian Regular/Paper Visa online forms.
 * Maps generic ApplicantProfile fields to target website inputs.
 */
export const REGULAR_VISA_MAPPINGS: IndiaVisaFieldMapping[] = [
  // Page 1: Application Start / Registration
  {
    id: 'reg_indian_mission',
    section: 'application-information',
    targetField: 'indian_mission',
    sourceType: 'country-specific',
    selector: REGULAR_VISA_SELECTORS.indianMission,
    inputType: 'select',
    status: 'verified',
    required: true,
    notes: 'Indian Mission location where application will be submitted.',
  },
  {
    id: 'reg_nationality',
    section: 'application-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.nationality,
    inputType: 'select',
    status: 'verified',
    required: true,
  },
  {
    id: 'reg_dob',
    section: 'application-information',
    targetField: 'dob',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'reg_email',
    section: 'application-information',
    targetField: 'email',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.email,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'lowercase',
  },
  {
    id: 'reg_arr_date',
    section: 'application-information',
    targetField: 'arr_date',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.expectedArrivalDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },

  // Page 2: Personal & Passport Information
  {
    id: 'form_surname',
    section: 'personal-information',
    targetField: 'applicant_surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'form_given_name',
    section: 'personal-information',
    targetField: 'applicant_given_name',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'form_gender',
    section: 'personal-information',
    targetField: 'gender',
    sourceField: 'personalInfo.gender',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.gender,
    inputType: 'select',
    status: 'verified',
    required: true,
  },
  {
    id: 'form_city_of_birth',
    section: 'personal-information',
    targetField: 'city_of_birth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
  },
  {
    id: 'form_country_of_birth',
    section: 'personal-information',
    targetField: 'country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
  },
  {
    id: 'form_national_id',
    section: 'personal-information',
    targetField: 'national_id',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
  },

  // Passport Details
  {
    id: 'form_passport_number',
    section: 'passport-information',
    targetField: 'passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
  },
  {
    id: 'form_place_of_issue',
    section: 'passport-information',
    targetField: 'place_of_issue',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'verified',
    required: true,
  },
  {
    id: 'form_passport_issue_date',
    section: 'passport-information',
    targetField: 'issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'form_passport_expiry_date',
    section: 'passport-information',
    targetField: 'expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    transform: 'isoDateToDdMmYyyy',
  },

  // Address & Contact
  {
    id: 'form_pres_addr1',
    section: 'address-information',
    targetField: 'pres_addr1',
    sourceField: 'presentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentAddressLine1,
    inputType: 'text',
    status: 'verified',
    required: true,
  },
  {
    id: 'form_mobile_no',
    section: 'contact-information',
    targetField: 'mobile_no',
    sourceField: 'contact.mobile',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.mobile,
    inputType: 'text',
    status: 'verified',
    required: true,
  },
]
