import type { IndiaVisaFieldMapping } from '../mapping.types'
import { REGULAR_VISA_SELECTORS } from '../selectors/regularVisa'

/**
 * Verified field mappings for official Indian Regular/Paper Visa online forms.
 * Maps generic ApplicantProfile fields to target website inputs.
 */
export const REGULAR_VISA_MAPPINGS: IndiaVisaFieldMapping[] = [
  // Page 1: Application Start / Registration
  {
    id: 'reg_country',
    section: 'application-information',
    targetField: 'country_applying_from',
    sourceField: 'presentAddress.country',
    sourceType: 'applicant-profile',
    selector: { strategy: 'id', value: 'countryname_id' },
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'application-start',
  },
  {
    id: 'reg_indian_mission',
    section: 'application-information',
    targetField: 'indian_mission',
    sourceField: 'registration.indianMission',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.indianMission,
    fallbackSelector: { strategy: 'id', value: 'missioncode_id' },
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'application-start',
    notes: 'Indian Mission location where application will be submitted.',
  },
  {
    id: 'reg_nationality',
    section: 'application-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.nationality,
    fallbackSelector: { strategy: 'id', value: 'nationality_id' },
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'application-start',
  },
  {
    id: 'reg_dob',
    section: 'application-information',
    targetField: 'dob',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.dateOfBirth,
    fallbackSelector: { strategy: 'id', value: 'dob_id' },
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'application-start',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'reg_email',
    section: 'application-information',
    targetField: 'email',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.email,
    fallbackSelector: { strategy: 'id', value: 'email_id' },
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'application-start',
    transform: 'lowercase',
  },
  {
    id: 'reg_email_confirm',
    section: 'application-information',
    targetField: 'email_re',
    sourceField: 'contact.email',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.emailConfirm,
    fallbackSelector: { strategy: 'id', value: 'email_re_id' },
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'application-start',
    transform: 'lowercase',
  },
  {
    id: 'reg_arr_date',
    section: 'application-information',
    targetField: 'arr_date',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.expectedArrivalDate,
    fallbackSelector: { strategy: 'id', value: 'jouryney_id' },
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'application-start',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'reg_captcha',
    section: 'application-information',
    targetField: 'captcha',
    sourceType: 'manual',
    selector: { strategy: 'id', value: 'captcha' },
    inputType: 'text',
    status: 'verified',
    page: 'application-start',
    notes: 'CAPTCHA verification must be completed manually.',
  },

  // Page 2: Personal & Passport Information
  {
    id: 'form_surname',
    section: 'personal-information',
    targetField: 'applicant_surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'form_given_name',
    section: 'personal-information',
    targetField: 'applicant_given_name',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'form_gender',
    section: 'personal-information',
    targetField: 'gender',
    sourceField: 'personalInfo.gender',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.gender,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'form_dob',
    section: 'personal-information',
    targetField: 'date_of_birth',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.dateOfBirth,
    fallbackSelector: { strategy: 'id', value: 'dob_id' },
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'form_nationality',
    section: 'personal-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.nationality,
    fallbackSelector: { strategy: 'id', value: 'nationality_id' },
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'form_city_of_birth',
    section: 'personal-information',
    targetField: 'city_of_birth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'form_country_of_birth',
    section: 'personal-information',
    targetField: 'country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'form_national_id',
    section: 'personal-information',
    targetField: 'national_id',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'personal-details',
  },
  {
    id: 'form_passport_number',
    section: 'passport-information',
    targetField: 'passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'uppercase',
  },
  {
    id: 'form_place_of_issue',
    section: 'passport-information',
    targetField: 'place_of_issue',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'personal-details',
  },
  {
    id: 'form_passport_issue_date',
    section: 'passport-information',
    targetField: 'issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'form_passport_expiry_date',
    section: 'passport-information',
    targetField: 'expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'personal-details',
    transform: 'isoDateToDdMmYyyy',
  },

  // Address & Contacts (Page 3)
  {
    id: 'form_pres_addr1',
    section: 'address-information',
    targetField: 'pres_addr1',
    sourceField: 'presentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentAddressLine1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_pres_addr2',
    section: 'address-information',
    targetField: 'pres_addr2',
    sourceField: 'presentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentAddressLine2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'form_pres_city',
    section: 'address-information',
    targetField: 'pres_city',
    sourceField: 'presentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_pres_state',
    section: 'address-information',
    targetField: 'pres_state',
    sourceField: 'presentAddress.stateProvince',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentState,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_pres_country',
    section: 'address-information',
    targetField: 'pres_country',
    sourceField: 'presentAddress.country',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentCountry,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_pres_zip',
    section: 'address-information',
    targetField: 'pres_postal_code',
    sourceField: 'presentAddress.postalCode',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_mobile_no',
    section: 'contact-information',
    targetField: 'mobile_no',
    sourceField: 'contact.mobile',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.mobile,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_phone_no',
    section: 'contact-information',
    targetField: 'phone_no',
    sourceField: 'contact.phone',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.phone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },

  // Permanent Address
  {
    id: 'form_perm_addr1',
    section: 'address-information',
    targetField: 'perm_addr1',
    sourceField: 'permanentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentAddressLine1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_perm_addr2',
    section: 'address-information',
    targetField: 'perm_addr2',
    sourceField: 'permanentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentAddressLine2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'address-details',
  },
  {
    id: 'form_perm_city',
    section: 'address-information',
    targetField: 'perm_city',
    sourceField: 'permanentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_perm_state',
    section: 'address-information',
    targetField: 'perm_state',
    sourceField: 'permanentAddress.stateProvince',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentState,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_perm_country',
    section: 'address-information',
    targetField: 'perm_country',
    sourceField: 'permanentAddress.country',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentCountry,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_perm_zip',
    section: 'address-information',
    targetField: 'perm_postal_code',
    sourceField: 'permanentAddress.postalCode',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.permanentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'address-details',
  },
  {
    id: 'form_same_addr',
    section: 'address-information',
    targetField: 'same_address',
    sourceField: 'permanentAddress.sameAsPresentAddress',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.sameAsPresentAddress,
    inputType: 'checkbox',
    status: 'verified',
    required: false,
    page: 'address-details',
  },

  // Family Information (Page 4)
  {
    id: 'form_father_name',
    section: 'family-information',
    targetField: 'father_name',
    sourceField: 'family.father.name',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.fatherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_father_nationality',
    section: 'family-information',
    targetField: 'father_nationality',
    sourceField: 'family.father.nationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.fatherNationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_father_prev_nationality',
    section: 'family-information',
    targetField: 'father_prev_nationality',
    sourceField: 'family.father.previousNationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.fatherPreviousNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'family-details',
  },
  {
    id: 'form_father_place_birth',
    section: 'family-information',
    targetField: 'father_place_birth',
    sourceField: 'family.father.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.fatherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_father_country_birth',
    section: 'family-information',
    targetField: 'father_country_birth',
    sourceField: 'family.father.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.fatherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_mother_name',
    section: 'family-information',
    targetField: 'mother_name',
    sourceField: 'family.mother.name',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.motherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_mother_nationality',
    section: 'family-information',
    targetField: 'mother_nationality',
    sourceField: 'family.mother.nationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.motherNationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_mother_prev_nationality',
    section: 'family-information',
    targetField: 'mother_prev_nationality',
    sourceField: 'family.mother.previousNationality',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.motherPreviousNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'family-details',
  },
  {
    id: 'form_mother_place_birth',
    section: 'family-information',
    targetField: 'mother_place_birth',
    sourceField: 'family.mother.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.motherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'family-details',
  },
  {
    id: 'form_mother_country_birth',
    section: 'family-information',
    targetField: 'mother_country_birth',
    sourceField: 'family.mother.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.motherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'family-details',
  },

  // Employment / Occupation (Page 5)
  {
    id: 'form_present_occupation',
    section: 'employment-information',
    targetField: 'present_occupation',
    sourceField: 'employment.presentOccupation',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.presentOccupation,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'form_designation',
    section: 'employment-information',
    targetField: 'designation',
    sourceField: 'employment.designationRank',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.designationRank,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'form_employer_name',
    section: 'employment-information',
    targetField: 'employer_name',
    sourceField: 'employment.employerName',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.employerName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'form_employer_address',
    section: 'employment-information',
    targetField: 'employer_address',
    sourceField: 'employment.employerAddress',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.employerAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },
  {
    id: 'form_employer_phone',
    section: 'employment-information',
    targetField: 'employer_phone',
    sourceField: 'employment.employerPhone',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.employerPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'occupation-details',
  },

  // Travel details (Page 6)
  {
    id: 'form_purpose_visit',
    section: 'travel-information',
    targetField: 'purpose',
    sourceField: 'travel.purposeOfVisit',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.purposeOfVisit,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'travel-details',
  },
  {
    id: 'form_arrival_date',
    section: 'travel-information',
    targetField: 'arrival_date',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.intendedArrivalDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'travel-details',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'form_departure_date',
    section: 'travel-information',
    targetField: 'departure_date',
    sourceField: 'travel.intendedDepartureDate',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.intendedDepartureDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'travel-details',
    transform: 'isoDateToDdMmYyyy',
  },

  // Accommodation & References (Page 7)
  {
    id: 'form_hotel_name',
    section: 'accommodation-information',
    targetField: 'hotel_name',
    sourceField: 'accommodation.placeHotelName',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.hotelName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_hotel_address',
    section: 'accommodation-information',
    targetField: 'hotel_address',
    sourceField: 'accommodation.address',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.hotelAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_hotel_state',
    section: 'accommodation-information',
    targetField: 'hotel_state',
    sourceField: 'accommodation.state',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.hotelState,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_hotel_phone',
    section: 'accommodation-information',
    targetField: 'hotel_phone',
    sourceField: 'accommodation.phone',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.hotelPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_booking_ref',
    section: 'accommodation-information',
    targetField: 'booking_ref',
    sourceField: 'accommodation.bookingReference',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.bookingReference,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'reference-details',
  },
  {
    id: 'form_ref_india_name',
    section: 'reference-information',
    targetField: 'ref_india_name',
    sourceField: 'reference.name',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.referenceIndiaName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_ref_india_address',
    section: 'reference-information',
    targetField: 'ref_india_address',
    sourceField: 'reference.address',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.referenceIndiaAddress,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
  {
    id: 'form_ref_india_phone',
    section: 'reference-information',
    targetField: 'ref_india_phone',
    sourceField: 'reference.phone',
    sourceType: 'applicant-profile',
    selector: REGULAR_VISA_SELECTORS.referenceIndiaPhone,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'reference-details',
  },
]
