import type { PortalSelectOption } from './registrationOptions'

/**
 * Complete Indian State to Districts mapping for all 37 States & Union Territories
 * in the official Indian Visa Portal.
 * All district names are normalized in uppercase according to portal select options.
 */
export const INDIAN_STATE_DISTRICTS_MAP: Record<string, string[]> = {
  'ANDAMAN AND NICOBAR': [
    'NICOBAR',
    'NORTH AND MIDDLE ANDAMAN',
    'SOUTH ANDAMAN',
  ],
  'ANDHRA PRADESH': [
    'ALLURI SITHARAMA RAJU',
    'ANAKAPALLI',
    'ANANTHAPURAMU',
    'ANNAMAYYA',
    'BAPATLA',
    'CHITTOOR',
    'DR B R AMBEDKAR KONASEEMA',
    'EAST GODAVARI',
    'ELURU',
    'GUNTUR',
    'KAKINADA',
    'KRISHNA',
    'KURNOOL',
    'NANDYAL',
    'NTR',
    'PALNADU',
    'PARVATHIPURAM MANYAM',
    'PRAKASAM',
    'SRI POTTI SRIRAMULU NELLORE',
    'SRI SATHYA SAI',
    'SRIKAKULAM',
    'TIRUPATI',
    'VISAKHAPATNAM',
    'VIZIANAGARAM',
    'WEST GODAVARI',
    'YSR KADAPA',
  ],
  'ARUNACHAL PRADESH': [
    'ANJAW',
    'CHANGLANG',
    'DIBANG VALLEY',
    'EAST KAMENG',
    'EAST SIANG',
    'ITANAGAR CAPITAL COMPLEX',
    'KAMLE',
    'KRA DAADI',
    'KURUNG KUMEY',
    'LEPARADA',
    'LOHIT',
    'LONGDING',
    'LOWER DIBANG VALLEY',
    'LOWER SIANG',
    'LOWER SUBANSIRI',
    'NAMSAI',
    'PAKKE KESSANG',
    'PAPUM PARE',
    'SHI YOMI',
    'SIANG',
    'TAWANG',
    'TIRAP',
    'UPPER SIANG',
    'UPPER SUBANSIRI',
    'WEST KAMENG',
    'WEST SIANG',
  ],
  'ASSAM': [
    'BAKSA',
    'BARPETA',
    'BISWANATH',
    'BONGAIGAON',
    'CACHAR',
    'CHARAIDEO',
    'CHIRANG',
    'DARRANG',
    'DHEMAJI',
    'DHUBRI',
    'DIBRUGARH',
    'DIMA HASAO',
    'GOALPARA',
    'GOLAGHAT',
    'HAILAKANDI',
    'HOJAI',
    'JORHAT',
    'KAMRUP',
    'KAMRUP METROPOLITAN',
    'KARBI ANGLONG',
    'KARIMGANJ',
    'KOKRAJHAR',
    'LAKHIMPUR',
    'MAJULI',
    'MORIGAON',
    'NAGAON',
    'NALBARI',
    'SIVASAGAR',
    'SONITPUR',
    'SOUTH SALMARA-MANKACHAR',
    'TAMULPUR',
    'TINSUKIA',
    'UDALGURI',
    'WEST KARBI ANGLONG',
  ],
  'BIHAR': [
    'ARARIA',
    'ARWAL',
    'AURANGABAD',
    'BANKA',
    'BEGUSARAI',
    'BHAGALPUR',
    'BHOJPUR',
    'BUXAR',
    'DARBHANGA',
    'EAST CHAMPARAN',
    'GAYA',
    'GOPALGANJ',
    'JAMUI',
    'JEHANABAD',
    'KAIMUR',
    'KATIHAR',
    'KHAGARIA',
    'KISHANGANJ',
    'LAKHISARAI',
    'MADHEPURA',
    'MADHUBANI',
    'MUNGER',
    'MUZAFFARPUR',
    'NALANDA',
    'NAWADA',
    'PATNA',
    'PURNEA',
    'ROHTAS',
    'SAHARSA',
    'SAMASTIPUR',
    'SARAN',
    'SHEIKHPURA',
    'SHEOHAR',
    'SITAMARHI',
    'SIWAN',
    'SUPAUL',
    'VAISHALI',
    'WEST CHAMPARAN',
  ],
  'CHANDIGARH': [
    'CHANDIGARH',
  ],
  'CHHATTISGARH': [
    'BALOD',
    'BALODA BAZAR',
    'BALRAMPUR',
    'BASTAR',
    'BEMETARA',
    'BIJAPUR',
    'BILASPUR',
    'DANTEWADA',
    'DHAMTARI',
    'DURG',
    'GARIYABAND',
    'GAURELA PENDRA MARWAHI',
    'JANJGIR-CHAMPA',
    'JASHPUR',
    'KABIRDHAM',
    'KANKER',
    'KONDAGAON',
    'KORBA',
    'KOREA',
    'MAHASAMUND',
    'MANENDRAGARH-CHIRMIRI-BHARATPUR',
    'MOHLA-MANPUR-AMBAGARH CHOWKI',
    'MUNGELI',
    'NARAYANPUR',
    'RAIGARH',
    'RAIPUR',
    'RAJNANDGAON',
    'SAKTI',
    'SARANGARH-BILAIGARH',
    'SUKMA',
    'SURAJPUR',
    'SURGUJA',
  ],
  'DADRA AND NAGAR HAVELI': [
    'DADRA AND NAGAR HAVELI',
  ],
  'DAMAN AND DIU': [
    'DAMAN',
    'DIU',
  ],
  'DELHI': [
    'CENTRAL DELHI',
    'EAST DELHI',
    'NEW DELHI',
    'NORTH DELHI',
    'NORTH EAST DELHI',
    'NORTH WEST DELHI',
    'SHAHDARA',
    'SOUTH DELHI',
    'SOUTH EAST DELHI',
    'SOUTH WEST DELHI',
    'WEST DELHI',
  ],
  'GOA': [
    'NORTH GOA',
    'SOUTH GOA',
  ],
  'GUJARAT': [
    'AHMEDABAD',
    'AMRELI',
    'ANAND',
    'ARAVALLI',
    'BANASKANTHA',
    'BHARUCH',
    'BHAVNAGAR',
    'BOTAD',
    'CHHOTA UDEPUR',
    'DAHOD',
    'DANG',
    'DEVBHOOMI DWARKA',
    'GANDHINAGAR',
    'GIR SOMNATH',
    'JAMNAGAR',
    'JUNAGADH',
    'KHEDA',
    'KUTCH',
    'MAHISAGAR',
    'MEHSANA',
    'MORBI',
    'NARMADA',
    'NAVSARI',
    'PANCHMAHAL',
    'PATAN',
    'PORBANDAR',
    'RAJKOT',
    'SABARKANTHA',
    'SURAT',
    'SURENDRANAGAR',
    'TAPI',
    'VADODARA',
    'VALSAD',
  ],
  'HARYANA': [
    'AMBALA',
    'BHIWANI',
    'CHARKHI DADRI',
    'FARIDABAD',
    'FATEHABAD',
    'GURUGRAM',
    'HISAR',
    'JHAJJAR',
    'JIND',
    'KAITHAL',
    'KARNAL',
    'KURUKSHETRA',
    'MAHENDRAGARH',
    'NUH',
    'PALWAL',
    'PANCHKULA',
    'PANIPAT',
    'REWARI',
    'ROHTAK',
    'SIRSA',
    'SONIPAT',
    'YAMUNANAGAR',
  ],
  'HIMACHAL PRADESH': [
    'BILASPUR',
    'CHAMBA',
    'HAMIRPUR',
    'KANGRA',
    'KINNAUR',
    'KULLU',
    'LAHAUL AND SPITI',
    'MANDI',
    'SHIMLA',
    'SIRMAUR',
    'SOLAN',
    'UNA',
  ],
  'JAMMU AND KASHMIR': [
    'ANANTNAG',
    'BANDIPORA',
    'BARAMULLA',
    'BUDGAM',
    'DODA',
    'GANDERBAL',
    'JAMMU',
    'KATHUA',
    'KISHTWAR',
    'KULGAM',
    'KUPWARA',
    'POONCH',
    'PULWAMA',
    'RAJOURI',
    'RAMBAN',
    'REASI',
    'SAMBA',
    'SHOPIAN',
    'SRINAGAR',
    'UDHAMPUR',
  ],
  'JHARKHAND': [
    'BOKARO',
    'CHATRA',
    'DEOGHAR',
    'DHANBAD',
    'DUMKA',
    'EAST SINGHBHUM',
    'GARHWA',
    'GIRIDIH',
    'GODDA',
    'GUMLA',
    'HAZARIBAGH',
    'JAMTARA',
    'KHUNTI',
    'KODERMA',
    'LATEHAR',
    'LOHARDAGA',
    'PAKUR',
    'PALAMU',
    'RAMGARH',
    'RANCHI',
    'SAHIBGANJ',
    'SARAIKELA KHARSAWAN',
    'SIMDEGA',
    'WEST SINGHBHUM',
  ],
  'KARNATAKA': [
    'BAGALKOTE',
    'BALLARI',
    'BELAGAVI',
    'BENGALURU RURAL',
    'BENGALURU URBAN',
    'BIDAR',
    'CHAMARAJANAGARA',
    'CHIKKABALLAPURA',
    'CHIKKAMAGALURU',
    'CHITRADURGA',
    'DAKSHINA KANNADA',
    'DAVANAGERE',
    'DHARWAD',
    'GADAG',
    'HASSAN',
    'HAVERI',
    'KALABURAGI',
    'KODAGU',
    'KOLAR',
    'KOPPAL',
    'MANDYA',
    'MYSURU',
    'RAICHUR',
    'RAMANAGARA',
    'SHIVAMOGGA',
    'TUMAKURU',
    'UDUPI',
    'UTTARA KANNADA',
    'VIJAYANAGARA',
    'VIJAYAPURA',
    'YADGIR',
  ],
  'KERALA': [
    'ALAPPUZHA',
    'ERNAKULAM',
    'IDUKKI',
    'KANNUR',
    'KASARAGOD',
    'KOLLAM',
    'KOTTAYAM',
    'KOZHIKODE',
    'MALAPPURAM',
    'PALAKKAD',
    'PATHANAMTHITTA',
    'THIRUVANANTHAPURAM',
    'THRISSUR',
    'WAYANAD',
  ],
  'LADAKH': [
    'KARGIL',
    'LEH',
  ],
  'LAKSHADWEEP': [
    'LAKSHADWEEP',
  ],
  'MADHYA PRADESH': [
    'AGAR MALWA',
    'ALIRAJPUR',
    'ANUPPUR',
    'ASHOKNAGAR',
    'BALAGHAT',
    'BARWANI',
    'BETUL',
    'BHIND',
    'BHOPAL',
    'BURHANPUR',
    'CHHATARPUR',
    'CHHINDWARA',
    'DAMOH',
    'DATIA',
    'DEWAS',
    'DHAR',
    'DINDORI',
    'GUNA',
    'GWALIOR',
    'HARDA',
    'HOSHANGABAD',
    'INDORE',
    'JABALPUR',
    'JHABUA',
    'KATNI',
    'KHANDWA',
    'KHARGONE',
    'MAU GANJ',
    'MANDLA',
    'MANDSAUR',
    'MORENA',
    'NARSINGHPUR',
    'NEEMUCH',
    'NIWARI',
    'PANNA',
    'RAISEN',
    'RAJGARH',
    'RATLAM',
    'REWA',
    'SAGAR',
    'SATNA',
    'SEHORE',
    'SEONI',
    'SHAHDOL',
    'SHAJAPUR',
    'SHEOPUR',
    'SHIVPURI',
    'SIDHI',
    'SINGRAULI',
    'TIKAMGARH',
    'UJJAIN',
    'UMARIA',
    'VIDISHA',
  ],
  'MAHARASHTRA': [
    'AHMEDNAGAR',
    'AKOLA',
    'AMRAVATI',
    'AURANGABAD',
    'BEED',
    'BHANDARA',
    'BULDHANA',
    'CHANDRAPUR',
    'DHULE',
    'GADCHIROLI',
    'GONDIA',
    'HINGOLI',
    'JALGAON',
    'JALNA',
    'KOLHAPUR',
    'LATUR',
    'MUMBAI CITY',
    'MUMBAI SUBURBAN',
    'NAGPUR',
    'NANDED',
    'NANDURBAR',
    'NASHIK',
    'OSMANABAD',
    'PALGHAR',
    'PARBHANI',
    'PUNE',
    'RAIGAD',
    'RATNAGIRI',
    'SANGLI',
    'SATARA',
    'SINDHUDURG',
    'SOLAPUR',
    'THANE',
    'WARDHA',
    'WASHIM',
    'YAVATMAL',
  ],
  'MANIPUR': [
    'BISHNUPUR',
    'CHANDEL',
    'CHURACHANDPUR',
    'IMPHAL EAST',
    'IMPHAL WEST',
    'JIRIBAM',
    'KAKCHING',
    'KAMJONG',
    'KANGPOKPI',
    'NONEY',
    'PHERZAWL',
    'SENAPATI',
    'TAMENGLONG',
    'TENGNOUPAL',
    'THOUBAL',
    'UKHRUL',
  ],
  'MEGHALAYA': [
    'EAST GARO HILLS',
    'EAST JAINTIA HILLS',
    'EAST KHASI HILLS',
    'EASTERN WEST KHASI HILLS',
    'NORTH GARO HILLS',
    'RI BHOI',
    'SOUTH GARO HILLS',
    'SOUTH WEST GARO HILLS',
    'SOUTH WEST KHASI HILLS',
    'WEST GARO HILLS',
    'WEST JAINTIA HILLS',
    'WEST KHASI HILLS',
  ],
  'MIZORAM': [
    'AIZAWL',
    'CHAMPHAI',
    'HNAHTHIAL',
    'KHAWZAWL',
    'KOLASIB',
    'LAWNGTLAI',
    'LUNGLEI',
    'MAMIT',
    'SAITUAL',
    'SERCHHIP',
    'SIAHA',
  ],
  'NAGALAND': [
    'CHUMOUKEDIMA',
    'DIMAPUR',
    'KIPHIRE',
    'KOHIMA',
    'LONGLENG',
    'MOKOKCHUNG',
    'MON',
    'NIULAND',
    'NOKLAK',
    'PEREN',
    'PHEK',
    'SHAMATOR',
    'TSEMINYU',
    'TUENSANG',
    'WOKHA',
    'ZUNHEBOTO',
  ],
  'ODISHA': [
    'ANGUL',
    'BALANGIR',
    'BALASORE',
    'BARGARH',
    'BHADRAK',
    'BOUDH',
    'CUTTACK',
    'DEOGARH',
    'DHENKANAL',
    'GAJAPATI',
    'GANJAM',
    'JAGATSINGHPUR',
    'JAJPUR',
    'JHARSUGUDA',
    'KALAHANDI',
    'KANDHAMAL',
    'KENDRAPARA',
    'KENDUJHAR',
    'KHORDHA',
    'KORAPUT',
    'MALKANGIRI',
    'MAYURBHANJ',
    'NABARANGPUR',
    'NAYAGARH',
    'NUAPADA',
    'PURI',
    'RAYAGADA',
    'SAMBALPUR',
    'SUBARNAPUR',
    'SUNDARGARH',
  ],
  'PUDUCHERRY': [
    'KARAIKAL',
    'MAHE',
    'PUDUCHERRY',
    'YANAM',
  ],
  'PUNJAB': [
    'AMRITSAR',
    'BARNALA',
    'BATHINDA',
    'FARIDKOT',
    'FATEHGARH SAHIB',
    'FAZILKA',
    'FEROZEPUR',
    'GURDASPUR',
    'HOSHIARPUR',
    'JALANDHAR',
    'KAPURTHALA',
    'LUDHIANA',
    'MALERKOTLA',
    'MANSA',
    'MOGA',
    'MUKTSAR',
    'PATHANKOT',
    'PATIALA',
    'RUPNAGAR',
    'SAHIBZADA AJIT SINGH NAGAR',
    'SANGRUR',
    'SHAHID BHAGAT SINGH NAGAR',
    'TARN TARAN',
  ],
  'RAJASTHAN': [
    'AJMER',
    'ALWAR',
    'ANUPGARH',
    'BALOTRA',
    'BANSWARA',
    'BARAN',
    'BARMER',
    'BEAWAR',
    'BHARATPUR',
    'BHILWARA',
    'BIKANER',
    'BUNDI',
    'CHITTORGARH',
    'CHURU',
    'DAUSA',
    'DEEG',
    'DHOLPUR',
    'DIDWANA-KUCHAMAN',
    'DUDU',
    'DUNGARPUR',
    'GANGANAGAR',
    'GANGAPUR CITY',
    'HANUMANGARH',
    'JAIPUR',
    'JAIPUR RURAL',
    'JAISALMER',
    'JALORE',
    'JHALAWAR',
    'JHUNJHUNU',
    'JODHPUR',
    'JODHPUR RURAL',
    'KARAULI',
    'KEKRI',
    'KHAIRTHAL-TIJARA',
    'KOTA',
    'KOTPUTLI-BEHROR',
    'NAGAUR',
    'NEEM KA THANA',
    'PALI',
    'PHALODI',
    'PRATAPGARH',
    'RAJSAMAND',
    'SALUMBAR',
    'SANCHORE',
    'SAWAI MADHOPUR',
    'SHAHURA',
    'SIKAR',
    'SIROHI',
    'TONK',
    'UDAIPUR',
  ],
  'SIKKIM': [
    'GANGTOK',
    'GYALSHING',
    'MANGAN',
    'NAMCHI',
    'PAKYONG',
    'SORENG',
  ],
  'TAMIL NADU': [
    'ARIYALUR',
    'CHENGALPATTU',
    'CHENNAI',
    'COIMBATORE',
    'CUDDALORE',
    'DHARMAPURI',
    'DINDIGUL',
    'ERODE',
    'KALLAKURICHI',
    'KANCHEEPURAM',
    'KANYAKUMARI',
    'KARUR',
    'KRISHNAGIRI',
    'MADURAI',
    'MAYILADUTHURAI',
    'NAGAPATTINAM',
    'NAMAKKAL',
    'NILGIRIS',
    'PERAMBALUR',
    'PUDUKKOTTAI',
    'RAMANATHAPURAM',
    'RANIPET',
    'SALEM',
    'SIVAGANGA',
    'TENKASI',
    'THANJAVUR',
    'THENI',
    'THOOTHUKUDI',
    'TIRUCHIRAPPALLI',
    'TIRUNELVELI',
    'TIRUPATHUR',
    'TIRUPPUR',
    'TIRUVALLUR',
    'TIRUVANNAMALAI',
    'TIRUVARUR',
    'VELLORE',
    'VILUPPURAM',
    'VIRUDHUNAGAR',
  ],
  'TELANGANA': [
    'ADILABAD',
    'BHADRADRI KOTHAGUDEM',
    'HANUMAKONDA',
    'HYDERABAD',
    'JAGITIAL',
    'JANGAON',
    'JAYASHANKAR BHUPALPALLY',
    'JOGULAMBA GADWAL',
    'KAMAREDDY',
    'KARIMNAGAR',
    'KHAMMAM',
    'KUMURAM BHEEM',
    'MAHABUBABAD',
    'MAHABUBNAGAR',
    'MANCHERIAL',
    'MEDAK',
    'MEDCHAL-MALKAJGIRI',
    'MULUGU',
    'NAGARKURNOOL',
    'NALGONDA',
    'NARAYANPET',
    'NIRMAL',
    'NIZAMABAD',
    'PEDDAPALLI',
    'RAJANNA SIRCILLA',
    'RANGAREDDY',
    'SANGAREDDY',
    'SIDDIPET',
    'SURYAPET',
    'VIKARABAD',
    'WANAPARTHY',
    'WARANGAL',
    'YADADRI BHUVANAGIRI',
  ],
  'TRIPURA': [
    'DHALAI',
    'GOMATI',
    'KHOWAI',
    'NORTH TRIPURA',
    'SEPAHIJALA',
    'SOUTH TRIPURA',
    'UNAKOTI',
    'WEST TRIPURA',
  ],
  'UTTAR PRADESH': [
    'AGRA',
    'ALIGARH',
    'AMBEDKAR NAGAR',
    'AMETHI',
    'AMROHA',
    'AURAIYA',
    'AYODHYA',
    'AZAMGARH',
    'BAGHPAT',
    'BAHRAICH',
    'BALLIA',
    'BALRAMPUR',
    'BANDA',
    'BARABANKI',
    'BAREILLY',
    'BASTI',
    'BHADOHI',
    'BIJNOR',
    'BUDAUN',
    'BULANDSHAHR',
    'CHANDAULI',
    'CHITRAKOOT',
    'DEORIA',
    'ETAH',
    'ETAWAH',
    'FARRUKHABAD',
    'FATEHPUR',
    'FIROZABAD',
    'GAUTAM BUDDHA NAGAR',
    'GHAZIABAD',
    'GHAZIPUR',
    'GONDA',
    'GORAKHPUR',
    'HAMIRPUR',
    'HAPUR',
    'HARDOI',
    'HATHRAS',
    'JALAUN',
    'JAUNPUR',
    'JHANSI',
    'KANNAUJ',
    'KANPUR DEHAT',
    'KANPUR NAGAR',
    'KASGANJ',
    'KAUSHAMBI',
    'KHERI',
    'KUSHINAGAR',
    'LALITPUR',
    'LUCKNOW',
    'MAHARAJGANJ',
    'MAHOBA',
    'MAINPURI',
    'MATHURA',
    'MAU',
    'MEERUT',
    'MIRZAPUR',
    'MORADABAD',
    'MUZAFFARNAGAR',
    'PILIBHIT',
    'PRATAPGARH',
    'PRAYAGRAJ',
    'RAEBARELI',
    'RAMPUR',
    'SAHARANPUR',
    'SAMBHAL',
    'SANT KABIR NAGAR',
    'SHAHJAHANPUR',
    'SHAMLI',
    'SHRAVASTI',
    'SIDDHARTHNAGAR',
    'SITAPUR',
    'SONBHADRA',
    'SULTANPUR',
    'UNNAO',
    'VARANASI',
  ],
  'UTTARAKHAND': [
    'ALMORA',
    'BAGESHWAR',
    'CHAMOLI',
    'CHAMPAWAT',
    'DEHRADUN',
    'HARIDWAR',
    'NAINITAL',
    'PAURI GARHWAL',
    'PITHORAGARH',
    'RUDRAPRAYAG',
    'TEHRI GARHWAL',
    'UDHAM SINGH NAGAR',
    'UTTARKASHI',
  ],
  'WEST BENGAL': [
    'ALIPURDUAR',
    'BANKURA',
    'BIRBHUM',
    'COOCH BEHAR',
    'DAKSHIN DINAJPUR',
    'DARJEELING',
    'HOOGHLY',
    'HOWRAH',
    'JALPAIGURI',
    'JHARGRAM',
    'KALIMPONG',
    'KOLKATA',
    'MALDA',
    'MURSHIDABAD',
    'NADIA',
    'NORTH 24 PARGANAS',
    'PASCHIM BARDHAMAN',
    'PASCHIM MEDINIPUR',
    'PURBA BARDHAMAN',
    'PURBA MEDINIPUR',
    'PURULIA',
    'SOUTH 24 PARGANAS',
    'UTTAR DINAJPUR',
  ],
}

/**
 * Normalizes a state name to match keys in INDIAN_STATE_DISTRICTS_MAP.
 */
export function normalizeIndianStateName(stateName?: string | null): string | null {
  if (!stateName || typeof stateName !== 'string') return null
  const cleaned = stateName.trim().toUpperCase()
  if (INDIAN_STATE_DISTRICTS_MAP[cleaned]) {
    return cleaned
  }
  // Try case-insensitive lookup
  for (const key of Object.keys(INDIAN_STATE_DISTRICTS_MAP)) {
    if (key.toUpperCase() === cleaned) {
      return key
    }
  }
  return null
}

/**
 * Returns the list of district select options for a given Indian State.
 * If the state is not found or empty, returns an empty array.
 */
export function getDistrictsForIndianState(stateName?: string | null): PortalSelectOption[] {
  const normalized = normalizeIndianStateName(stateName)
  if (!normalized) return []
  const districts = INDIAN_STATE_DISTRICTS_MAP[normalized] || []
  return districts.map((d) => ({
    value: d,
    label: d,
  }))
}

/**
 * Given a district name, finds the corresponding Indian State name if it uniquely matches.
 */
export function getStateForIndianDistrict(districtName?: string | null): string | null {
  if (!districtName || typeof districtName !== 'string') return null
  const cleaned = districtName.trim().toUpperCase()
  for (const [state, districts] of Object.entries(INDIAN_STATE_DISTRICTS_MAP)) {
    if (districts.some((d) => d.toUpperCase() === cleaned)) {
      return state
    }
  }
  return null
}

/**
 * Flat list of all unique Indian districts across all states, sorted alphabetically.
 */
export const ALL_INDIAN_DISTRICTS_OPTIONS: PortalSelectOption[] = (() => {
  const set = new Set<string>()
  for (const list of Object.values(INDIAN_STATE_DISTRICTS_MAP)) {
    for (const d of list) {
      set.add(d)
    }
  }
  return Array.from(set)
    .sort()
    .map((d) => ({ value: d, label: d }))
})()
