import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_BASIC_DETAILS_SELECTORS } from '../../selectors/bangladesh/basicDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Basic Details page (/visa/BasicDetails)
 * Canonical Page Identity: 'BASIC_DETAILS'
 * 
 * Verified field mappings:
 * - All normal form fields with verified DOM selectors are marked 'verified'.
 *   (Autofill executes when confirmed document data exists; left untouched if missing).
 */
export const BANGLADESH_BASIC_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'bd_basic_surname',
    section: 'personal-information',
    targetField: 'appl.surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_given_name',
    section: 'personal-information',
    targetField: 'appl.applname',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_changed_surname_check',
    section: 'personal-information',
    targetField: 'appl.changedSurnameCheck',
    sourceField: 'personalInfo.hasChangedName',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.changedSurnameCheck,
    inputType: 'checkbox',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_gender',
    section: 'personal-information',
    targetField: 'appl.applsex',
    sourceField: 'personalInfo.gender',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.gender,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_town_city_of_birth',
    section: 'personal-information',
    targetField: 'appl.placbrth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_country_of_birth',
    section: 'personal-information',
    targetField: 'appl.country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_national_id',
    section: 'personal-information',
    targetField: 'appl.nic_no',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_religion',
    section: 'personal-information',
    targetField: 'appl.religion',
    sourceField: 'personalInfo.religion',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.religion,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_identity_marks',
    section: 'personal-information',
    targetField: 'appl.visual_mark',
    sourceField: 'personalInfo.visibleIdentificationMarks',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.visibleIdentificationMarks,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_educational_qualification',
    section: 'personal-information',
    targetField: 'appl.edu_id',
    sourceField: 'personalInfo.educationalQualification',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.educationalQualification,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_nationality_by',
    section: 'personal-information',
    targetField: 'appl.nationality_by',
    sourceField: 'personalInfo.nationalityAcquiredBy',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalityBy,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_passport_number',
    section: 'passport-information',
    targetField: 'appl.passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_place_of_issue',
    section: 'passport-information',
    targetField: 'appl.passport_issue_place',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_passport_issue_date',
    section: 'passport-information',
    targetField: 'appl.passport_issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_passport_expiry_date',
    section: 'passport-information',
    targetField: 'appl.passport_expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_other_ppt_flag',
    section: 'passport-information',
    targetField: 'appl.oth_ppt',
    sourceField: 'passport.holdsOtherPassport',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_other_ppt_no',
    section: 'passport-information',
    targetField: 'appl.oth_pptno',
    sourceField: 'passport.otherPassportDetails.passportNumber',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_other_ppt_place',
    section: 'passport-information',
    targetField: 'appl.oth_ppt_issue_place',
    sourceField: 'passport.otherPassportDetails.placeOfIssue',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportPlaceOfIssue,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_other_ppt_country',
    section: 'passport-information',
    targetField: 'appl.prev_passport_country_issue',
    sourceField: 'passport.otherPassportDetails.countryOfIssue',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportCountryOfIssue,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_other_ppt_nat',
    section: 'passport-information',
    targetField: 'appl.other_ppt_nationality',
    sourceField: 'passport.otherPassportDetails.nationalityInPassport',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
]

