import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_BASIC_DETAILS_SELECTORS } from '../../selectors/bangladesh/basicDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Basic Details page (/visa/BasicDetails)
 * Canonical Page Identity: 'BASIC_DETAILS'
 * 
 * Verified field mappings:
 * - All normal form fields with verified DOM selectors are marked 'verified'.
 *   (Autofill executes when confirmed document data exists; left untouched if missing).
 */
export const BANGLADESH_BASIC_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'bd_basic_surname',
    section: 'personal-information',
    targetField: 'applicant_surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.surname,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_given_name',
    section: 'personal-information',
    targetField: 'applicant_given_name',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.givenName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_gender',
    section: 'personal-information',
    targetField: 'gender',
    sourceField: 'personalInfo.gender',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.gender,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_dob',
    section: 'personal-information',
    targetField: 'date_of_birth',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_town_city_of_birth',
    section: 'personal-information',
    targetField: 'city_of_birth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_country_of_birth',
    section: 'personal-information',
    targetField: 'country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_national_id',
    section: 'personal-information',
    targetField: 'national_id',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_religion',
    section: 'personal-information',
    targetField: 'religion',
    sourceField: 'personalInfo.religion',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.religion,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_identity_marks',
    section: 'personal-information',
    targetField: 'visual_mark',
    sourceField: 'personalInfo.visibleIdentificationMarks',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.visibleIdentificationMarks,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_educational_qualification',
    section: 'personal-information',
    targetField: 'educational_qualification',
    sourceField: 'personalInfo.educationalQualification',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.educationalQualification,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_nationality',
    section: 'personal-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationality,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_passport_number',
    section: 'passport-information',
    targetField: 'passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_place_of_issue',
    section: 'passport-information',
    targetField: 'place_of_issue',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_passport_issue_date',
    section: 'passport-information',
    targetField: 'issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.issueDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_passport_expiry_date',
    section: 'passport-information',
    targetField: 'expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'verified',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_other_ppt_no',
    section: 'passport-information',
    targetField: 'other_pptno',
    sourceField: 'passport.otherPassportDetails.passportNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_other_ppt_place',
    section: 'passport-information',
    targetField: 'other_ppt_issue_place',
    sourceField: 'passport.otherPassportDetails.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportPlaceOfIssue,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_other_ppt_country',
    section: 'passport-information',
    targetField: 'prev_passport_country_issue',
    sourceField: 'passport.otherPassportDetails.countryOfIssue',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportCountryOfIssue,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_other_ppt_nat',
    section: 'passport-information',
    targetField: 'other_ppt_nationality',
    sourceField: 'passport.otherPassportDetails.nationalityInPassport',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.otherPassportNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'BASIC_DETAILS',
  },
]

