import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_BASIC_DETAILS_SELECTORS } from '../../selectors/bangladesh/basicDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Basic Details page (/visa/BasicDetails)
 * Canonical Page Identity: 'BASIC_DETAILS'
 * 
 * Field Status Audit:
 * - All automated fields derived from confirmed document/profile: 'needs-verification'
 * - Control types strictly specified: 'text', 'date', 'select', 'radio'
 */
export const BANGLADESH_BASIC_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'bd_basic_surname',
    section: 'personal-information',
    targetField: 'applicant_surname',
    sourceField: 'personalInfo.surname',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.surname,
    inputType: 'text',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_given_name',
    section: 'personal-information',
    targetField: 'applicant_given_name',
    sourceField: 'personalInfo.givenNames',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.givenName,
    inputType: 'text',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_gender',
    section: 'personal-information',
    targetField: 'gender',
    sourceField: 'personalInfo.gender',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.gender,
    inputType: 'select',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_dob',
    section: 'personal-information',
    targetField: 'date_of_birth',
    sourceField: 'personalInfo.dateOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.dateOfBirth,
    inputType: 'date',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_town_city_of_birth',
    section: 'personal-information',
    targetField: 'city_of_birth',
    sourceField: 'personalInfo.townCityOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.townCityOfBirth,
    inputType: 'text',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_country_of_birth',
    section: 'personal-information',
    targetField: 'country_of_birth',
    sourceField: 'personalInfo.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.countryOfBirth,
    inputType: 'select',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_national_id',
    section: 'personal-information',
    targetField: 'national_id',
    sourceField: 'personalInfo.nationalIdNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationalIdNumber,
    inputType: 'text',
    status: 'needs-verification',
    required: false,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_religion',
    section: 'personal-information',
    targetField: 'religion',
    sourceField: 'personalInfo.religion',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.religion,
    inputType: 'select',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_educational_qualification',
    section: 'personal-information',
    targetField: 'educational_qualification',
    sourceField: 'personalInfo.educationalQualification',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.educationalQualification,
    inputType: 'select',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_nationality',
    section: 'personal-information',
    targetField: 'nationality',
    sourceField: 'personalInfo.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.nationality,
    inputType: 'select',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_passport_number',
    section: 'passport-information',
    targetField: 'passport_number',
    sourceField: 'passport.passportNumber',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.passportNumber,
    inputType: 'text',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_basic_place_of_issue',
    section: 'passport-information',
    targetField: 'place_of_issue',
    sourceField: 'passport.placeOfIssue',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.placeOfIssue,
    inputType: 'text',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
  },
  {
    id: 'bd_basic_passport_issue_date',
    section: 'passport-information',
    targetField: 'issue_date',
    sourceField: 'passport.issueDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.issueDate,
    inputType: 'date',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_basic_passport_expiry_date',
    section: 'passport-information',
    targetField: 'expiry_date',
    sourceField: 'passport.expiryDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_BASIC_DETAILS_SELECTORS.expiryDate,
    inputType: 'date',
    status: 'needs-verification',
    required: true,
    page: 'BASIC_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
]
