import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_FAMILY_DETAILS_SELECTORS } from '../../selectors/bangladesh/familyDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Family Details page (/visa/FamilyDetails)
 * Canonical Page Identity: 'FAMILY_DETAILS'
 */
export const BANGLADESH_FAMILY_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  // Present Address
  {
    id: 'bd_family_pres_add1',
    section: 'address-information',
    targetField: 'pres_addr1',
    sourceField: 'presentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_add2',
    section: 'address-information',
    targetField: 'pres_addr2',
    sourceField: 'presentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_add3',
    section: 'address-information',
    targetField: 'state_name',
    sourceField: 'presentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentStateCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pincode',
    section: 'address-information',
    targetField: 'pincode',
    sourceField: 'presentAddress.postalCode',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_phone',
    section: 'address-information',
    targetField: 'pres_phone',
    sourceField: 'contact.phone',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mobile',
    section: 'address-information',
    targetField: 'mobile',
    sourceField: 'contact.mobile',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.mobile,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },

  // Permanent Address
  {
    id: 'bd_family_perm_add1',
    section: 'address-information',
    targetField: 'perm_add1',
    sourceField: 'permanentAddress.addressLine1',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_perm_add2',
    section: 'address-information',
    targetField: 'perm_add2',
    sourceField: 'permanentAddress.addressLine2',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_perm_add3',
    section: 'address-information',
    targetField: 'perm_add3',
    sourceField: 'permanentAddress.villageTownCity',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentStateCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },

  // Family Members
  {
    id: 'bd_family_father_name',
    section: 'family-information',
    targetField: 'fthrname',
    sourceField: 'family.father.name',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_birth_place',
    section: 'family-information',
    targetField: 'father_place_of_birth',
    sourceField: 'family.father.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_country_birth',
    section: 'family-information',
    targetField: 'father_country_of_birth',
    sourceField: 'family.father.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_nat',
    section: 'family-information',
    targetField: 'father_nationality',
    sourceField: 'family.father.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_name',
    section: 'family-information',
    targetField: 'mother_name',
    sourceField: 'family.mother.name',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_birth_place',
    section: 'family-information',
    targetField: 'mother_place_of_birth',
    sourceField: 'family.mother.placeOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_country_birth',
    section: 'family-information',
    targetField: 'mother_country_of_birth',
    sourceField: 'family.mother.countryOfBirth',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_nat',
    section: 'family-information',
    targetField: 'mother_nationality',
    sourceField: 'family.mother.nationality',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_marital_status',
    section: 'family-information',
    targetField: 'marital_status',
    sourceField: 'family.spouse.name',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.maritalStatus,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },

  // Occupation & Employment
  {
    id: 'bd_family_occupation',
    section: 'employment-information',
    targetField: 'occupation',
    sourceField: 'employment.presentOccupation',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.occupation,
    inputType: 'select',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empname',
    section: 'employment-information',
    targetField: 'empname',
    sourceField: 'employment.employerName',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empdesignation',
    section: 'employment-information',
    targetField: 'empdesignation',
    sourceField: 'employment.designationRank',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerDesignation,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empphone',
    section: 'employment-information',
    targetField: 'empphone',
    sourceField: 'employment.employerPhone',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_org',
    section: 'employment-information',
    targetField: 'previous_organization',
    sourceField: 'employment.militaryOrganization',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOrganization,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
]
