import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_FAMILY_DETAILS_SELECTORS } from '../../selectors/bangladesh/familyDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Family Details page (/visa/FamilyDetails)
 * Canonical Page Identity: 'FAMILY_DETAILS'
 */
export const BANGLADESH_FAMILY_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  // Present Address
  {
    id: 'bd_family_pres_add1',
    section: 'address-information',
    targetField: 'pres_addr1',
    sourceField: 'presentAddress.addressLine1',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_add2',
    section: 'address-information',
    targetField: 'pres_addr2',
    sourceField: 'presentAddress.addressLine2',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_add3',
    section: 'address-information',
    targetField: 'state_name',
    sourceField: 'presentAddress.villageTownCity',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentStateCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pincode',
    section: 'address-information',
    targetField: 'pincode',
    sourceField: 'presentAddress.postalCode',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPostalCode,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_pres_phone',
    section: 'address-information',
    targetField: 'pres_phone',
    sourceField: 'contact.phone',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.presentPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mobile',
    section: 'address-information',
    targetField: 'mobile',
    sourceField: 'contact.mobile',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.mobile,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_same_address',
    section: 'address-information',
    targetField: 'sameAddress',
    sourceType: 'manual',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.sameAddress,
    inputType: 'checkbox',
    status: 'manual-required',
    required: false,
    page: 'FAMILY_DETAILS',
    notes: 'Same Address checkbox is strictly manual-only. Never automated or clicked.',
  },

  // Permanent Address
  {
    id: 'bd_family_perm_add1',
    section: 'address-information',
    targetField: 'perm_add1',
    sourceField: 'permanentAddress.addressLine1',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress1,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_perm_add2',
    section: 'address-information',
    targetField: 'perm_add2',
    sourceField: 'permanentAddress.addressLine2',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_perm_add3',
    section: 'address-information',
    targetField: 'perm_add3',
    sourceField: 'permanentAddress.villageTownCity',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.permanentStateCity,
    inputType: 'text',
    status: 'verified',
    required: true,
    page: 'FAMILY_DETAILS',
  },

  // Family Members
  {
    id: 'bd_family_father_name',
    section: 'family-information',
    targetField: 'fthrname',
    sourceField: 'family.father.name',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_birth_place',
    section: 'family-information',
    targetField: 'father_place_of_birth',
    sourceField: 'family.father.placeOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_country_birth',
    section: 'family-information',
    targetField: 'father_country_of_birth',
    sourceField: 'family.father.countryOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_nat',
    section: 'family-information',
    targetField: 'father_nationality',
    sourceField: 'family.father.nationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_father_prev_nat',
    section: 'family-information',
    targetField: 'father_prev_nationality',
    sourceField: 'family.father.previousNationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.fatherPreviousNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_name',
    section: 'family-information',
    targetField: 'mother_name',
    sourceField: 'family.mother.name',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherName,
    inputType: 'text',
    status: 'verified',
    required: true,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_birth_place',
    section: 'family-information',
    targetField: 'mother_place_of_birth',
    sourceField: 'family.mother.placeOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherPlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_country_birth',
    section: 'family-information',
    targetField: 'mother_country_of_birth',
    sourceField: 'family.mother.countryOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_nat',
    section: 'family-information',
    targetField: 'mother_nationality',
    sourceField: 'family.mother.nationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_mother_prev_nat',
    section: 'family-information',
    targetField: 'mother_prev_nationality',
    sourceField: 'family.mother.previousNationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.motherPreviousNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_marital_status',
    section: 'family-information',
    targetField: 'marital_status',
    sourceField: 'personalInfo.maritalStatus',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.maritalStatus,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_spouse_name',
    section: 'family-information',
    targetField: 'spouse_name',
    sourceField: 'family.spouse.name',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.spouseName,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_spouse_birth_place',
    section: 'family-information',
    targetField: 'spouse_place_of_birth',
    sourceField: 'family.spouse.placeOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.spousePlaceOfBirth,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_spouse_country_birth',
    section: 'family-information',
    targetField: 'spouse_country_of_birth',
    sourceField: 'family.spouse.countryOfBirth',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.spouseCountryOfBirth,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_spouse_nat',
    section: 'family-information',
    targetField: 'spouse_nationality',
    sourceField: 'family.spouse.nationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.spouseNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_spouse_prev_nat',
    section: 'family-information',
    targetField: 'spouse_prev_nationality',
    sourceField: 'family.spouse.previousNationality',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.spousePreviousNationality,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_grandparent_flag',
    section: 'family-information',
    targetField: 'grandparent_flag',
    sourceField: 'family.hasPakistanRelation',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.grandparentFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_grandparent_details',
    section: 'family-information',
    targetField: 'grandparent_details',
    sourceField: 'family.pakistanRelationDetails',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.grandparentDetails,
    inputType: 'textarea',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },

  // Occupation & Employment
  {
    id: 'bd_family_occupation',
    section: 'employment-information',
    targetField: 'occupation',
    sourceField: 'employment.presentOccupation',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.occupation,
    inputType: 'select',
    status: 'verified',
    required: true,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empname',
    section: 'employment-information',
    targetField: 'empname',
    sourceField: 'employment.employerName',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerName,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empdesignation',
    section: 'employment-information',
    targetField: 'empdesignation',
    sourceField: 'employment.designationRank',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerDesignation,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empaddress',
    section: 'employment-information',
    targetField: 'empaddress',
    sourceField: 'employment.employerAddress',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerAddress,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_empphone',
    section: 'employment-information',
    targetField: 'empphone',
    sourceField: 'employment.employerPhone',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.employerPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_occupation',
    section: 'employment-information',
    targetField: 'previous_occupation',
    sourceField: 'employment.pastOccupation',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOccupation,
    inputType: 'select',
    status: 'verified',
    required: false,
    transform: 'selectOptionMatch',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_prev_org_flag',
    section: 'employment-information',
    targetField: 'prev_org',
    sourceField: 'employment.hasMilitaryService',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOrgFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_org',
    section: 'employment-information',
    targetField: 'previous_organization',
    sourceField: 'employment.militaryOrganization',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousOrganization,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_designation',
    section: 'employment-information',
    targetField: 'previous_designation',
    sourceField: 'employment.militaryDesignation',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousDesignation,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_rank',
    section: 'employment-information',
    targetField: 'previous_rank',
    sourceField: 'employment.militaryRank',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousRank,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
  {
    id: 'bd_family_previous_posting',
    section: 'employment-information',
    targetField: 'previous_posting',
    sourceField: 'employment.militaryPlaceOfPosting',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_FAMILY_DETAILS_SELECTORS.previousPosting,
    inputType: 'text',
    status: 'verified',
    required: false,
    transform: 'uppercase',
    page: 'FAMILY_DETAILS',
  },
]
