import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_VISA_DETAILS_SELECTORS } from '../../selectors/bangladesh/visaDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Visa Details page (/visa/VisaDetails)
 * Canonical Page Identity: 'TRAVEL_DETAILS'
 */
export const BANGLADESH_VISA_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'bd_visa_duration',
    section: 'visa-information',
    targetField: 'duration',
    sourceField: 'travel.duration',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.duration,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_purpose',
    section: 'visa-information',
    targetField: 'purpose',
    sourceField: 'travel.purposeOfVisit',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.purpose,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_comp_name',
    section: 'visa-information',
    targetField: 'comp_name',
    sourceField: 'travel.businessCompanyName',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.businessCompanyName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_comp_address',
    section: 'visa-information',
    targetField: 'comp_address',
    sourceField: 'travel.businessCompanyAddress',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.businessCompanyAddress,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_comp_phone',
    section: 'visa-information',
    targetField: 'comp_phone',
    sourceField: 'travel.businessCompanyPhone',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.businessCompanyPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_comp_email',
    section: 'visa-information',
    targetField: 'comp_email',
    sourceField: 'travel.businessCompanyEmail',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.businessCompanyEmail,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_entry_type',
    section: 'visa-information',
    targetField: 'visa_entry_id',
    sourceField: 'travel.visaEntryType',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.visaEntryType,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_journeydate',
    section: 'visa-information',
    targetField: 'journeydate',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.expectedArrivalDate,
    inputType: 'date',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_visa_entrypoint',
    section: 'visa-information',
    targetField: 'entrypoint',
    sourceField: 'travel.entryPoint',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.entryPoint,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_exitpoint',
    section: 'visa-information',
    targetField: 'exitpoint',
    sourceField: 'travel.exitPoint',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.exitPoint,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_old_visa_flag',
    section: 'previous-visa',
    targetField: 'old_visa_flag',
    sourceField: 'previousVisa.hasPreviousVisa',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_prv_visit_add1',
    section: 'previous-visa',
    targetField: 'prv_visit_add1',
    sourceField: 'previousVisa.visitedAddress1',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress1,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_prv_visit_add2',
    section: 'previous-visa',
    targetField: 'prv_visit_add2',
    sourceField: 'previousVisa.visitedAddress2',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_prv_visit_add3',
    section: 'previous-visa',
    targetField: 'prv_visit_add3',
    sourceField: 'previousVisa.visitedAddress3',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.previousVisitAddress3,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_cities_visited',
    section: 'previous-visa',
    targetField: 'cities_visited',
    sourceField: 'previousVisa.citiesVisited',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.citiesVisitedIndia,
    inputType: 'textarea',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_old_visa_no',
    section: 'previous-visa',
    targetField: 'old_visa_no',
    sourceField: 'previousVisa.visaNumber',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaNumber,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_old_visa_type',
    section: 'previous-visa',
    targetField: 'old_visa_type_id',
    sourceField: 'previousVisa.visaType',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaType,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_old_visa_place',
    section: 'previous-visa',
    targetField: 'oldvisaissueplace',
    sourceField: 'previousVisa.placeOfIssue',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaIssuePlace,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_old_visa_date',
    section: 'previous-visa',
    targetField: 'oldvisaissuedate',
    sourceField: 'previousVisa.dateOfIssue',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.oldVisaIssueDate,
    inputType: 'date',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_visa_refuse_flag',
    section: 'previous-visa',
    targetField: 'refuse_flag',
    sourceField: 'previousVisa.hasRefusal',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.refuseFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_refuse_details',
    section: 'previous-visa',
    targetField: 'refuse_details',
    sourceField: 'previousVisa.refusalDetails',
    sourceType: 'manual',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.refuseDetails,
    inputType: 'textarea',
    status: 'manual-required',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_country_visited',
    section: 'travel-history',
    targetField: 'country_visited',
    sourceField: 'travel.countriesVisited',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.countryVisited,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_saarc_flag',
    section: 'travel-history',
    targetField: 'saarc_flag',
    sourceField: 'travel.visitedSaarc',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.saarcFlag,
    inputType: 'radio',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_saarc_details',
    section: 'travel-history',
    targetField: 'saarc_details',
    sourceField: 'travel.saarcDetails',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.saarcDetails,
    inputType: 'textarea',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_ind_name',
    section: 'reference-information',
    targetField: 'nameofsponsor_ind',
    sourceField: 'reference.name',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_sponsor_ind_add1',
    section: 'reference-information',
    targetField: 'add1ofsponsor_ind',
    sourceField: 'reference.addressLine1',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaAddress1,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_ind_add2',
    section: 'reference-information',
    targetField: 'add2ofsponsor_ind',
    sourceField: 'reference.addressLine2',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_ind_state',
    section: 'reference-information',
    targetField: 'stateofsponsor_ind',
    sourceField: 'reference.state',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorState,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_sponsor_ind_district',
    section: 'reference-information',
    targetField: 'districtofsponsor_ind',
    sourceField: 'reference.district',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorDistrict,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'selectOptionMatch',
  },
  {
    id: 'bd_visa_sponsor_ind_phone',
    section: 'reference-information',
    targetField: 'phoneofsponsor_ind',
    sourceField: 'reference.phone',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_msn_name',
    section: 'reference-information',
    targetField: 'nameofsponsor_msn',
    sourceField: 'sponsorMission.name',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'uppercase',
  },
  {
    id: 'bd_visa_sponsor_msn_add1',
    section: 'reference-information',
    targetField: 'add1ofsponsor_msn',
    sourceField: 'sponsorMission.addressLine1',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionAddress1,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_msn_add2',
    section: 'reference-information',
    targetField: 'add2ofsponsor_msn',
    sourceField: 'sponsorMission.addressLine2',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionAddress2,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_msn_phone',
    section: 'reference-information',
    targetField: 'phoneofsponsor_msn',
    sourceField: 'sponsorMission.phone',
    sourceType: 'confirmed-document',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
]
