import type { IndiaVisaFieldMapping } from '../../mapping.types'
import { BANGLADESH_VISA_DETAILS_SELECTORS } from '../../selectors/bangladesh/visaDetails'

/**
 * Field mappings for Bangladesh Indian Visa Portal - Visa Details page (/visa/VisaDetails)
 * Canonical Page Identity: 'TRAVEL_DETAILS'
 */
export const BANGLADESH_VISA_DETAILS_MAPPINGS: IndiaVisaFieldMapping[] = [
  {
    id: 'bd_visa_duration',
    section: 'visa-information',
    targetField: 'duration',
    sourceField: 'travel.purposeOfVisit',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.duration,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_entry_type',
    section: 'visa-information',
    targetField: 'visa_entry_id',
    sourceField: 'travel.purposeOfVisit',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.visaEntryType,
    inputType: 'select',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_journeydate',
    section: 'visa-information',
    targetField: 'journeydate',
    sourceField: 'travel.intendedArrivalDate',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.expectedArrivalDate,
    inputType: 'date',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
    transform: 'isoDateToDdMmYyyy',
  },
  {
    id: 'bd_visa_sponsor_ind_name',
    section: 'reference-information',
    targetField: 'nameofsponsor_ind',
    sourceField: 'reference.name',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_ind_phone',
    section: 'reference-information',
    targetField: 'phoneofsponsor_ind',
    sourceField: 'reference.phone',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorIndiaPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_msn_name',
    section: 'reference-information',
    targetField: 'nameofsponsor_msn',
    sourceField: 'accommodation.placeHotelName',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionName,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
  {
    id: 'bd_visa_sponsor_msn_phone',
    section: 'reference-information',
    targetField: 'phoneofsponsor_msn',
    sourceField: 'accommodation.phone',
    sourceType: 'applicant-profile',
    selector: BANGLADESH_VISA_DETAILS_SELECTORS.sponsorMissionPhone,
    inputType: 'text',
    status: 'verified',
    required: false,
    page: 'TRAVEL_DETAILS',
  },
]
