import type { ApplicantProfile } from './types'

export const MOCK_SYNTHETIC_APPLICANT: ApplicantProfile = {
  applicantId: 'applicant_synthetic_test_001',
  personalInfo: {
    surname: 'Test',
    givenNames: 'John David',
    hasChangedName: false,
    previousName: '',
    gender: 'male',
    dateOfBirth: '1990-01-15',
    townCityOfBirth: 'Test City',
    countryOfBirth: 'Testland',
    nationalIdNumber: 'NID-999999',
    religion: 'OTHERS',
    visibleIdentificationMarks: 'NONE',
    educationalQualification: 'GRADUATE',
    nationality: 'Testland',
    nationalityAcquiredBy: 'birth',
    previousNationality: '',
  },
  passport: {
    passportNumber: 'TEST000000',
    passportType: 'Ordinary',
    issuingCountry: 'Testland',
    issueDate: '2020-01-01',
    expiryDate: '2030-01-01',
    placeOfIssue: 'Test Passport Office',
    holdsOtherPassport: false,
  },
  presentAddress: {
    addressLine1: '123 Test Street',
    addressLine2: 'Suite 4B',
    villageTownCity: 'Testville',
    district: 'Test District',
    stateProvince: 'Test State',
    country: 'Testland',
    postalCode: '123456',
  },
  permanentAddress: {
    sameAsPresentAddress: true,
    addressLine1: '123 Test Street',
    addressLine2: 'Suite 4B',
    villageTownCity: 'Testville',
    district: 'Test District',
    stateProvince: 'Test State',
    country: 'Testland',
    postalCode: '123456',
  },
  contact: {
    phone: '+1-555-0100',
    mobile: '+1-555-0199',
    email: 'john.test@example.com',
  },
  family: {
    father: {
      name: 'Robert Test',
      nationality: 'Testland',
      placeOfBirth: 'Test City',
      countryOfBirth: 'Testland',
    },
    mother: {
      name: 'Mary Test',
      nationality: 'Testland',
      placeOfBirth: 'Test City',
      countryOfBirth: 'Testland',
    },
    spouse: {
      name: 'Sarah Test',
      nationality: 'Testland',
      placeOfBirth: 'Test City',
      countryOfBirth: 'Testland',
    },
    hasPakistanRelation: false,
    pakistanRelationDetails: '',
  },
  employment: {
    presentOccupation: 'SOFTWARE ENGINEER',
    designationRank: 'SENIOR DEVELOPER',
    employerName: 'Test Corp Inc',
    employerAddress: {
      addressLine1: '456 Tech Park',
      villageTownCity: 'Test City',
      stateProvince: 'Test State',
      country: 'Testland',
      postalCode: '123456',
    },
    employerPhone: '+1-555-0200',
    pastOccupation: 'DEVELOPER',
    hasMilitaryService: false,
  },
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}
